#ifndef CONFIG_H
#define CONFIG_H

#cmakedefine PREFIXDIR "@PREFIXDIR@"
#cmakedefine DATADIR "@DATADIR@"
#cmakedefine PKGDATADIR "@PKGDATADIR@"
#cmakedefine LOCALE_DIR "@LOCALE_DIR@"
#cmakedefine VERSION "@VERSION@"
#cmakedefine BUILDDIR "@BUILDDIR@"
#cmakedefine TESTVALADIR "@TESTVALADIR@"
#cmakedefine TESTDATADIR "@TESTDIRDIR@"
#cmakedefine GETTEXT_PACKAGE "@GETTEXT_PACKAGE@"
#cmakedefine INDICATORDIR "@INDICATORDIR@"
#cmakedefine INDICATORICONDIR "@INDICATORICONDIR@"

#endif // CONFIG_H
