/* panel-indicators.c generated by valac, the Vala compiler
 * generated from panel-indicators.vala, do not modify */

/* -*- Mode: vala; indent-tabs-mode: nil; c-basic-offset: 2; tab-width: 2 -*- */
/*
 * Copyright (C) 2010 Canonical Ltd
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Authored by Neil Jagdish Patel <neil.patel@canonical.com>
 *
 */

#include <glib.h>
#include <glib-object.h>
#include <clutk/clutk.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>
#include <float.h>
#include <math.h>
#include <gio/gio.h>
#include <libindicator/indicator-object.h>
#include <clutter/clutter.h>
#include <libindicator/indicator.h>
#include <libindicator/indicator-service.h>
#include <libindicator/indicator-service-manager.h>
#include <cairo.h>


#define UNITY_PANEL_INDICATORS_TYPE_VIEW (unity_panel_indicators_view_get_type ())
#define UNITY_PANEL_INDICATORS_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), UNITY_PANEL_INDICATORS_TYPE_VIEW, UnityPanelIndicatorsView))
#define UNITY_PANEL_INDICATORS_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), UNITY_PANEL_INDICATORS_TYPE_VIEW, UnityPanelIndicatorsViewClass))
#define UNITY_PANEL_INDICATORS_IS_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), UNITY_PANEL_INDICATORS_TYPE_VIEW))
#define UNITY_PANEL_INDICATORS_IS_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), UNITY_PANEL_INDICATORS_TYPE_VIEW))
#define UNITY_PANEL_INDICATORS_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), UNITY_PANEL_INDICATORS_TYPE_VIEW, UnityPanelIndicatorsViewClass))

typedef struct _UnityPanelIndicatorsView UnityPanelIndicatorsView;
typedef struct _UnityPanelIndicatorsViewClass UnityPanelIndicatorsViewClass;
typedef struct _UnityPanelIndicatorsViewPrivate UnityPanelIndicatorsViewPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

#define UNITY_PANEL_INDICATORS_TYPE_INDICATOR_ITEM (unity_panel_indicators_indicator_item_get_type ())
#define UNITY_PANEL_INDICATORS_INDICATOR_ITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), UNITY_PANEL_INDICATORS_TYPE_INDICATOR_ITEM, UnityPanelIndicatorsIndicatorItem))
#define UNITY_PANEL_INDICATORS_INDICATOR_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), UNITY_PANEL_INDICATORS_TYPE_INDICATOR_ITEM, UnityPanelIndicatorsIndicatorItemClass))
#define UNITY_PANEL_INDICATORS_IS_INDICATOR_ITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), UNITY_PANEL_INDICATORS_TYPE_INDICATOR_ITEM))
#define UNITY_PANEL_INDICATORS_IS_INDICATOR_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), UNITY_PANEL_INDICATORS_TYPE_INDICATOR_ITEM))
#define UNITY_PANEL_INDICATORS_INDICATOR_ITEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), UNITY_PANEL_INDICATORS_TYPE_INDICATOR_ITEM, UnityPanelIndicatorsIndicatorItemClass))

typedef struct _UnityPanelIndicatorsIndicatorItem UnityPanelIndicatorsIndicatorItem;
typedef struct _UnityPanelIndicatorsIndicatorItemClass UnityPanelIndicatorsIndicatorItemClass;
typedef struct _UnityPanelIndicatorsIndicatorItemPrivate UnityPanelIndicatorsIndicatorItemPrivate;

#define UNITY_PANEL_INDICATORS_TYPE_INDICATOR_ENTRY (unity_panel_indicators_indicator_entry_get_type ())
#define UNITY_PANEL_INDICATORS_INDICATOR_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), UNITY_PANEL_INDICATORS_TYPE_INDICATOR_ENTRY, UnityPanelIndicatorsIndicatorEntry))
#define UNITY_PANEL_INDICATORS_INDICATOR_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), UNITY_PANEL_INDICATORS_TYPE_INDICATOR_ENTRY, UnityPanelIndicatorsIndicatorEntryClass))
#define UNITY_PANEL_INDICATORS_IS_INDICATOR_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), UNITY_PANEL_INDICATORS_TYPE_INDICATOR_ENTRY))
#define UNITY_PANEL_INDICATORS_IS_INDICATOR_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), UNITY_PANEL_INDICATORS_TYPE_INDICATOR_ENTRY))
#define UNITY_PANEL_INDICATORS_INDICATOR_ENTRY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), UNITY_PANEL_INDICATORS_TYPE_INDICATOR_ENTRY, UnityPanelIndicatorsIndicatorEntryClass))

typedef struct _UnityPanelIndicatorsIndicatorEntry UnityPanelIndicatorsIndicatorEntry;
typedef struct _UnityPanelIndicatorsIndicatorEntryClass UnityPanelIndicatorsIndicatorEntryClass;
typedef struct _UnityPanelIndicatorsIndicatorEntryPrivate UnityPanelIndicatorsIndicatorEntryPrivate;
#define _cairo_destroy0(var) ((var == NULL) ? NULL : (var = (cairo_destroy (var), NULL)))
#define _cairo_pattern_destroy0(var) ((var == NULL) ? NULL : (var = (cairo_pattern_destroy (var), NULL)))

struct _UnityPanelIndicatorsView {
	CtkBox parent_instance;
	UnityPanelIndicatorsViewPrivate * priv;
};

struct _UnityPanelIndicatorsViewClass {
	CtkBoxClass parent_class;
};

struct _UnityPanelIndicatorsViewPrivate {
	GeeHashMap* indicator_order;
	GtkMenu* popped;
	guint32 click_time;
	float last_found_entry_x;
};

struct _UnityPanelIndicatorsIndicatorItem {
	CtkBox parent_instance;
	UnityPanelIndicatorsIndicatorItemPrivate * priv;
	gint position;
};

struct _UnityPanelIndicatorsIndicatorItemClass {
	CtkBoxClass parent_class;
};

struct _UnityPanelIndicatorsIndicatorItemPrivate {
	IndicatorObject* object;
};

struct _UnityPanelIndicatorsIndicatorEntry {
	CtkBox parent_instance;
	UnityPanelIndicatorsIndicatorEntryPrivate * priv;
};

struct _UnityPanelIndicatorsIndicatorEntryClass {
	CtkBoxClass parent_class;
};

struct _UnityPanelIndicatorsIndicatorEntryPrivate {
	IndicatorObjectEntry* _entry;
	ClutterCairoTexture* bg;
	CtkImage* image;
	CtkText* text;
};


static gpointer unity_panel_indicators_view_parent_class = NULL;
static gpointer unity_panel_indicators_indicator_item_parent_class = NULL;
static gpointer unity_panel_indicators_indicator_entry_parent_class = NULL;

GType unity_panel_indicators_view_get_type (void);
#define UNITY_PANEL_INDICATORS_VIEW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), UNITY_PANEL_INDICATORS_TYPE_VIEW, UnityPanelIndicatorsViewPrivate))
enum  {
	UNITY_PANEL_INDICATORS_VIEW_DUMMY_PROPERTY
};
UnityPanelIndicatorsView* unity_panel_indicators_view_new (void);
UnityPanelIndicatorsView* unity_panel_indicators_view_construct (GType object_type);
static void unity_panel_indicators_view_load_indicator (UnityPanelIndicatorsView* self, const char* filename, const char* leaf);
GType unity_panel_indicators_indicator_item_get_type (void);
gint unity_panel_indicators_view_reorder_icons (UnityPanelIndicatorsIndicatorItem* a, UnityPanelIndicatorsIndicatorItem* b);
static gboolean unity_panel_indicators_view_load_indicators (UnityPanelIndicatorsView* self);
UnityPanelIndicatorsIndicatorItem* unity_panel_indicators_indicator_item_new (void);
UnityPanelIndicatorsIndicatorItem* unity_panel_indicators_indicator_item_construct (GType object_type);
void unity_panel_indicators_indicator_item_set_object (UnityPanelIndicatorsIndicatorItem* self, IndicatorObject* object);
static void unity_panel_indicators_view_on_menu_moved (UnityPanelIndicatorsView* self, UnityPanelIndicatorsIndicatorItem* item, GtkMenuDirectionType type);
static void _unity_panel_indicators_view_on_menu_moved_unity_panel_indicators_indicator_item_menu_moved (UnityPanelIndicatorsIndicatorItem* _sender, GtkMenuDirectionType type, gpointer self);
static void unity_panel_indicators_view_position_menu (UnityPanelIndicatorsView* self, GtkMenu* menu, gint* x, gint* y, gboolean* push_in);
GType unity_panel_indicators_indicator_entry_get_type (void);
static UnityPanelIndicatorsIndicatorEntry* unity_panel_indicators_view_entry_for_event (UnityPanelIndicatorsView* self, float root_x);
GtkMenu* unity_panel_indicators_indicator_entry_get_menu (UnityPanelIndicatorsIndicatorEntry* self);
static void _unity_panel_indicators_view_position_menu_gtk_menu_position_func (GtkMenu* menu, gint* x, gint* y, gboolean* push_in, gpointer self);
void unity_panel_indicators_indicator_entry_menu_shown (UnityPanelIndicatorsIndicatorEntry* self);
void unity_panel_indicators_view_show_entry (UnityPanelIndicatorsView* self, UnityPanelIndicatorsIndicatorEntry* entry);
static gboolean unity_panel_indicators_view_on_button_press_event (UnityPanelIndicatorsView* self, ClutterEvent* e);
static gboolean unity_panel_indicators_view_on_button_release_event (UnityPanelIndicatorsView* self, ClutterEvent* e);
static gboolean unity_panel_indicators_view_on_motion_event (UnityPanelIndicatorsView* self, ClutterEvent* e);
static gboolean _unity_panel_indicators_view_on_button_press_event_clutter_actor_button_press_event (ClutterActor* _sender, ClutterEvent* event, gpointer self);
static gboolean _unity_panel_indicators_view_on_button_release_event_clutter_actor_button_release_event (ClutterActor* _sender, ClutterEvent* event, gpointer self);
static gboolean _unity_panel_indicators_view_on_motion_event_clutter_actor_motion_event (ClutterActor* _sender, ClutterEvent* event, gpointer self);
static gboolean _unity_panel_indicators_view_load_indicators_gsource_func (gpointer self);
static GObject * unity_panel_indicators_view_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void unity_panel_indicators_view_finalize (GObject* obj);
#define UNITY_PANEL_INDICATORS_INDICATOR_ITEM_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), UNITY_PANEL_INDICATORS_TYPE_INDICATOR_ITEM, UnityPanelIndicatorsIndicatorItemPrivate))
enum  {
	UNITY_PANEL_INDICATORS_INDICATOR_ITEM_DUMMY_PROPERTY
};
IndicatorObjectEntry* unity_panel_indicators_indicator_entry_get_entry (UnityPanelIndicatorsIndicatorEntry* self);
static void unity_panel_indicators_indicator_item_remove_entry (UnityPanelIndicatorsIndicatorItem* self, IndicatorObjectEntry* entry);
UnityPanelIndicatorsIndicatorEntry* unity_panel_indicators_indicator_entry_new (IndicatorObjectEntry* entry);
UnityPanelIndicatorsIndicatorEntry* unity_panel_indicators_indicator_entry_construct (GType object_type, IndicatorObjectEntry* entry);
static void unity_panel_indicators_indicator_item_on_menu_moved (UnityPanelIndicatorsIndicatorItem* self, UnityPanelIndicatorsIndicatorEntry* entry, GtkMenuDirectionType type);
static void _unity_panel_indicators_indicator_item_on_menu_moved_unity_panel_indicators_indicator_entry_menu_moved (UnityPanelIndicatorsIndicatorEntry* _sender, GtkMenuDirectionType type, gpointer self);
static void unity_panel_indicators_indicator_item_create_entry (UnityPanelIndicatorsIndicatorItem* self, IndicatorObjectEntry* entry);
static void _unity_panel_indicators_indicator_item_create_entry_indicator_object_entry_added (IndicatorObject* _sender, IndicatorObjectEntry* entry, gpointer self);
static void _unity_panel_indicators_indicator_item_remove_entry_indicator_object_entry_removed (IndicatorObject* _sender, IndicatorObjectEntry* entry, gpointer self);
IndicatorObject* unity_panel_indicators_indicator_item_get_object (UnityPanelIndicatorsIndicatorItem* self);
static GObject * unity_panel_indicators_indicator_item_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void unity_panel_indicators_indicator_item_finalize (GObject* obj);
#define UNITY_PANEL_INDICATORS_INDICATOR_ENTRY_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), UNITY_PANEL_INDICATORS_TYPE_INDICATOR_ENTRY, UnityPanelIndicatorsIndicatorEntryPrivate))
enum  {
	UNITY_PANEL_INDICATORS_INDICATOR_ENTRY_DUMMY_PROPERTY,
	UNITY_PANEL_INDICATORS_INDICATOR_ENTRY_ENTRY,
	UNITY_PANEL_INDICATORS_INDICATOR_ENTRY_MENU
};
void unity_panel_indicators_indicator_entry_menu_key_moved (UnityPanelIndicatorsIndicatorEntry* self, GtkMenuDirectionType type);
static void _unity_panel_indicators_indicator_entry_menu_key_moved_gtk_menu_shell_move_current (GtkMenuShell* _sender, GtkMenuDirectionType direction, gpointer self);
void unity_panel_indicators_indicator_entry_menu_vis_changed (UnityPanelIndicatorsIndicatorEntry* self);
static void _unity_panel_indicators_indicator_entry_menu_vis_changed_g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void unity_panel_indicators_indicator_entry_update_bg (UnityPanelIndicatorsIndicatorEntry* self, gint width, gint height);
static void unity_panel_indicators_indicator_entry_real_allocate (ClutterActor* base, const ClutterActorBox* box, ClutterAllocationFlags flags);
static void unity_panel_indicators_indicator_entry_real_paint (ClutterActor* base);
static void unity_panel_indicators_indicator_entry_real_map (ClutterActor* base);
static void unity_panel_indicators_indicator_entry_real_unmap (ClutterActor* base);
static void unity_panel_indicators_indicator_entry_set_entry (UnityPanelIndicatorsIndicatorEntry* self, IndicatorObjectEntry* value);
static void _lambda4_ (UnityPanelIndicatorsIndicatorEntry* self);
static void __lambda4__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void _lambda5_ (UnityPanelIndicatorsIndicatorEntry* self);
static void __lambda5__gtk_icon_theme_changed (GtkIconTheme* _sender, gpointer self);
static void _lambda6_ (UnityPanelIndicatorsIndicatorEntry* self);
static void __lambda6__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void _lambda7_ (UnityPanelIndicatorsIndicatorEntry* self);
static void __lambda7__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static GObject * unity_panel_indicators_indicator_entry_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void unity_panel_indicators_indicator_entry_finalize (GObject* obj);
static void unity_panel_indicators_indicator_entry_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void unity_panel_indicators_indicator_entry_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static int _vala_strcmp0 (const char * str1, const char * str2);



#line 33 "panel-indicators.vala"
UnityPanelIndicatorsView* unity_panel_indicators_view_construct (GType object_type) {
#line 214 "panel-indicators.c"
	UnityPanelIndicatorsView * self;
#line 35 "panel-indicators.vala"
	self = (UnityPanelIndicatorsView*) g_object_new (object_type, "orientation", CTK_ORIENTATION_HORIZONTAL, "spacing", 0, "homogeneous", FALSE, "reactive", TRUE, NULL);
#line 218 "panel-indicators.c"
	return self;
}


#line 33 "panel-indicators.vala"
UnityPanelIndicatorsView* unity_panel_indicators_view_new (void) {
#line 33 "panel-indicators.vala"
	return unity_panel_indicators_view_construct (UNITY_PANEL_INDICATORS_TYPE_VIEW);
#line 227 "panel-indicators.c"
}


#line 970 "glib-2.0.vapi"
static char* string_slice (const char* self, glong start, glong end) {
#line 233 "panel-indicators.c"
	char* result;
	glong string_length;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	const char* start_string;
#line 970 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 971 "glib-2.0.vapi"
	string_length = g_utf8_strlen (self, -1);
#line 972 "glib-2.0.vapi"
	if (start < 0) {
#line 973 "glib-2.0.vapi"
		start = string_length + start;
#line 247 "panel-indicators.c"
	}
#line 975 "glib-2.0.vapi"
	if (end < 0) {
#line 976 "glib-2.0.vapi"
		end = string_length + end;
#line 253 "panel-indicators.c"
	}
#line 978 "glib-2.0.vapi"
	if (start >= 0) {
#line 978 "glib-2.0.vapi"
		_tmp0_ = start <= string_length;
#line 259 "panel-indicators.c"
	} else {
#line 978 "glib-2.0.vapi"
		_tmp0_ = FALSE;
#line 263 "panel-indicators.c"
	}
#line 978 "glib-2.0.vapi"
	g_return_val_if_fail (_tmp0_, NULL);
#line 979 "glib-2.0.vapi"
	if (end >= 0) {
#line 979 "glib-2.0.vapi"
		_tmp1_ = end <= string_length;
#line 271 "panel-indicators.c"
	} else {
#line 979 "glib-2.0.vapi"
		_tmp1_ = FALSE;
#line 275 "panel-indicators.c"
	}
#line 979 "glib-2.0.vapi"
	g_return_val_if_fail (_tmp1_, NULL);
#line 980 "glib-2.0.vapi"
	g_return_val_if_fail (start <= end, NULL);
#line 981 "glib-2.0.vapi"
	start_string = g_utf8_offset_to_pointer (self, start);
#line 283 "panel-indicators.c"
	result = g_strndup (start_string, ((gchar*) g_utf8_offset_to_pointer (start_string, end - start)) - ((gchar*) start_string));
#line 982 "glib-2.0.vapi"
	return result;
#line 287 "panel-indicators.c"
}


#line 55 "panel-indicators.vala"
static gboolean unity_panel_indicators_view_load_indicators (UnityPanelIndicatorsView* self) {
#line 293 "panel-indicators.c"
	gboolean result;
	GError * _inner_error_;
	GFile* dir;
#line 55 "panel-indicators.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 299 "panel-indicators.c"
	_inner_error_ = NULL;
#line 58 "panel-indicators.vala"
	gee_abstract_map_set ((GeeAbstractMap*) self->priv->indicator_order, "libapplication.so", GINT_TO_POINTER (1));
#line 59 "panel-indicators.vala"
	gee_abstract_map_set ((GeeAbstractMap*) self->priv->indicator_order, "libmessaging.so", GINT_TO_POINTER (2));
#line 60 "panel-indicators.vala"
	gee_abstract_map_set ((GeeAbstractMap*) self->priv->indicator_order, "libdatetime.so", GINT_TO_POINTER (3));
#line 61 "panel-indicators.vala"
	gee_abstract_map_set ((GeeAbstractMap*) self->priv->indicator_order, "libme.so", GINT_TO_POINTER (4));
#line 62 "panel-indicators.vala"
	gee_abstract_map_set ((GeeAbstractMap*) self->priv->indicator_order, "libsession.so", GINT_TO_POINTER (5));
#line 65 "panel-indicators.vala"
	gtk_icon_theme_append_search_path (gtk_icon_theme_get_default (), INDICATORICONSDIR);
#line 68 "panel-indicators.vala"
	dir = g_file_new_for_path (INDICATORDIR);
#line 315 "panel-indicators.c"
	{
		GFileEnumerator* e;
		GFileInfo* file_info;
#line 71 "panel-indicators.vala"
		e = g_file_enumerate_children (dir, G_FILE_ATTRIBUTE_STANDARD_NAME, 0, NULL, &_inner_error_);
#line 321 "panel-indicators.c"
		if (_inner_error_ != NULL) {
			goto __catch6_g_error;
		}
		file_info = NULL;
#line 76 "panel-indicators.vala"
		while (TRUE) {
#line 328 "panel-indicators.c"
			GFileInfo* _tmp0_;
			GFileInfo* _tmp1_;
			char* leaf;
			char* _tmp2_;
			gboolean _tmp3_;
#line 76 "panel-indicators.vala"
			_tmp0_ = g_file_enumerator_next_file (e, NULL, &_inner_error_);
#line 336 "panel-indicators.c"
			if (_inner_error_ != NULL) {
				_g_object_unref0 (e);
				_g_object_unref0 (file_info);
				goto __catch6_g_error;
			}
#line 76 "panel-indicators.vala"
			if (!((file_info = (_tmp1_ = _tmp0_, _g_object_unref0 (file_info), _tmp1_)) != NULL)) {
#line 76 "panel-indicators.vala"
				break;
#line 346 "panel-indicators.c"
			}
#line 78 "panel-indicators.vala"
			leaf = g_strdup (g_file_info_get_name (file_info));
#line 80 "panel-indicators.vala"
			if ((_tmp3_ = _vala_strcmp0 (_tmp2_ = string_slice (leaf, g_utf8_strlen (leaf, -1) - 2, g_utf8_strlen (leaf, -1)), "so") == 0, _g_free0 (_tmp2_), _tmp3_)) {
#line 352 "panel-indicators.c"
				char* _tmp4_;
#line 81 "panel-indicators.vala"
				unity_panel_indicators_view_load_indicator (self, _tmp4_ = g_strconcat (INDICATORDIR, g_file_info_get_name (file_info), NULL), g_file_info_get_name (file_info));
#line 356 "panel-indicators.c"
				_g_free0 (_tmp4_);
			}
			_g_free0 (leaf);
		}
		_g_object_unref0 (e);
		_g_object_unref0 (file_info);
	}
	goto __finally6;
	__catch6_g_error:
	{
		GError * _error_;
		_error_ = _inner_error_;
		_inner_error_ = NULL;
		{
#line 87 "panel-indicators.vala"
			g_print ("Unable to read indicators: %s\n", _error_->message);
#line 373 "panel-indicators.c"
			_g_error_free0 (_error_);
		}
	}
	__finally6:
	if (_inner_error_ != NULL) {
		_g_object_unref0 (dir);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return FALSE;
	}
#line 89 "panel-indicators.vala"
	ctk_box_sort_children ((CtkBox*) self, (GCompareFunc) unity_panel_indicators_view_reorder_icons);
#line 386 "panel-indicators.c"
	result = FALSE;
	_g_object_unref0 (dir);
#line 91 "panel-indicators.vala"
	return result;
#line 391 "panel-indicators.c"
}


#line 94 "panel-indicators.vala"
gint unity_panel_indicators_view_reorder_icons (UnityPanelIndicatorsIndicatorItem* a, UnityPanelIndicatorsIndicatorItem* b) {
#line 397 "panel-indicators.c"
	gint result;
#line 94 "panel-indicators.vala"
	g_return_val_if_fail (a != NULL, 0);
#line 94 "panel-indicators.vala"
	g_return_val_if_fail (b != NULL, 0);
#line 403 "panel-indicators.c"
	result = a->position - b->position;
#line 96 "panel-indicators.vala"
	return result;
#line 407 "panel-indicators.c"
}


#line 257 "panel-indicators.vala"
static void _unity_panel_indicators_view_on_menu_moved_unity_panel_indicators_indicator_item_menu_moved (UnityPanelIndicatorsIndicatorItem* _sender, GtkMenuDirectionType type, gpointer self) {
#line 413 "panel-indicators.c"
	unity_panel_indicators_view_on_menu_moved (self, _sender, type);
}


#line 99 "panel-indicators.vala"
static void unity_panel_indicators_view_load_indicator (UnityPanelIndicatorsView* self, const char* filename, const char* leaf) {
#line 420 "panel-indicators.c"
	IndicatorObject* o;
	IndicatorObject* _tmp0_;
#line 99 "panel-indicators.vala"
	g_return_if_fail (self != NULL);
#line 99 "panel-indicators.vala"
	g_return_if_fail (filename != NULL);
#line 99 "panel-indicators.vala"
	g_return_if_fail (leaf != NULL);
#line 429 "panel-indicators.c"
	o = NULL;
#line 103 "panel-indicators.vala"
	o = (_tmp0_ = indicator_object_new_from_file (filename), _g_object_unref0 (o), _tmp0_);
#line 105 "panel-indicators.vala"
	if (INDICATOR_IS_OBJECT (o)) {
#line 435 "panel-indicators.c"
		UnityPanelIndicatorsIndicatorItem* i;
#line 107 "panel-indicators.vala"
		i = g_object_ref_sink (unity_panel_indicators_indicator_item_new ());
#line 108 "panel-indicators.vala"
		unity_panel_indicators_indicator_item_set_object (i, o);
#line 109 "panel-indicators.vala"
		clutter_container_add_actor ((ClutterContainer*) self, (ClutterActor*) i);
#line 110 "panel-indicators.vala"
		clutter_actor_show ((ClutterActor*) i);
#line 112 "panel-indicators.vala"
		g_signal_connect_object (i, "menu-moved", (GCallback) _unity_panel_indicators_view_on_menu_moved_unity_panel_indicators_indicator_item_menu_moved, self, 0);
#line 114 "panel-indicators.vala"
		i->position = (gint) GPOINTER_TO_INT (gee_abstract_map_get ((GeeAbstractMap*) self->priv->indicator_order, leaf));
#line 449 "panel-indicators.c"
		_g_object_unref0 (i);
	} else {
#line 118 "panel-indicators.vala"
		g_warning ("panel-indicators.vala:118: Unable to load %s\n", filename);
#line 454 "panel-indicators.c"
	}
	_g_object_unref0 (o);
}


#line 122 "panel-indicators.vala"
static void unity_panel_indicators_view_position_menu (UnityPanelIndicatorsView* self, GtkMenu* menu, gint* x, gint* y, gboolean* push_in) {
#line 122 "panel-indicators.vala"
	g_return_if_fail (self != NULL);
#line 122 "panel-indicators.vala"
	g_return_if_fail (menu != NULL);
#line 127 "panel-indicators.vala"
	*y = (gint) clutter_actor_get_height ((ClutterActor*) self);
#line 128 "panel-indicators.vala"
	*x = (gint) self->priv->last_found_entry_x;
#line 470 "panel-indicators.c"
}


#line 131 "panel-indicators.vala"
static UnityPanelIndicatorsIndicatorEntry* unity_panel_indicators_view_entry_for_event (UnityPanelIndicatorsView* self, float root_x) {
#line 476 "panel-indicators.c"
	UnityPanelIndicatorsIndicatorEntry* result;
	UnityPanelIndicatorsIndicatorItem* item;
	UnityPanelIndicatorsIndicatorEntry* entry;
	float x;
	GList* list;
#line 131 "panel-indicators.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 133 "panel-indicators.vala"
	item = NULL;
#line 134 "panel-indicators.vala"
	entry = NULL;
#line 135 "panel-indicators.vala"
	x = root_x - clutter_actor_get_x ((ClutterActor*) self);
#line 138 "panel-indicators.vala"
	list = clutter_container_get_children ((ClutterContainer*) self);
#line 492 "panel-indicators.c"
	{
		gint i;
#line 139 "panel-indicators.vala"
		i = 0;
#line 497 "panel-indicators.c"
		{
			gboolean _tmp0_;
#line 139 "panel-indicators.vala"
			_tmp0_ = TRUE;
#line 139 "panel-indicators.vala"
			while (TRUE) {
#line 504 "panel-indicators.c"
				UnityPanelIndicatorsIndicatorItem* it;
				gboolean _tmp1_ = FALSE;
#line 139 "panel-indicators.vala"
				if (!_tmp0_) {
#line 139 "panel-indicators.vala"
					i++;
#line 511 "panel-indicators.c"
				}
#line 139 "panel-indicators.vala"
				_tmp0_ = FALSE;
#line 139 "panel-indicators.vala"
				if (!(i < g_list_length (list))) {
#line 139 "panel-indicators.vala"
					break;
#line 519 "panel-indicators.c"
				}
#line 141 "panel-indicators.vala"
				it = UNITY_PANEL_INDICATORS_INDICATOR_ITEM (g_list_nth_data (list, (guint) i));
#line 143 "panel-indicators.vala"
				if (clutter_actor_get_x ((ClutterActor*) it) < x) {
#line 143 "panel-indicators.vala"
					_tmp1_ = x < (clutter_actor_get_x ((ClutterActor*) it) + clutter_actor_get_width ((ClutterActor*) it));
#line 527 "panel-indicators.c"
				} else {
#line 143 "panel-indicators.vala"
					_tmp1_ = FALSE;
#line 531 "panel-indicators.c"
				}
#line 143 "panel-indicators.vala"
				if (_tmp1_) {
#line 145 "panel-indicators.vala"
					item = it;
#line 146 "panel-indicators.vala"
					break;
#line 539 "panel-indicators.c"
				}
			}
		}
	}
#line 150 "panel-indicators.vala"
	if (item == NULL) {
#line 546 "panel-indicators.c"
		result = NULL;
#line 151 "panel-indicators.vala"
		return result;
#line 550 "panel-indicators.c"
	}
#line 153 "panel-indicators.vala"
	x = x - clutter_actor_get_x ((ClutterActor*) item);
#line 154 "panel-indicators.vala"
	list = clutter_container_get_children ((ClutterContainer*) item);
#line 556 "panel-indicators.c"
	{
		gint i;
#line 155 "panel-indicators.vala"
		i = 0;
#line 561 "panel-indicators.c"
		{
			gboolean _tmp2_;
#line 155 "panel-indicators.vala"
			_tmp2_ = TRUE;
#line 155 "panel-indicators.vala"
			while (TRUE) {
#line 568 "panel-indicators.c"
				UnityPanelIndicatorsIndicatorEntry* ent;
				gboolean _tmp3_ = FALSE;
#line 155 "panel-indicators.vala"
				if (!_tmp2_) {
#line 155 "panel-indicators.vala"
					i++;
#line 575 "panel-indicators.c"
				}
#line 155 "panel-indicators.vala"
				_tmp2_ = FALSE;
#line 155 "panel-indicators.vala"
				if (!(i < g_list_length (list))) {
#line 155 "panel-indicators.vala"
					break;
#line 583 "panel-indicators.c"
				}
#line 157 "panel-indicators.vala"
				ent = UNITY_PANEL_INDICATORS_INDICATOR_ENTRY (g_list_nth_data (list, (guint) i));
#line 159 "panel-indicators.vala"
				if (clutter_actor_get_x ((ClutterActor*) ent) < x) {
#line 159 "panel-indicators.vala"
					_tmp3_ = x < (clutter_actor_get_x ((ClutterActor*) ent) + clutter_actor_get_width ((ClutterActor*) ent));
#line 591 "panel-indicators.c"
				} else {
#line 159 "panel-indicators.vala"
					_tmp3_ = FALSE;
#line 595 "panel-indicators.c"
				}
#line 159 "panel-indicators.vala"
				if (_tmp3_) {
#line 161 "panel-indicators.vala"
					self->priv->last_found_entry_x = (clutter_actor_get_x ((ClutterActor*) ent) + clutter_actor_get_x ((ClutterActor*) item)) + clutter_actor_get_x ((ClutterActor*) self);
#line 162 "panel-indicators.vala"
					entry = ent;
#line 603 "panel-indicators.c"
				}
			}
		}
	}
	result = entry;
#line 166 "panel-indicators.vala"
	return result;
#line 611 "panel-indicators.c"
}


#line 122 "panel-indicators.vala"
static void _unity_panel_indicators_view_position_menu_gtk_menu_position_func (GtkMenu* menu, gint* x, gint* y, gboolean* push_in, gpointer self) {
#line 617 "panel-indicators.c"
	unity_panel_indicators_view_position_menu (self, menu, x, y, push_in);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


#line 169 "panel-indicators.vala"
void unity_panel_indicators_view_show_entry (UnityPanelIndicatorsView* self, UnityPanelIndicatorsIndicatorEntry* entry) {
#line 629 "panel-indicators.c"
	gboolean _tmp0_ = FALSE;
	GtkMenu* _tmp2_;
#line 169 "panel-indicators.vala"
	g_return_if_fail (self != NULL);
#line 169 "panel-indicators.vala"
	g_return_if_fail (entry != NULL);
#line 171 "panel-indicators.vala"
	if (GTK_IS_MENU (self->priv->popped)) {
#line 172 "panel-indicators.vala"
		_tmp0_ = (GTK_WIDGET_FLAGS ((GtkWidget*) self->priv->popped) & GTK_VISIBLE) != 0;
#line 640 "panel-indicators.c"
	} else {
#line 171 "panel-indicators.vala"
		_tmp0_ = FALSE;
#line 644 "panel-indicators.c"
	}
#line 171 "panel-indicators.vala"
	if (_tmp0_) {
#line 648 "panel-indicators.c"
		GtkMenu* _tmp1_;
#line 174 "panel-indicators.vala"
		gtk_menu_popdown (self->priv->popped);
#line 175 "panel-indicators.vala"
		self->priv->popped = (_tmp1_ = NULL, _g_object_unref0 (self->priv->popped), _tmp1_);
#line 654 "panel-indicators.c"
	}
#line 178 "panel-indicators.vala"
	self->priv->last_found_entry_x = (clutter_actor_get_x ((ClutterActor*) entry) + clutter_actor_get_x (clutter_actor_get_parent ((ClutterActor*) entry))) + clutter_actor_get_x ((ClutterActor*) self);
#line 180 "panel-indicators.vala"
	gtk_menu_popup (unity_panel_indicators_indicator_entry_get_menu (entry), NULL, NULL, _unity_panel_indicators_view_position_menu_gtk_menu_position_func, self, (guint) 1, clutter_get_current_event_time ());
#line 185 "panel-indicators.vala"
	self->priv->click_time = clutter_get_current_event_time ();
#line 186 "panel-indicators.vala"
	self->priv->popped = (_tmp2_ = _g_object_ref0 (unity_panel_indicators_indicator_entry_get_menu (entry)), _g_object_unref0 (self->priv->popped), _tmp2_);
#line 187 "panel-indicators.vala"
	unity_panel_indicators_indicator_entry_menu_shown (entry);
#line 666 "panel-indicators.c"
}


#line 190 "panel-indicators.vala"
static gboolean unity_panel_indicators_view_on_button_press_event (UnityPanelIndicatorsView* self, ClutterEvent* e) {
#line 672 "panel-indicators.c"
	gboolean result;
	gboolean _tmp0_ = FALSE;
	UnityPanelIndicatorsIndicatorEntry* entry;
#line 190 "panel-indicators.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 192 "panel-indicators.vala"
	if (GTK_IS_MENU (self->priv->popped)) {
#line 193 "panel-indicators.vala"
		_tmp0_ = (GTK_WIDGET_FLAGS ((GtkWidget*) self->priv->popped) & GTK_VISIBLE) != 0;
#line 682 "panel-indicators.c"
	} else {
#line 192 "panel-indicators.vala"
		_tmp0_ = FALSE;
#line 686 "panel-indicators.c"
	}
#line 192 "panel-indicators.vala"
	if (_tmp0_) {
#line 690 "panel-indicators.c"
		GtkMenu* _tmp1_;
#line 195 "panel-indicators.vala"
		gtk_menu_popdown (self->priv->popped);
#line 196 "panel-indicators.vala"
		self->priv->popped = (_tmp1_ = NULL, _g_object_unref0 (self->priv->popped), _tmp1_);
#line 696 "panel-indicators.c"
	}
#line 199 "panel-indicators.vala"
	entry = unity_panel_indicators_view_entry_for_event (self, (*e).button.x);
#line 200 "panel-indicators.vala"
	if (UNITY_PANEL_INDICATORS_IS_INDICATOR_ENTRY (entry)) {
#line 702 "panel-indicators.c"
		GtkMenu* _tmp2_;
#line 202 "panel-indicators.vala"
		gtk_menu_popup (unity_panel_indicators_indicator_entry_get_menu (entry), NULL, NULL, _unity_panel_indicators_view_position_menu_gtk_menu_position_func, self, (guint) (*e).button.button, (*e).button.time);
#line 207 "panel-indicators.vala"
		self->priv->click_time = (*e).button.time;
#line 208 "panel-indicators.vala"
		self->priv->popped = (_tmp2_ = _g_object_ref0 (unity_panel_indicators_indicator_entry_get_menu (entry)), _g_object_unref0 (self->priv->popped), _tmp2_);
#line 209 "panel-indicators.vala"
		unity_panel_indicators_indicator_entry_menu_shown (entry);
#line 712 "panel-indicators.c"
	}
	result = TRUE;
#line 211 "panel-indicators.vala"
	return result;
#line 717 "panel-indicators.c"
}


#line 214 "panel-indicators.vala"
static gboolean unity_panel_indicators_view_on_button_release_event (UnityPanelIndicatorsView* self, ClutterEvent* e) {
#line 723 "panel-indicators.c"
	gboolean result;
	gboolean _tmp0_ = FALSE;
#line 214 "panel-indicators.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 216 "panel-indicators.vala"
	if (((*e).button.time - self->priv->click_time) < 300) {
#line 730 "panel-indicators.c"
		result = TRUE;
#line 217 "panel-indicators.vala"
		return result;
#line 734 "panel-indicators.c"
	}
#line 219 "panel-indicators.vala"
	if (GTK_IS_MENU (self->priv->popped)) {
#line 220 "panel-indicators.vala"
		_tmp0_ = (GTK_WIDGET_FLAGS ((GtkWidget*) self->priv->popped) & GTK_VISIBLE) != 0;
#line 740 "panel-indicators.c"
	} else {
#line 219 "panel-indicators.vala"
		_tmp0_ = FALSE;
#line 744 "panel-indicators.c"
	}
#line 219 "panel-indicators.vala"
	if (_tmp0_) {
#line 748 "panel-indicators.c"
		GtkMenu* _tmp1_;
#line 222 "panel-indicators.vala"
		gtk_menu_popdown (self->priv->popped);
#line 223 "panel-indicators.vala"
		self->priv->popped = (_tmp1_ = NULL, _g_object_unref0 (self->priv->popped), _tmp1_);
#line 754 "panel-indicators.c"
	}
	result = TRUE;
#line 226 "panel-indicators.vala"
	return result;
#line 759 "panel-indicators.c"
}


#line 229 "panel-indicators.vala"
static gboolean unity_panel_indicators_view_on_motion_event (UnityPanelIndicatorsView* self, ClutterEvent* e) {
#line 765 "panel-indicators.c"
	gboolean result;
	gboolean _tmp0_ = FALSE;
#line 229 "panel-indicators.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 231 "panel-indicators.vala"
	if (GTK_IS_MENU (self->priv->popped)) {
#line 232 "panel-indicators.vala"
		_tmp0_ = (GTK_WIDGET_FLAGS ((GtkWidget*) self->priv->popped) & GTK_VISIBLE) != 0;
#line 774 "panel-indicators.c"
	} else {
#line 231 "panel-indicators.vala"
		_tmp0_ = FALSE;
#line 778 "panel-indicators.c"
	}
#line 231 "panel-indicators.vala"
	if (_tmp0_) {
#line 782 "panel-indicators.c"
		UnityPanelIndicatorsIndicatorEntry* entry;
		entry = NULL;
#line 236 "panel-indicators.vala"
		entry = unity_panel_indicators_view_entry_for_event (self, (*e).motion.x);
#line 238 "panel-indicators.vala"
		if (entry == NULL) {
#line 789 "panel-indicators.c"
			result = TRUE;
#line 239 "panel-indicators.vala"
			return result;
#line 793 "panel-indicators.c"
		}
#line 241 "panel-indicators.vala"
		if (unity_panel_indicators_indicator_entry_get_menu (entry) != self->priv->popped) {
#line 797 "panel-indicators.c"
			GtkMenu* _tmp1_;
#line 243 "panel-indicators.vala"
			gtk_menu_popdown (self->priv->popped);
#line 244 "panel-indicators.vala"
			self->priv->popped = (_tmp1_ = _g_object_ref0 (unity_panel_indicators_indicator_entry_get_menu (entry)), _g_object_unref0 (self->priv->popped), _tmp1_);
#line 245 "panel-indicators.vala"
			gtk_menu_popup (self->priv->popped, NULL, NULL, _unity_panel_indicators_view_position_menu_gtk_menu_position_func, self, (guint) (*e).button.button, (*e).button.time);
#line 250 "panel-indicators.vala"
			unity_panel_indicators_indicator_entry_menu_shown (entry);
#line 807 "panel-indicators.c"
		}
	}
	result = TRUE;
#line 254 "panel-indicators.vala"
	return result;
#line 813 "panel-indicators.c"
}


#line 257 "panel-indicators.vala"
static void unity_panel_indicators_view_on_menu_moved (UnityPanelIndicatorsView* self, UnityPanelIndicatorsIndicatorItem* item, GtkMenuDirectionType type) {
#line 819 "panel-indicators.c"
	GList* list;
	gint pos;
	gpointer _tmp0_;
	UnityPanelIndicatorsIndicatorItem* new_item;
	GList* l;
	gint _tmp1_ = 0;
	gint p;
	gpointer _tmp2_;
	UnityPanelIndicatorsIndicatorEntry* new_entry;
#line 257 "panel-indicators.vala"
	g_return_if_fail (self != NULL);
#line 257 "panel-indicators.vala"
	g_return_if_fail (item != NULL);
#line 260 "panel-indicators.vala"
	list = clutter_container_get_children ((ClutterContainer*) self);
#line 262 "panel-indicators.vala"
	pos = g_list_index (list, item);
#line 264 "panel-indicators.vala"
	if (pos == (-1)) {
#line 265 "panel-indicators.vala"
		return;
#line 841 "panel-indicators.c"
	}
#line 268 "panel-indicators.vala"
	if (type == GTK_MENU_DIR_PARENT) {
#line 270 "panel-indicators.vala"
		if (pos == 0) {
#line 271 "panel-indicators.vala"
			return;
#line 849 "panel-indicators.c"
		}
#line 272 "panel-indicators.vala"
		pos = pos - 1;
#line 853 "panel-indicators.c"
	} else {
#line 274 "panel-indicators.vala"
		if (type == GTK_MENU_DIR_CHILD) {
#line 276 "panel-indicators.vala"
			if (pos == (g_list_length (list) - 1)) {
#line 277 "panel-indicators.vala"
				return;
#line 861 "panel-indicators.c"
			}
#line 278 "panel-indicators.vala"
			pos = pos + 1;
#line 865 "panel-indicators.c"
		}
	}
#line 282 "panel-indicators.vala"
	new_item = _g_object_ref0 ((_tmp0_ = g_list_nth_data (list, (guint) pos), UNITY_PANEL_INDICATORS_IS_INDICATOR_ITEM (_tmp0_) ? ((UnityPanelIndicatorsIndicatorItem*) _tmp0_) : NULL));
#line 285 "panel-indicators.vala"
	l = clutter_container_get_children ((ClutterContainer*) new_item);
#line 286 "panel-indicators.vala"
	if (type == GTK_MENU_DIR_PARENT) {
#line 286 "panel-indicators.vala"
		_tmp1_ = ((gint) g_list_length (l)) - 1;
#line 876 "panel-indicators.c"
	} else {
#line 286 "panel-indicators.vala"
		_tmp1_ = 0;
#line 880 "panel-indicators.c"
	}
#line 286 "panel-indicators.vala"
	p = _tmp1_;
#line 287 "panel-indicators.vala"
	new_entry = _g_object_ref0 ((_tmp2_ = g_list_nth_data (l, (guint) p), UNITY_PANEL_INDICATORS_IS_INDICATOR_ENTRY (_tmp2_) ? ((UnityPanelIndicatorsIndicatorEntry*) _tmp2_) : NULL));
#line 289 "panel-indicators.vala"
	if (UNITY_PANEL_INDICATORS_IS_INDICATOR_ENTRY (new_entry)) {
#line 290 "panel-indicators.vala"
		unity_panel_indicators_view_show_entry (self, new_entry);
#line 890 "panel-indicators.c"
	}
	_g_object_unref0 (new_item);
	_g_object_unref0 (new_entry);
}


#line 190 "panel-indicators.vala"
static gboolean _unity_panel_indicators_view_on_button_press_event_clutter_actor_button_press_event (ClutterActor* _sender, ClutterEvent* event, gpointer self) {
#line 899 "panel-indicators.c"
	return unity_panel_indicators_view_on_button_press_event (self, event);
}


#line 214 "panel-indicators.vala"
static gboolean _unity_panel_indicators_view_on_button_release_event_clutter_actor_button_release_event (ClutterActor* _sender, ClutterEvent* event, gpointer self) {
#line 906 "panel-indicators.c"
	return unity_panel_indicators_view_on_button_release_event (self, event);
}


#line 229 "panel-indicators.vala"
static gboolean _unity_panel_indicators_view_on_motion_event_clutter_actor_motion_event (ClutterActor* _sender, ClutterEvent* event, gpointer self) {
#line 913 "panel-indicators.c"
	return unity_panel_indicators_view_on_motion_event (self, event);
}


#line 55 "panel-indicators.vala"
static gboolean _unity_panel_indicators_view_load_indicators_gsource_func (gpointer self) {
#line 920 "panel-indicators.c"
	return unity_panel_indicators_view_load_indicators (self);
}


static GObject * unity_panel_indicators_view_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	UnityPanelIndicatorsView * self;
	parent_class = G_OBJECT_CLASS (unity_panel_indicators_view_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = UNITY_PANEL_INDICATORS_VIEW (obj);
	{
		GeeHashMap* _tmp0_;
#line 43 "panel-indicators.vala"
		self->priv->indicator_order = (_tmp0_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, G_TYPE_INT, NULL, NULL, NULL, NULL, NULL), _g_object_unref0 (self->priv->indicator_order), _tmp0_);
#line 45 "panel-indicators.vala"
		g_signal_connect_object ((ClutterActor*) self, "button-press-event", (GCallback) _unity_panel_indicators_view_on_button_press_event_clutter_actor_button_press_event, self, 0);
#line 46 "panel-indicators.vala"
		g_signal_connect_object ((ClutterActor*) self, "button-release-event", (GCallback) _unity_panel_indicators_view_on_button_release_event_clutter_actor_button_release_event, self, 0);
#line 47 "panel-indicators.vala"
		g_signal_connect_object ((ClutterActor*) self, "motion-event", (GCallback) _unity_panel_indicators_view_on_motion_event_clutter_actor_motion_event, self, 0);
#line 49 "panel-indicators.vala"
		if (g_getenv ("UNITY_DISABLE_IDLES") != NULL) {
#line 50 "panel-indicators.vala"
			unity_panel_indicators_view_load_indicators (self);
#line 946 "panel-indicators.c"
		} else {
#line 52 "panel-indicators.vala"
			g_idle_add_full (G_PRIORITY_DEFAULT_IDLE, _unity_panel_indicators_view_load_indicators_gsource_func, g_object_ref (self), g_object_unref);
#line 950 "panel-indicators.c"
		}
	}
	return obj;
}


static void unity_panel_indicators_view_class_init (UnityPanelIndicatorsViewClass * klass) {
	unity_panel_indicators_view_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (UnityPanelIndicatorsViewPrivate));
	G_OBJECT_CLASS (klass)->constructor = unity_panel_indicators_view_constructor;
	G_OBJECT_CLASS (klass)->finalize = unity_panel_indicators_view_finalize;
}


static void unity_panel_indicators_view_instance_init (UnityPanelIndicatorsView * self) {
	self->priv = UNITY_PANEL_INDICATORS_VIEW_GET_PRIVATE (self);
	self->priv->last_found_entry_x = 0.0f;
}


static void unity_panel_indicators_view_finalize (GObject* obj) {
	UnityPanelIndicatorsView * self;
	self = UNITY_PANEL_INDICATORS_VIEW (obj);
	_g_object_unref0 (self->priv->indicator_order);
	_g_object_unref0 (self->priv->popped);
	G_OBJECT_CLASS (unity_panel_indicators_view_parent_class)->finalize (obj);
}


GType unity_panel_indicators_view_get_type (void) {
	static GType unity_panel_indicators_view_type_id = 0;
	if (unity_panel_indicators_view_type_id == 0) {
		static const GTypeInfo g_define_type_info = { sizeof (UnityPanelIndicatorsViewClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) unity_panel_indicators_view_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (UnityPanelIndicatorsView), 0, (GInstanceInitFunc) unity_panel_indicators_view_instance_init, NULL };
		unity_panel_indicators_view_type_id = g_type_register_static (CTK_TYPE_BOX, "UnityPanelIndicatorsView", &g_define_type_info, 0);
	}
	return unity_panel_indicators_view_type_id;
}


#line 304 "panel-indicators.vala"
UnityPanelIndicatorsIndicatorItem* unity_panel_indicators_indicator_item_construct (GType object_type) {
#line 992 "panel-indicators.c"
	UnityPanelIndicatorsIndicatorItem * self;
#line 306 "panel-indicators.vala"
	self = (UnityPanelIndicatorsIndicatorItem*) g_object_new (object_type, "orientation", CTK_ORIENTATION_HORIZONTAL, "spacing", 0, "homogeneous", FALSE, NULL);
#line 996 "panel-indicators.c"
	return self;
}


#line 304 "panel-indicators.vala"
UnityPanelIndicatorsIndicatorItem* unity_panel_indicators_indicator_item_new (void) {
#line 304 "panel-indicators.vala"
	return unity_panel_indicators_indicator_item_construct (UNITY_PANEL_INDICATORS_TYPE_INDICATOR_ITEM);
#line 1005 "panel-indicators.c"
}


#line 315 "panel-indicators.vala"
static void unity_panel_indicators_indicator_item_remove_entry (UnityPanelIndicatorsIndicatorItem* self, IndicatorObjectEntry* entry) {
#line 1011 "panel-indicators.c"
	GList* list;
#line 315 "panel-indicators.vala"
	g_return_if_fail (self != NULL);
#line 315 "panel-indicators.vala"
	g_return_if_fail (entry != NULL);
#line 317 "panel-indicators.vala"
	list = clutter_container_get_children ((ClutterContainer*) self);
#line 1019 "panel-indicators.c"
	{
		gint i;
#line 319 "panel-indicators.vala"
		i = 0;
#line 1024 "panel-indicators.c"
		{
			gboolean _tmp0_;
#line 319 "panel-indicators.vala"
			_tmp0_ = TRUE;
#line 319 "panel-indicators.vala"
			while (TRUE) {
#line 1031 "panel-indicators.c"
				UnityPanelIndicatorsIndicatorEntry* e;
				UnityPanelIndicatorsIndicatorEntry* _tmp1_;
#line 319 "panel-indicators.vala"
				if (!_tmp0_) {
#line 319 "panel-indicators.vala"
					i++;
#line 1038 "panel-indicators.c"
				}
#line 319 "panel-indicators.vala"
				_tmp0_ = FALSE;
#line 319 "panel-indicators.vala"
				if (!(i < g_list_length (list))) {
#line 319 "panel-indicators.vala"
					break;
#line 1046 "panel-indicators.c"
				}
				e = NULL;
#line 323 "panel-indicators.vala"
				e = (_tmp1_ = _g_object_ref0 (UNITY_PANEL_INDICATORS_INDICATOR_ENTRY (g_list_nth_data (list, (guint) i))), _g_object_unref0 (e), _tmp1_);
#line 325 "panel-indicators.vala"
				if (unity_panel_indicators_indicator_entry_get_entry (e) == entry) {
#line 327 "panel-indicators.vala"
					clutter_container_remove_actor ((ClutterContainer*) self, (ClutterActor*) e);
#line 1055 "panel-indicators.c"
				}
				_g_object_unref0 (e);
			}
		}
	}
}


#line 341 "panel-indicators.vala"
static void _unity_panel_indicators_indicator_item_on_menu_moved_unity_panel_indicators_indicator_entry_menu_moved (UnityPanelIndicatorsIndicatorEntry* _sender, GtkMenuDirectionType type, gpointer self) {
#line 1066 "panel-indicators.c"
	unity_panel_indicators_indicator_item_on_menu_moved (self, _sender, type);
}


#line 332 "panel-indicators.vala"
static void unity_panel_indicators_indicator_item_create_entry (UnityPanelIndicatorsIndicatorItem* self, IndicatorObjectEntry* entry) {
#line 1073 "panel-indicators.c"
	UnityPanelIndicatorsIndicatorEntry* e;
#line 332 "panel-indicators.vala"
	g_return_if_fail (self != NULL);
#line 332 "panel-indicators.vala"
	g_return_if_fail (entry != NULL);
#line 334 "panel-indicators.vala"
	e = g_object_ref_sink (unity_panel_indicators_indicator_entry_new (entry));
#line 335 "panel-indicators.vala"
	clutter_container_add_actor ((ClutterContainer*) self, (ClutterActor*) e);
#line 336 "panel-indicators.vala"
	clutter_actor_show ((ClutterActor*) self);
#line 338 "panel-indicators.vala"
	g_signal_connect_object (e, "menu-moved", (GCallback) _unity_panel_indicators_indicator_item_on_menu_moved_unity_panel_indicators_indicator_entry_menu_moved, self, 0);
#line 1087 "panel-indicators.c"
	_g_object_unref0 (e);
}


#line 341 "panel-indicators.vala"
static void unity_panel_indicators_indicator_item_on_menu_moved (UnityPanelIndicatorsIndicatorItem* self, UnityPanelIndicatorsIndicatorEntry* entry, GtkMenuDirectionType type) {
#line 1094 "panel-indicators.c"
	GList* list;
	gint pos;
	gpointer _tmp0_;
	UnityPanelIndicatorsIndicatorEntry* new_entry;
	ClutterActor* _tmp1_;
	UnityPanelIndicatorsView* parent;
#line 341 "panel-indicators.vala"
	g_return_if_fail (self != NULL);
#line 341 "panel-indicators.vala"
	g_return_if_fail (entry != NULL);
#line 344 "panel-indicators.vala"
	list = clutter_container_get_children ((ClutterContainer*) self);
#line 346 "panel-indicators.vala"
	pos = g_list_index (list, entry);
#line 348 "panel-indicators.vala"
	if (pos == (-1)) {
#line 350 "panel-indicators.vala"
		g_signal_emit_by_name (self, "menu-moved", type);
#line 351 "panel-indicators.vala"
		return;
#line 1115 "panel-indicators.c"
	}
#line 355 "panel-indicators.vala"
	if (type == GTK_MENU_DIR_PARENT) {
#line 357 "panel-indicators.vala"
		if (pos == 0) {
#line 359 "panel-indicators.vala"
			g_signal_emit_by_name (self, "menu-moved", type);
#line 360 "panel-indicators.vala"
			return;
#line 1125 "panel-indicators.c"
		}
#line 362 "panel-indicators.vala"
		pos = pos - 1;
#line 1129 "panel-indicators.c"
	} else {
#line 364 "panel-indicators.vala"
		if (type == GTK_MENU_DIR_CHILD) {
#line 366 "panel-indicators.vala"
			if (pos == (g_list_length (list) - 1)) {
#line 368 "panel-indicators.vala"
				g_signal_emit_by_name (self, "menu-moved", type);
#line 369 "panel-indicators.vala"
				return;
#line 1139 "panel-indicators.c"
			}
#line 371 "panel-indicators.vala"
			pos = pos + 1;
#line 1143 "panel-indicators.c"
		}
	}
#line 374 "panel-indicators.vala"
	new_entry = _g_object_ref0 ((_tmp0_ = g_list_nth_data (list, (guint) pos), UNITY_PANEL_INDICATORS_IS_INDICATOR_ENTRY (_tmp0_) ? ((UnityPanelIndicatorsIndicatorEntry*) _tmp0_) : NULL));
#line 376 "panel-indicators.vala"
	parent = _g_object_ref0 ((_tmp1_ = clutter_actor_get_parent ((ClutterActor*) self), UNITY_PANEL_INDICATORS_IS_VIEW (_tmp1_) ? ((UnityPanelIndicatorsView*) _tmp1_) : NULL));
#line 377 "panel-indicators.vala"
	unity_panel_indicators_view_show_entry (parent, new_entry);
#line 1152 "panel-indicators.c"
	_g_object_unref0 (new_entry);
	_g_object_unref0 (parent);
}


#line 332 "panel-indicators.vala"
static void _unity_panel_indicators_indicator_item_create_entry_indicator_object_entry_added (IndicatorObject* _sender, IndicatorObjectEntry* entry, gpointer self) {
#line 1160 "panel-indicators.c"
	unity_panel_indicators_indicator_item_create_entry (self, entry);
}


#line 315 "panel-indicators.vala"
static void _unity_panel_indicators_indicator_item_remove_entry_indicator_object_entry_removed (IndicatorObject* _sender, IndicatorObjectEntry* entry, gpointer self) {
#line 1167 "panel-indicators.c"
	unity_panel_indicators_indicator_item_remove_entry (self, entry);
}


#line 380 "panel-indicators.vala"
void unity_panel_indicators_indicator_item_set_object (UnityPanelIndicatorsIndicatorItem* self, IndicatorObject* object) {
#line 1174 "panel-indicators.c"
	IndicatorObject* _tmp0_;
	GList* list;
#line 380 "panel-indicators.vala"
	g_return_if_fail (self != NULL);
#line 380 "panel-indicators.vala"
	g_return_if_fail (object != NULL);
#line 382 "panel-indicators.vala"
	self->priv->object = (_tmp0_ = _g_object_ref0 (object), _g_object_unref0 (self->priv->object), _tmp0_);
#line 384 "panel-indicators.vala"
	g_signal_connect_object (object, "entry-added", (GCallback) _unity_panel_indicators_indicator_item_create_entry_indicator_object_entry_added, self, 0);
#line 385 "panel-indicators.vala"
	g_signal_connect_object (object, "entry-removed", (GCallback) _unity_panel_indicators_indicator_item_remove_entry_indicator_object_entry_removed, self, 0);
#line 387 "panel-indicators.vala"
	list = indicator_object_get_entries (object);
#line 1189 "panel-indicators.c"
	{
		gint i;
#line 389 "panel-indicators.vala"
		i = 0;
#line 1194 "panel-indicators.c"
		{
			gboolean _tmp1_;
#line 389 "panel-indicators.vala"
			_tmp1_ = TRUE;
#line 389 "panel-indicators.vala"
			while (TRUE) {
#line 1201 "panel-indicators.c"
				IndicatorObjectEntry* entry;
#line 389 "panel-indicators.vala"
				if (!_tmp1_) {
#line 389 "panel-indicators.vala"
					i++;
#line 1207 "panel-indicators.c"
				}
#line 389 "panel-indicators.vala"
				_tmp1_ = FALSE;
#line 389 "panel-indicators.vala"
				if (!(i < g_list_length (list))) {
#line 389 "panel-indicators.vala"
					break;
#line 1215 "panel-indicators.c"
				}
				entry = NULL;
#line 393 "panel-indicators.vala"
				entry = (IndicatorObjectEntry*) g_list_nth_data (list, (guint) i);
#line 395 "panel-indicators.vala"
				unity_panel_indicators_indicator_item_create_entry (self, entry);
#line 1222 "panel-indicators.c"
			}
		}
	}
}


#line 399 "panel-indicators.vala"
IndicatorObject* unity_panel_indicators_indicator_item_get_object (UnityPanelIndicatorsIndicatorItem* self) {
#line 1231 "panel-indicators.c"
	IndicatorObject* result;
#line 399 "panel-indicators.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 1235 "panel-indicators.c"
	result = _g_object_ref0 (self->priv->object);
#line 401 "panel-indicators.vala"
	return result;
#line 1239 "panel-indicators.c"
}


static GObject * unity_panel_indicators_indicator_item_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	UnityPanelIndicatorsIndicatorItem * self;
	parent_class = G_OBJECT_CLASS (unity_panel_indicators_indicator_item_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = UNITY_PANEL_INDICATORS_INDICATOR_ITEM (obj);
	{
	}
	return obj;
}


static void unity_panel_indicators_indicator_item_class_init (UnityPanelIndicatorsIndicatorItemClass * klass) {
	unity_panel_indicators_indicator_item_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (UnityPanelIndicatorsIndicatorItemPrivate));
	G_OBJECT_CLASS (klass)->constructor = unity_panel_indicators_indicator_item_constructor;
	G_OBJECT_CLASS (klass)->finalize = unity_panel_indicators_indicator_item_finalize;
	g_signal_new ("menu_moved", UNITY_PANEL_INDICATORS_TYPE_INDICATOR_ITEM, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__ENUM, G_TYPE_NONE, 1, GTK_TYPE_MENU_DIRECTION_TYPE);
}


static void unity_panel_indicators_indicator_item_instance_init (UnityPanelIndicatorsIndicatorItem * self) {
	self->priv = UNITY_PANEL_INDICATORS_INDICATOR_ITEM_GET_PRIVATE (self);
}


static void unity_panel_indicators_indicator_item_finalize (GObject* obj) {
	UnityPanelIndicatorsIndicatorItem * self;
	self = UNITY_PANEL_INDICATORS_INDICATOR_ITEM (obj);
	_g_object_unref0 (self->priv->object);
	G_OBJECT_CLASS (unity_panel_indicators_indicator_item_parent_class)->finalize (obj);
}


GType unity_panel_indicators_indicator_item_get_type (void) {
	static GType unity_panel_indicators_indicator_item_type_id = 0;
	if (unity_panel_indicators_indicator_item_type_id == 0) {
		static const GTypeInfo g_define_type_info = { sizeof (UnityPanelIndicatorsIndicatorItemClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) unity_panel_indicators_indicator_item_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (UnityPanelIndicatorsIndicatorItem), 0, (GInstanceInitFunc) unity_panel_indicators_indicator_item_instance_init, NULL };
		unity_panel_indicators_indicator_item_type_id = g_type_register_static (CTK_TYPE_BOX, "UnityPanelIndicatorsIndicatorItem", &g_define_type_info, 0);
	}
	return unity_panel_indicators_indicator_item_type_id;
}


#line 418 "panel-indicators.vala"
UnityPanelIndicatorsIndicatorEntry* unity_panel_indicators_indicator_entry_construct (GType object_type, IndicatorObjectEntry* entry) {
#line 1290 "panel-indicators.c"
	UnityPanelIndicatorsIndicatorEntry * self;
#line 418 "panel-indicators.vala"
	g_return_val_if_fail (entry != NULL, NULL);
#line 420 "panel-indicators.vala"
	self = (UnityPanelIndicatorsIndicatorEntry*) g_object_new (object_type, "entry", entry, "orientation", CTK_ORIENTATION_HORIZONTAL, "spacing", 4, "reactive", FALSE, NULL);
#line 1296 "panel-indicators.c"
	return self;
}


#line 418 "panel-indicators.vala"
UnityPanelIndicatorsIndicatorEntry* unity_panel_indicators_indicator_entry_new (IndicatorObjectEntry* entry) {
#line 418 "panel-indicators.vala"
	return unity_panel_indicators_indicator_entry_construct (UNITY_PANEL_INDICATORS_TYPE_INDICATOR_ENTRY, entry);
#line 1305 "panel-indicators.c"
}


#line 509 "panel-indicators.vala"
static void _unity_panel_indicators_indicator_entry_menu_key_moved_gtk_menu_shell_move_current (GtkMenuShell* _sender, GtkMenuDirectionType direction, gpointer self) {
#line 1311 "panel-indicators.c"
	unity_panel_indicators_indicator_entry_menu_key_moved (self, direction);
}


#line 495 "panel-indicators.vala"
static void _unity_panel_indicators_indicator_entry_menu_vis_changed_g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
#line 1318 "panel-indicators.c"
	unity_panel_indicators_indicator_entry_menu_vis_changed (self);
}


#line 484 "panel-indicators.vala"
void unity_panel_indicators_indicator_entry_menu_shown (UnityPanelIndicatorsIndicatorEntry* self) {
#line 484 "panel-indicators.vala"
	g_return_if_fail (self != NULL);
#line 486 "panel-indicators.vala"
	if (GTK_IS_MENU (self->priv->_entry->menu)) {
#line 488 "panel-indicators.vala"
		g_signal_connect_object ((GtkMenuShell*) self->priv->_entry->menu, "move-current", (GCallback) _unity_panel_indicators_indicator_entry_menu_key_moved_gtk_menu_shell_move_current, self, 0);
#line 489 "panel-indicators.vala"
		g_signal_connect_object ((GObject*) self->priv->_entry->menu, "notify::visible", (GCallback) _unity_panel_indicators_indicator_entry_menu_vis_changed_g_object_notify, self, 0);
#line 490 "panel-indicators.vala"
		clutter_actor_animate ((ClutterActor*) self->priv->bg, (gulong) CLUTTER_EASE_OUT_QUAD, (guint) 200, "opacity", 255, NULL);
#line 1335 "panel-indicators.c"
	}
}


#line 495 "panel-indicators.vala"
void unity_panel_indicators_indicator_entry_menu_vis_changed (UnityPanelIndicatorsIndicatorEntry* self) {
#line 1342 "panel-indicators.c"
	gboolean vis;
#line 495 "panel-indicators.vala"
	g_return_if_fail (self != NULL);
#line 497 "panel-indicators.vala"
	vis = (GTK_WIDGET_FLAGS ((GtkWidget*) self->priv->_entry->menu) & GTK_VISIBLE) != 0;
#line 499 "panel-indicators.vala"
	if (vis == FALSE) {
#line 1350 "panel-indicators.c"
		guint _tmp0_;
		GQuark _tmp2_;
		guint _tmp1_;
#line 501 "panel-indicators.vala"
		clutter_actor_animate ((ClutterActor*) self->priv->bg, (gulong) CLUTTER_EASE_OUT_QUAD, (guint) 200, "opacity", 0, NULL);
#line 504 "panel-indicators.vala"
		g_signal_handlers_disconnect_matched ((GtkMenuShell*) self->priv->_entry->menu, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, (g_signal_parse_name ("move-current", GTK_TYPE_MENU_SHELL, &_tmp0_, NULL, FALSE), _tmp0_), 0, NULL, (GCallback) _unity_panel_indicators_indicator_entry_menu_key_moved_gtk_menu_shell_move_current, self);
#line 505 "panel-indicators.vala"
		g_signal_handlers_disconnect_matched ((GObject*) self->priv->_entry->menu, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_DETAIL | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, (g_signal_parse_name ("notify::visible", G_TYPE_OBJECT, &_tmp1_, &_tmp2_, FALSE), _tmp1_), 0, NULL, (GCallback) _unity_panel_indicators_indicator_entry_menu_vis_changed_g_object_notify, self);
#line 1360 "panel-indicators.c"
	}
}


#line 509 "panel-indicators.vala"
void unity_panel_indicators_indicator_entry_menu_key_moved (UnityPanelIndicatorsIndicatorEntry* self, GtkMenuDirectionType type) {
#line 1367 "panel-indicators.c"
	gboolean _tmp0_ = FALSE;
#line 509 "panel-indicators.vala"
	g_return_if_fail (self != NULL);
#line 511 "panel-indicators.vala"
	if (type != GTK_MENU_DIR_PARENT) {
#line 512 "panel-indicators.vala"
		_tmp0_ = type != GTK_MENU_DIR_CHILD;
#line 1375 "panel-indicators.c"
	} else {
#line 511 "panel-indicators.vala"
		_tmp0_ = FALSE;
#line 1379 "panel-indicators.c"
	}
#line 511 "panel-indicators.vala"
	if (_tmp0_) {
#line 513 "panel-indicators.vala"
		return;
#line 1385 "panel-indicators.c"
	}
#line 515 "panel-indicators.vala"
	g_signal_emit_by_name (self, "menu-moved", type);
#line 1389 "panel-indicators.c"
}


#line 518 "panel-indicators.vala"
static void unity_panel_indicators_indicator_entry_update_bg (UnityPanelIndicatorsIndicatorEntry* self, gint width, gint height) {
#line 1395 "panel-indicators.c"
	cairo_t* cr;
	cairo_t* _tmp0_;
	cairo_pattern_t* pat;
#line 518 "panel-indicators.vala"
	g_return_if_fail (self != NULL);
#line 1401 "panel-indicators.c"
	cr = NULL;
#line 522 "panel-indicators.vala"
	clutter_cairo_texture_set_surface_size (self->priv->bg, (guint) width, (guint) height);
#line 524 "panel-indicators.vala"
	cr = (_tmp0_ = clutter_cairo_texture_create (self->priv->bg), _cairo_destroy0 (cr), _tmp0_);
#line 526 "panel-indicators.vala"
	cairo_set_operator (cr, CAIRO_OPERATOR_CLEAR);
#line 527 "panel-indicators.vala"
	cairo_paint (cr);
#line 529 "panel-indicators.vala"
	cairo_set_operator (cr, CAIRO_OPERATOR_OVER);
#line 531 "panel-indicators.vala"
	cairo_set_line_width (cr, 1.0);
#line 533 "panel-indicators.vala"
	cairo_set_source_rgba (cr, 1.0, 1.0, 1.0, 0.2);
#line 535 "panel-indicators.vala"
	cairo_move_to (cr, (double) 1, (double) height);
#line 537 "panel-indicators.vala"
	cairo_line_to (cr, (double) 1, (double) 7);
#line 539 "panel-indicators.vala"
	cairo_curve_to (cr, (double) 1, (double) 2, (double) 1, (double) 2, (double) 10, (double) 2);
#line 543 "panel-indicators.vala"
	cairo_line_to (cr, (double) (width - 10), (double) 2);
#line 545 "panel-indicators.vala"
	cairo_curve_to (cr, (double) width, (double) 2, (double) width, (double) 2, (double) width, (double) 7);
#line 549 "panel-indicators.vala"
	cairo_line_to (cr, (double) width, (double) height);
#line 551 "panel-indicators.vala"
	cairo_line_to (cr, (double) 1, (double) height);
#line 553 "panel-indicators.vala"
	pat = cairo_pattern_create_linear ((double) 1, (double) 0, (double) 1, (double) height);
#line 554 "panel-indicators.vala"
	cairo_pattern_add_color_stop_rgba (pat, 0.0, (double) 1.0f, (double) 1.0f, (double) 1.0f, (double) 0.6f);
#line 555 "panel-indicators.vala"
	cairo_pattern_add_color_stop_rgba (pat, 1.0, (double) 1.0f, (double) 1.0f, (double) 1.0f, (double) 0.2f);
#line 557 "panel-indicators.vala"
	cairo_set_source (cr, pat);
#line 558 "panel-indicators.vala"
	cairo_fill (cr);
#line 1441 "panel-indicators.c"
	_cairo_destroy0 (cr);
	_cairo_pattern_destroy0 (pat);
}


#line 564 "panel-indicators.vala"
static void unity_panel_indicators_indicator_entry_real_allocate (ClutterActor* base, const ClutterActorBox* box, ClutterAllocationFlags flags) {
#line 1449 "panel-indicators.c"
	UnityPanelIndicatorsIndicatorEntry * self;
	float width = 0.0F;
	float height = 0.0F;
	ClutterActorBox _tmp0_ = {0};
	ClutterActorBox child_box;
	gboolean _tmp1_ = FALSE;
	self = (UnityPanelIndicatorsIndicatorEntry*) base;
#line 570 "panel-indicators.vala"
	CLUTTER_ACTOR_CLASS (unity_panel_indicators_indicator_entry_parent_class)->allocate ((ClutterActor*) CTK_BOX (self), box, flags);
#line 572 "panel-indicators.vala"
	width = floorf ((*box).x2 - (*box).x1);
#line 573 "panel-indicators.vala"
	height = floorf ((*box).y2 - (*box).y1) - 1;
#line 575 "panel-indicators.vala"
	child_box = (_tmp0_.x1 = (float) 0, _tmp0_);
#line 576 "panel-indicators.vala"
	child_box.x1 = (float) 0;
#line 577 "panel-indicators.vala"
	child_box.x2 = width;
#line 578 "panel-indicators.vala"
	child_box.y1 = (float) 0;
#line 579 "panel-indicators.vala"
	child_box.y2 = height;
#line 581 "panel-indicators.vala"
	if (width != clutter_actor_get_width ((ClutterActor*) self->priv->bg)) {
#line 581 "panel-indicators.vala"
		_tmp1_ = TRUE;
#line 1477 "panel-indicators.c"
	} else {
#line 582 "panel-indicators.vala"
		_tmp1_ = height != clutter_actor_get_height ((ClutterActor*) self->priv->bg);
#line 1481 "panel-indicators.c"
	}
#line 581 "panel-indicators.vala"
	if (_tmp1_) {
#line 584 "panel-indicators.vala"
		unity_panel_indicators_indicator_entry_update_bg (self, (gint) width, (gint) height);
#line 1487 "panel-indicators.c"
	}
#line 587 "panel-indicators.vala"
	clutter_actor_allocate ((ClutterActor*) self->priv->bg, &child_box, flags);
#line 1491 "panel-indicators.c"
}


#line 590 "panel-indicators.vala"
static void unity_panel_indicators_indicator_entry_real_paint (ClutterActor* base) {
#line 1497 "panel-indicators.c"
	UnityPanelIndicatorsIndicatorEntry * self;
	self = (UnityPanelIndicatorsIndicatorEntry*) base;
#line 592 "panel-indicators.vala"
	clutter_actor_paint ((ClutterActor*) self->priv->bg);
#line 593 "panel-indicators.vala"
	CLUTTER_ACTOR_CLASS (unity_panel_indicators_indicator_entry_parent_class)->paint ((ClutterActor*) CTK_BOX (self));
#line 1504 "panel-indicators.c"
}


#line 596 "panel-indicators.vala"
static void unity_panel_indicators_indicator_entry_real_map (ClutterActor* base) {
#line 1510 "panel-indicators.c"
	UnityPanelIndicatorsIndicatorEntry * self;
	self = (UnityPanelIndicatorsIndicatorEntry*) base;
#line 598 "panel-indicators.vala"
	CLUTTER_ACTOR_CLASS (unity_panel_indicators_indicator_entry_parent_class)->map ((ClutterActor*) CTK_BOX (self));
#line 599 "panel-indicators.vala"
	clutter_actor_map ((ClutterActor*) self->priv->bg);
#line 1517 "panel-indicators.c"
}


#line 602 "panel-indicators.vala"
static void unity_panel_indicators_indicator_entry_real_unmap (ClutterActor* base) {
#line 1523 "panel-indicators.c"
	UnityPanelIndicatorsIndicatorEntry * self;
	self = (UnityPanelIndicatorsIndicatorEntry*) base;
#line 604 "panel-indicators.vala"
	CLUTTER_ACTOR_CLASS (unity_panel_indicators_indicator_entry_parent_class)->unmap ((ClutterActor*) CTK_BOX (self));
#line 605 "panel-indicators.vala"
	clutter_actor_unmap ((ClutterActor*) self->priv->bg);
#line 1530 "panel-indicators.c"
}


IndicatorObjectEntry* unity_panel_indicators_indicator_entry_get_entry (UnityPanelIndicatorsIndicatorEntry* self) {
	IndicatorObjectEntry* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_entry;
#line 407 "panel-indicators.vala"
	return result;
#line 1540 "panel-indicators.c"
}


static void unity_panel_indicators_indicator_entry_set_entry (UnityPanelIndicatorsIndicatorEntry* self, IndicatorObjectEntry* value) {
	g_return_if_fail (self != NULL);
	self->priv->_entry = value;
	g_object_notify ((GObject *) self, "entry");
}


GtkMenu* unity_panel_indicators_indicator_entry_get_menu (UnityPanelIndicatorsIndicatorEntry* self) {
	GtkMenu* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_entry->menu;
#line 414 "panel-indicators.vala"
	return result;
#line 1557 "panel-indicators.c"
}


#line 446 "panel-indicators.vala"
static void _lambda4_ (UnityPanelIndicatorsIndicatorEntry* self) {
#line 1563 "panel-indicators.c"
	char* _tmp1_;
	char* _tmp0_ = NULL;
#line 448 "panel-indicators.vala"
	g_object_set (self->priv->image, "stock-id", _tmp1_ = (g_object_get (self->priv->_entry->image, "icon-name", &_tmp0_, NULL), _tmp0_), NULL);
#line 1568 "panel-indicators.c"
	_g_free0 (_tmp1_);
}


#line 446 "panel-indicators.vala"
static void __lambda4__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
#line 1575 "panel-indicators.c"
	_lambda4_ (self);
}


#line 452 "panel-indicators.vala"
static void _lambda5_ (UnityPanelIndicatorsIndicatorEntry* self) {
#line 1582 "panel-indicators.c"
	char* _tmp1_;
	char* _tmp0_ = NULL;
#line 454 "panel-indicators.vala"
	g_object_set (self->priv->image, "stock-id", _tmp1_ = (g_object_get (self->priv->_entry->image, "icon-name", &_tmp0_, NULL), _tmp0_), NULL);
#line 1587 "panel-indicators.c"
	_g_free0 (_tmp1_);
}


#line 452 "panel-indicators.vala"
static void __lambda5__gtk_icon_theme_changed (GtkIconTheme* _sender, gpointer self) {
#line 1594 "panel-indicators.c"
	_lambda5_ (self);
}


#line 462 "panel-indicators.vala"
static void _lambda6_ (UnityPanelIndicatorsIndicatorEntry* self) {
#line 1601 "panel-indicators.c"
	GdkPixbuf* _tmp1_;
	GdkPixbuf* _tmp0_ = NULL;
#line 464 "panel-indicators.vala"
	g_object_set (self->priv->image, "pixbuf", _tmp1_ = (g_object_get (self->priv->_entry->image, "pixbuf", &_tmp0_, NULL), _tmp0_), NULL);
#line 1606 "panel-indicators.c"
	_g_object_unref0 (_tmp1_);
}


#line 462 "panel-indicators.vala"
static void __lambda6__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
#line 1613 "panel-indicators.c"
	_lambda6_ (self);
}


#line 477 "panel-indicators.vala"
static void _lambda7_ (UnityPanelIndicatorsIndicatorEntry* self) {
#line 479 "panel-indicators.vala"
	clutter_text_set_text ((ClutterText*) self->priv->text, gtk_label_get_label (self->priv->_entry->label));
#line 1622 "panel-indicators.c"
}


#line 477 "panel-indicators.vala"
static void __lambda7__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
#line 1628 "panel-indicators.c"
	_lambda7_ (self);
}


static GObject * unity_panel_indicators_indicator_entry_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	UnityPanelIndicatorsIndicatorEntry * self;
	parent_class = G_OBJECT_CLASS (unity_panel_indicators_indicator_entry_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = UNITY_PANEL_INDICATORS_INDICATOR_ENTRY (obj);
	{
		CtkPadding _tmp1_ = {0};
		CtkPadding _tmp2_;
		ClutterCairoTexture* _tmp3_;
#line 428 "panel-indicators.vala"
		ctk_actor_set_padding ((CtkActor*) self, (_tmp2_ = (_tmp1_.top = (float) 0, _tmp1_.right = 6.0f, _tmp1_.bottom = (float) 0, _tmp1_.left = 6.0f, _tmp1_), &_tmp2_));
#line 430 "panel-indicators.vala"
		self->priv->bg = (_tmp3_ = g_object_ref_sink ((ClutterCairoTexture*) clutter_cairo_texture_new ((guint) 10, (guint) 10)), _g_object_unref0 (self->priv->bg), _tmp3_);
#line 431 "panel-indicators.vala"
		clutter_actor_set_parent ((ClutterActor*) self->priv->bg, (ClutterActor*) self);
#line 432 "panel-indicators.vala"
		clutter_actor_set_opacity ((ClutterActor*) self->priv->bg, (guint8) 0);
#line 433 "panel-indicators.vala"
		clutter_actor_show ((ClutterActor*) self->priv->bg);
#line 435 "panel-indicators.vala"
		if (GTK_IS_IMAGE (self->priv->_entry->image)) {
#line 1656 "panel-indicators.c"
			CtkImage* _tmp4_;
			char* _tmp6_;
			char* _tmp5_ = NULL;
			gboolean _tmp7_;
			GdkPixbuf* _tmp11_;
			GdkPixbuf* _tmp10_ = NULL;
			gboolean _tmp12_;
#line 437 "panel-indicators.vala"
			self->priv->image = (_tmp4_ = g_object_ref_sink ((CtkImage*) ctk_image_new ((guint) 22)), _g_object_unref0 (self->priv->image), _tmp4_);
#line 438 "panel-indicators.vala"
			clutter_container_add_actor ((ClutterContainer*) self, (ClutterActor*) self->priv->image);
#line 439 "panel-indicators.vala"
			clutter_actor_show ((ClutterActor*) self->priv->image);
#line 441 "panel-indicators.vala"
			if ((_tmp7_ = (_tmp6_ = (g_object_get (self->priv->_entry->image, "icon-name", &_tmp5_, NULL), _tmp5_)) != NULL, _g_free0 (_tmp6_), _tmp7_)) {
#line 1672 "panel-indicators.c"
				char* _tmp9_;
				char* _tmp8_ = NULL;
				GtkIconTheme* theme;
#line 444 "panel-indicators.vala"
				g_object_set (self->priv->image, "stock-id", _tmp9_ = (g_object_get (self->priv->_entry->image, "icon-name", &_tmp8_, NULL), _tmp8_), NULL);
#line 1678 "panel-indicators.c"
				_g_free0 (_tmp9_);
#line 446 "panel-indicators.vala"
				g_signal_connect_object ((GObject*) self->priv->_entry->image, "notify::icon-name", (GCallback) __lambda4__g_object_notify, self, 0);
#line 451 "panel-indicators.vala"
				theme = gtk_icon_theme_get_default ();
#line 452 "panel-indicators.vala"
				g_signal_connect_object (theme, "changed", (GCallback) __lambda5__gtk_icon_theme_changed, self, 0);
#line 1686 "panel-indicators.c"
			}
#line 458 "panel-indicators.vala"
			if ((_tmp12_ = (_tmp11_ = (g_object_get (self->priv->_entry->image, "pixbuf", &_tmp10_, NULL), _tmp10_)) != NULL, _g_object_unref0 (_tmp11_), _tmp12_)) {
#line 1690 "panel-indicators.c"
				GdkPixbuf* _tmp14_;
				GdkPixbuf* _tmp13_ = NULL;
#line 460 "panel-indicators.vala"
				g_object_set (self->priv->image, "pixbuf", _tmp14_ = (g_object_get (self->priv->_entry->image, "pixbuf", &_tmp13_, NULL), _tmp13_), NULL);
#line 1695 "panel-indicators.c"
				_g_object_unref0 (_tmp14_);
#line 462 "panel-indicators.vala"
				g_signal_connect_object ((GObject*) self->priv->_entry->image, "notify::pixbuf", (GCallback) __lambda6__g_object_notify, self, 0);
#line 1699 "panel-indicators.c"
			}
		}
#line 469 "panel-indicators.vala"
		if (GTK_IS_LABEL (self->priv->_entry->label)) {
#line 1704 "panel-indicators.c"
			CtkText* _tmp15_;
#line 471 "panel-indicators.vala"
			self->priv->text = (_tmp15_ = g_object_ref_sink ((CtkText*) ctk_text_new ("")), _g_object_unref0 (self->priv->text), _tmp15_);
#line 472 "panel-indicators.vala"
			clutter_container_add_actor ((ClutterContainer*) self, (ClutterActor*) self->priv->text);
#line 473 "panel-indicators.vala"
			clutter_actor_show ((ClutterActor*) self->priv->text);
#line 475 "panel-indicators.vala"
			clutter_text_set_text ((ClutterText*) self->priv->text, gtk_label_get_label (self->priv->_entry->label));
#line 477 "panel-indicators.vala"
			g_signal_connect_object ((GObject*) self->priv->_entry->label, "notify::label", (GCallback) __lambda7__g_object_notify, self, 0);
#line 1716 "panel-indicators.c"
		}
	}
	return obj;
}


static void unity_panel_indicators_indicator_entry_class_init (UnityPanelIndicatorsIndicatorEntryClass * klass) {
	unity_panel_indicators_indicator_entry_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (UnityPanelIndicatorsIndicatorEntryPrivate));
	CLUTTER_ACTOR_CLASS (klass)->allocate = unity_panel_indicators_indicator_entry_real_allocate;
	CLUTTER_ACTOR_CLASS (klass)->paint = unity_panel_indicators_indicator_entry_real_paint;
	CLUTTER_ACTOR_CLASS (klass)->map = unity_panel_indicators_indicator_entry_real_map;
	CLUTTER_ACTOR_CLASS (klass)->unmap = unity_panel_indicators_indicator_entry_real_unmap;
	G_OBJECT_CLASS (klass)->get_property = unity_panel_indicators_indicator_entry_get_property;
	G_OBJECT_CLASS (klass)->set_property = unity_panel_indicators_indicator_entry_set_property;
	G_OBJECT_CLASS (klass)->constructor = unity_panel_indicators_indicator_entry_constructor;
	G_OBJECT_CLASS (klass)->finalize = unity_panel_indicators_indicator_entry_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), UNITY_PANEL_INDICATORS_INDICATOR_ENTRY_ENTRY, g_param_spec_pointer ("entry", "entry", "entry", G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
	g_object_class_install_property (G_OBJECT_CLASS (klass), UNITY_PANEL_INDICATORS_INDICATOR_ENTRY_MENU, g_param_spec_object ("menu", "menu", "menu", GTK_TYPE_MENU, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_signal_new ("menu_moved", UNITY_PANEL_INDICATORS_TYPE_INDICATOR_ENTRY, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__ENUM, G_TYPE_NONE, 1, GTK_TYPE_MENU_DIRECTION_TYPE);
}


static void unity_panel_indicators_indicator_entry_instance_init (UnityPanelIndicatorsIndicatorEntry * self) {
	self->priv = UNITY_PANEL_INDICATORS_INDICATOR_ENTRY_GET_PRIVATE (self);
}


static void unity_panel_indicators_indicator_entry_finalize (GObject* obj) {
	UnityPanelIndicatorsIndicatorEntry * self;
	self = UNITY_PANEL_INDICATORS_INDICATOR_ENTRY (obj);
	_g_object_unref0 (self->priv->bg);
	_g_object_unref0 (self->priv->image);
	_g_object_unref0 (self->priv->text);
	G_OBJECT_CLASS (unity_panel_indicators_indicator_entry_parent_class)->finalize (obj);
}


GType unity_panel_indicators_indicator_entry_get_type (void) {
	static GType unity_panel_indicators_indicator_entry_type_id = 0;
	if (unity_panel_indicators_indicator_entry_type_id == 0) {
		static const GTypeInfo g_define_type_info = { sizeof (UnityPanelIndicatorsIndicatorEntryClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) unity_panel_indicators_indicator_entry_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (UnityPanelIndicatorsIndicatorEntry), 0, (GInstanceInitFunc) unity_panel_indicators_indicator_entry_instance_init, NULL };
		unity_panel_indicators_indicator_entry_type_id = g_type_register_static (CTK_TYPE_BOX, "UnityPanelIndicatorsIndicatorEntry", &g_define_type_info, 0);
	}
	return unity_panel_indicators_indicator_entry_type_id;
}


static void unity_panel_indicators_indicator_entry_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	UnityPanelIndicatorsIndicatorEntry * self;
	self = UNITY_PANEL_INDICATORS_INDICATOR_ENTRY (object);
	switch (property_id) {
		case UNITY_PANEL_INDICATORS_INDICATOR_ENTRY_ENTRY:
		g_value_set_pointer (value, unity_panel_indicators_indicator_entry_get_entry (self));
		break;
		case UNITY_PANEL_INDICATORS_INDICATOR_ENTRY_MENU:
		g_value_set_object (value, unity_panel_indicators_indicator_entry_get_menu (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void unity_panel_indicators_indicator_entry_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	UnityPanelIndicatorsIndicatorEntry * self;
	self = UNITY_PANEL_INDICATORS_INDICATOR_ENTRY (object);
	switch (property_id) {
		case UNITY_PANEL_INDICATORS_INDICATOR_ENTRY_ENTRY:
		unity_panel_indicators_indicator_entry_set_entry (self, g_value_get_pointer (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static int _vala_strcmp0 (const char * str1, const char * str2) {
	if (str1 == NULL) {
		return -(str1 != str2);
	}
	if (str2 == NULL) {
		return str1 != str2;
	}
	return strcmp (str1, str2);
}




