.TH unity-panel-service "1" "8 December 2010" "" "Linux User's Manual"

.SH NAME
unity-panel-service \- program for drawing the panel with the unity shell.

.SH SYNOPSIS
.B unity-panel-service
.br

.SH DESCRIPTION
The \fBunity-panel-service\fP program is normally started automatically by the Unity shell (which gets started as a compiz module) and is used to draw panels which can then be used for the global menu, or to hold indicators.

.SH OPTIONS
\fBunity-panel-service\fP takes no options.

.SH NOTES

.SH "SEE ALSO"

