/* quicklist-rendering.c generated by valac, the Vala compiler
 * generated from quicklist-rendering.vala, do not modify */

/*
 * Copyright (C) 2010 Canonical, Ltd.
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License
 * version 3.0 as published by the Free Software Foundation.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License version 3.0 for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library. If not, see
 * <http://www.gnu.org/licenses/>.
 *
 * Authored by Mirco "MacSlow" Müller <mirco.mueller@canonical.com>
 *
 */

#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>
#include <cairo.h>
#include <pango/pangocairo.h>
#include <pango/pango.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>
#include <stdlib.h>
#include <string.h>
#include <clutk/clutk.h>


#define UNITY_QUICKLIST_RENDERING_TYPE_SEPERATOR (unity_quicklist_rendering_seperator_get_type ())
#define UNITY_QUICKLIST_RENDERING_SEPERATOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), UNITY_QUICKLIST_RENDERING_TYPE_SEPERATOR, UnityQuicklistRenderingSeperator))
#define UNITY_QUICKLIST_RENDERING_SEPERATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), UNITY_QUICKLIST_RENDERING_TYPE_SEPERATOR, UnityQuicklistRenderingSeperatorClass))
#define UNITY_QUICKLIST_RENDERING_IS_SEPERATOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), UNITY_QUICKLIST_RENDERING_TYPE_SEPERATOR))
#define UNITY_QUICKLIST_RENDERING_IS_SEPERATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), UNITY_QUICKLIST_RENDERING_TYPE_SEPERATOR))
#define UNITY_QUICKLIST_RENDERING_SEPERATOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), UNITY_QUICKLIST_RENDERING_TYPE_SEPERATOR, UnityQuicklistRenderingSeperatorClass))

typedef struct _UnityQuicklistRenderingSeperator UnityQuicklistRenderingSeperator;
typedef struct _UnityQuicklistRenderingSeperatorClass UnityQuicklistRenderingSeperatorClass;
typedef struct _UnityQuicklistRenderingSeperatorPrivate UnityQuicklistRenderingSeperatorPrivate;

#define UNITY_QUICKLIST_RENDERING_TYPE_ITEM (unity_quicklist_rendering_item_get_type ())
#define UNITY_QUICKLIST_RENDERING_ITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), UNITY_QUICKLIST_RENDERING_TYPE_ITEM, UnityQuicklistRenderingItem))
#define UNITY_QUICKLIST_RENDERING_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), UNITY_QUICKLIST_RENDERING_TYPE_ITEM, UnityQuicklistRenderingItemClass))
#define UNITY_QUICKLIST_RENDERING_IS_ITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), UNITY_QUICKLIST_RENDERING_TYPE_ITEM))
#define UNITY_QUICKLIST_RENDERING_IS_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), UNITY_QUICKLIST_RENDERING_TYPE_ITEM))
#define UNITY_QUICKLIST_RENDERING_ITEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), UNITY_QUICKLIST_RENDERING_TYPE_ITEM, UnityQuicklistRenderingItemClass))

typedef struct _UnityQuicklistRenderingItem UnityQuicklistRenderingItem;
typedef struct _UnityQuicklistRenderingItemClass UnityQuicklistRenderingItemClass;
typedef struct _UnityQuicklistRenderingItemPrivate UnityQuicklistRenderingItemPrivate;
#define _cairo_surface_destroy0(var) ((var == NULL) ? NULL : (var = (cairo_surface_destroy (var), NULL)))
#define _cairo_destroy0(var) ((var == NULL) ? NULL : (var = (cairo_destroy (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _pango_font_description_free0(var) ((var == NULL) ? NULL : (var = (pango_font_description_free (var), NULL)))

#define UNITY_QUICKLIST_RENDERING_TYPE_MENU (unity_quicklist_rendering_menu_get_type ())
#define UNITY_QUICKLIST_RENDERING_MENU(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), UNITY_QUICKLIST_RENDERING_TYPE_MENU, UnityQuicklistRenderingMenu))
#define UNITY_QUICKLIST_RENDERING_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), UNITY_QUICKLIST_RENDERING_TYPE_MENU, UnityQuicklistRenderingMenuClass))
#define UNITY_QUICKLIST_RENDERING_IS_MENU(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), UNITY_QUICKLIST_RENDERING_TYPE_MENU))
#define UNITY_QUICKLIST_RENDERING_IS_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), UNITY_QUICKLIST_RENDERING_TYPE_MENU))
#define UNITY_QUICKLIST_RENDERING_MENU_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), UNITY_QUICKLIST_RENDERING_TYPE_MENU, UnityQuicklistRenderingMenuClass))

typedef struct _UnityQuicklistRenderingMenu UnityQuicklistRenderingMenu;
typedef struct _UnityQuicklistRenderingMenuClass UnityQuicklistRenderingMenuClass;
typedef struct _UnityQuicklistRenderingMenuPrivate UnityQuicklistRenderingMenuPrivate;
#define _cairo_pattern_destroy0(var) ((var == NULL) ? NULL : (var = (cairo_pattern_destroy (var), NULL)))

struct _UnityQuicklistRenderingSeperator {
	GObject parent_instance;
	UnityQuicklistRenderingSeperatorPrivate * priv;
};

struct _UnityQuicklistRenderingSeperatorClass {
	GObjectClass parent_class;
};

struct _UnityQuicklistRenderingItem {
	GObject parent_instance;
	UnityQuicklistRenderingItemPrivate * priv;
};

struct _UnityQuicklistRenderingItemClass {
	GObjectClass parent_class;
};

struct _UnityQuicklistRenderingMenu {
	GObject parent_instance;
	UnityQuicklistRenderingMenuPrivate * priv;
};

struct _UnityQuicklistRenderingMenuClass {
	GObjectClass parent_class;
};


static gpointer unity_quicklist_rendering_seperator_parent_class = NULL;
static gpointer unity_quicklist_rendering_item_parent_class = NULL;
static gpointer unity_quicklist_rendering_menu_parent_class = NULL;

#define UNITY_QUICKLIST_RENDERING_LINE_WIDTH 0.083f
#define UNITY_QUICKLIST_RENDERING_LINE_WIDTH_ABS 1.5f
#define UNITY_QUICKLIST_RENDERING_TEXT_HEIGHT 1.0f
#define UNITY_QUICKLIST_RENDERING_MAX_TEXT_WIDTH 15.0f
#define UNITY_QUICKLIST_RENDERING_GAP 0.25f
#define UNITY_QUICKLIST_RENDERING_MARGIN 0.5f
#define UNITY_QUICKLIST_RENDERING_BORDER 0.25f
#define UNITY_QUICKLIST_RENDERING_CORNER_RADIUS 0.3f
#define UNITY_QUICKLIST_RENDERING_CORNER_RADIUS_ABS 5.0f
#define UNITY_QUICKLIST_RENDERING_SHADOW_SIZE 1.25f
#define UNITY_QUICKLIST_RENDERING_ITEM_HEIGHT 2.0f
#define UNITY_QUICKLIST_RENDERING_ITEM_CORNER_RADIUS 0.3f
#define UNITY_QUICKLIST_RENDERING_ITEM_CORNER_RADIUS_ABS 4.0f
#define UNITY_QUICKLIST_RENDERING_ANCHOR_HEIGHT 1.5f
#define UNITY_QUICKLIST_RENDERING_ANCHOR_HEIGHT_ABS 18.0f
#define UNITY_QUICKLIST_RENDERING_ANCHOR_WIDTH 0.75f
#define UNITY_QUICKLIST_RENDERING_ANCHOR_WIDTH_ABS 10.0f
GType unity_quicklist_rendering_seperator_get_type (void);
enum  {
	UNITY_QUICKLIST_RENDERING_SEPERATOR_DUMMY_PROPERTY
};
void unity_quicklist_rendering_seperator_fill_mask (cairo_t* cr);
void unity_quicklist_rendering_seperator_image_background (cairo_t* cr, gint w, gint h);
UnityQuicklistRenderingSeperator* unity_quicklist_rendering_seperator_new (void);
UnityQuicklistRenderingSeperator* unity_quicklist_rendering_seperator_construct (GType object_type);
GType unity_quicklist_rendering_item_get_type (void);
enum  {
	UNITY_QUICKLIST_RENDERING_ITEM_DUMMY_PROPERTY
};
static void _unity_quicklist_rendering_item_round_rect (cairo_t* cr, double aspect, double x, double y, double corner_radius, double width, double height);
void unity_quicklist_rendering_item_get_text_extents (const char* font, const char* text, gint* width, gint* height);
void unity_quicklist_rendering_item_normal_mask (cairo_t* cr, gint w, gint h, const char* font, const char* text);
void unity_quicklist_rendering_item_selected_mask (cairo_t* cr, gint w, gint h, const char* font, const char* text);
UnityQuicklistRenderingItem* unity_quicklist_rendering_item_new (void);
UnityQuicklistRenderingItem* unity_quicklist_rendering_item_construct (GType object_type);
GType unity_quicklist_rendering_menu_get_type (void);
enum  {
	UNITY_QUICKLIST_RENDERING_MENU_DUMMY_PROPERTY
};
static double _unity_quicklist_rendering_menu_align (double val);
static void _unity_quicklist_rendering_menu_round_rect_anchor (cairo_t* cr, double aspect, double x, double y, double corner_radius, double width, double height, double anchor_width, double anchor_height, double anchor_x, double anchor_y);
static void _unity_quicklist_rendering_menu_draw_mask (cairo_t* cr, gint w, gint h, float anchor_y);
void unity_quicklist_rendering_menu_full_mask (cairo_t* cr, gint w, gint h, float anchor_y);
void unity_quicklist_rendering_menu_fill_mask (cairo_t* cr, gint w, gint h, float anchor_y);
void unity_quicklist_rendering_menu_background (cairo_t* cr, gint w, gint h, float anchor_y);
UnityQuicklistRenderingMenu* unity_quicklist_rendering_menu_new (void);
UnityQuicklistRenderingMenu* unity_quicklist_rendering_menu_construct (GType object_type);



#line 45 "quicklist-rendering.vala"
void unity_quicklist_rendering_seperator_fill_mask (cairo_t* cr) {
#line 45 "quicklist-rendering.vala"
	g_return_if_fail (cr != NULL);
#line 49 "quicklist-rendering.vala"
	cairo_set_operator (cr, CAIRO_OPERATOR_CLEAR);
#line 50 "quicklist-rendering.vala"
	cairo_paint (cr);
#line 53 "quicklist-rendering.vala"
	cairo_set_operator (cr, CAIRO_OPERATOR_SOURCE);
#line 54 "quicklist-rendering.vala"
	cairo_scale (cr, (double) 1.0f, (double) 1.0f);
#line 55 "quicklist-rendering.vala"
	cairo_set_source_rgba (cr, (double) 1.0f, (double) 1.0f, (double) 1.0f, (double) 1.0f);
#line 56 "quicklist-rendering.vala"
	cairo_paint (cr);
#line 175 "quicklist-rendering.c"
}


#line 59 "quicklist-rendering.vala"
void unity_quicklist_rendering_seperator_image_background (cairo_t* cr, gint w, gint h) {
#line 181 "quicklist-rendering.c"
	float half_height;
	float fract;
#line 59 "quicklist-rendering.vala"
	g_return_if_fail (cr != NULL);
#line 65 "quicklist-rendering.vala"
	cairo_set_operator (cr, CAIRO_OPERATOR_CLEAR);
#line 66 "quicklist-rendering.vala"
	cairo_paint (cr);
#line 69 "quicklist-rendering.vala"
	cairo_scale (cr, (double) 1.0f, (double) 1.0f);
#line 70 "quicklist-rendering.vala"
	cairo_set_operator (cr, CAIRO_OPERATOR_SOURCE);
#line 73 "quicklist-rendering.vala"
	cairo_set_line_width (cr, (double) 1.5f);
#line 75 "quicklist-rendering.vala"
	cairo_set_source_rgba (cr, (double) 1.0f, (double) 1.0f, (double) 1.0f, (double) 0.75f);
#line 76 "quicklist-rendering.vala"
	cairo_set_line_cap (cr, CAIRO_LINE_CAP_ROUND);
#line 79 "quicklist-rendering.vala"
	half_height = ((float) h) / 2.0f;
#line 80 "quicklist-rendering.vala"
	fract = half_height - ((gint) half_height);
#line 81 "quicklist-rendering.vala"
	if (fract == 0.0f) {
#line 82 "quicklist-rendering.vala"
		half_height = half_height + 0.5f;
#line 208 "quicklist-rendering.c"
	}
#line 83 "quicklist-rendering.vala"
	cairo_move_to (cr, (double) 0.0f, (double) half_height);
#line 84 "quicklist-rendering.vala"
	cairo_line_to (cr, (double) ((float) w), (double) half_height);
#line 86 "quicklist-rendering.vala"
	cairo_stroke (cr);
#line 216 "quicklist-rendering.c"
}


#line 43 "quicklist-rendering.vala"
UnityQuicklistRenderingSeperator* unity_quicklist_rendering_seperator_construct (GType object_type) {
#line 222 "quicklist-rendering.c"
	UnityQuicklistRenderingSeperator * self;
#line 43 "quicklist-rendering.vala"
	self = (UnityQuicklistRenderingSeperator*) g_object_new (object_type, NULL);
#line 226 "quicklist-rendering.c"
	return self;
}


#line 43 "quicklist-rendering.vala"
UnityQuicklistRenderingSeperator* unity_quicklist_rendering_seperator_new (void) {
#line 43 "quicklist-rendering.vala"
	return unity_quicklist_rendering_seperator_construct (UNITY_QUICKLIST_RENDERING_TYPE_SEPERATOR);
#line 235 "quicklist-rendering.c"
}


static void unity_quicklist_rendering_seperator_class_init (UnityQuicklistRenderingSeperatorClass * klass) {
	unity_quicklist_rendering_seperator_parent_class = g_type_class_peek_parent (klass);
}


static void unity_quicklist_rendering_seperator_instance_init (UnityQuicklistRenderingSeperator * self) {
}


GType unity_quicklist_rendering_seperator_get_type (void) {
	static volatile gsize unity_quicklist_rendering_seperator_type_id__volatile = 0;
	if (g_once_init_enter (&unity_quicklist_rendering_seperator_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (UnityQuicklistRenderingSeperatorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) unity_quicklist_rendering_seperator_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (UnityQuicklistRenderingSeperator), 0, (GInstanceInitFunc) unity_quicklist_rendering_seperator_instance_init, NULL };
		GType unity_quicklist_rendering_seperator_type_id;
		unity_quicklist_rendering_seperator_type_id = g_type_register_static (G_TYPE_OBJECT, "UnityQuicklistRenderingSeperator", &g_define_type_info, 0);
		g_once_init_leave (&unity_quicklist_rendering_seperator_type_id__volatile, unity_quicklist_rendering_seperator_type_id);
	}
	return unity_quicklist_rendering_seperator_type_id__volatile;
}


#line 92 "quicklist-rendering.vala"
static void _unity_quicklist_rendering_item_round_rect (cairo_t* cr, double aspect, double x, double y, double corner_radius, double width, double height) {
#line 262 "quicklist-rendering.c"
	double radius;
#line 92 "quicklist-rendering.vala"
	g_return_if_fail (cr != NULL);
#line 101 "quicklist-rendering.vala"
	radius = corner_radius / aspect;
#line 104 "quicklist-rendering.vala"
	cairo_move_to (cr, x + radius, y);
#line 107 "quicklist-rendering.vala"
	cairo_line_to (cr, (x + width) - radius, y);
#line 110 "quicklist-rendering.vala"
	cairo_arc (cr, (x + width) - radius, y + radius, radius, ((-90.0f) * G_PI) / 180.0f, (0.0f * G_PI) / 180.0f);
#line 117 "quicklist-rendering.vala"
	cairo_line_to (cr, x + width, (y + height) - radius);
#line 120 "quicklist-rendering.vala"
	cairo_arc (cr, (x + width) - radius, (y + height) - radius, radius, (0.0f * G_PI) / 180.0f, (90.0f * G_PI) / 180.0f);
#line 127 "quicklist-rendering.vala"
	cairo_line_to (cr, x + radius, y + height);
#line 130 "quicklist-rendering.vala"
	cairo_arc (cr, x + radius, (y + height) - radius, radius, (90.0f * G_PI) / 180.0f, (180.0f * G_PI) / 180.0f);
#line 137 "quicklist-rendering.vala"
	cairo_arc (cr, x + radius, y + radius, radius, (180.0f * G_PI) / 180.0f, (270.0f * G_PI) / 180.0f);
#line 284 "quicklist-rendering.c"
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


#line 144 "quicklist-rendering.vala"
void unity_quicklist_rendering_item_get_text_extents (const char* font, const char* text, gint* width, gint* height) {
#line 295 "quicklist-rendering.c"
	cairo_surface_t* surface;
	cairo_t* cr;
	PangoLayout* layout;
	GtkSettings* settings;
	PangoFontDescription* desc;
	PangoContext* pango_context;
	GdkScreen* screen;
	gint _tmp0_;
	PangoRectangle log_rect = {0};
#line 144 "quicklist-rendering.vala"
	g_return_if_fail (font != NULL);
#line 144 "quicklist-rendering.vala"
	g_return_if_fail (text != NULL);
#line 150 "quicklist-rendering.vala"
	surface = cairo_image_surface_create (CAIRO_FORMAT_A1, 1, 1);
#line 151 "quicklist-rendering.vala"
	cr = cairo_create (surface);
#line 152 "quicklist-rendering.vala"
	layout = pango_cairo_create_layout (cr);
#line 153 "quicklist-rendering.vala"
	settings = _g_object_ref0 (gtk_settings_get_default ());
#line 154 "quicklist-rendering.vala"
	desc = pango_font_description_from_string (font);
#line 155 "quicklist-rendering.vala"
	pango_font_description_set_weight (desc, PANGO_WEIGHT_NORMAL);
#line 156 "quicklist-rendering.vala"
	pango_layout_set_font_description (layout, desc);
#line 157 "quicklist-rendering.vala"
	pango_layout_set_wrap (layout, PANGO_WRAP_WORD_CHAR);
#line 158 "quicklist-rendering.vala"
	pango_layout_set_ellipsize (layout, PANGO_ELLIPSIZE_END);
#line 159 "quicklist-rendering.vala"
	pango_layout_set_text (layout, text, -1);
#line 160 "quicklist-rendering.vala"
	pango_context = _g_object_ref0 (pango_layout_get_context (layout));
#line 161 "quicklist-rendering.vala"
	screen = _g_object_ref0 (gdk_screen_get_default ());
#line 162 "quicklist-rendering.vala"
	pango_cairo_context_set_font_options (pango_context, gdk_screen_get_font_options (screen));
#line 164 "quicklist-rendering.vala"
	pango_cairo_context_set_resolution (pango_context, (double) (((float) (g_object_get (settings, "gtk-xft-dpi", &_tmp0_, NULL), _tmp0_)) / ((float) PANGO_SCALE)));
#line 167 "quicklist-rendering.vala"
	pango_layout_context_changed (layout);
#line 169 "quicklist-rendering.vala"
	pango_layout_get_extents (layout, NULL, &log_rect);
#line 170 "quicklist-rendering.vala"
	*width = log_rect.width / PANGO_SCALE;
#line 171 "quicklist-rendering.vala"
	*height = log_rect.height / PANGO_SCALE;
#line 345 "quicklist-rendering.c"
	_cairo_surface_destroy0 (surface);
	_cairo_destroy0 (cr);
	_g_object_unref0 (layout);
	_g_object_unref0 (settings);
	_pango_font_description_free0 (desc);
	_g_object_unref0 (pango_context);
	_g_object_unref0 (screen);
}


#line 174 "quicklist-rendering.vala"
void unity_quicklist_rendering_item_normal_mask (cairo_t* cr, gint w, gint h, const char* font, const char* text) {
#line 358 "quicklist-rendering.c"
	PangoLayout* layout;
	GtkSettings* settings;
	PangoFontDescription* desc;
	PangoContext* pango_context;
	GdkScreen* screen;
	gint _tmp0_;
	gint text_width = 0;
	gint text_height = 0;
#line 174 "quicklist-rendering.vala"
	g_return_if_fail (cr != NULL);
#line 174 "quicklist-rendering.vala"
	g_return_if_fail (font != NULL);
#line 174 "quicklist-rendering.vala"
	g_return_if_fail (text != NULL);
#line 182 "quicklist-rendering.vala"
	cairo_set_operator (cr, CAIRO_OPERATOR_CLEAR);
#line 183 "quicklist-rendering.vala"
	cairo_paint (cr);
#line 186 "quicklist-rendering.vala"
	cairo_set_operator (cr, CAIRO_OPERATOR_SOURCE);
#line 187 "quicklist-rendering.vala"
	cairo_scale (cr, (double) 1.0f, (double) 1.0f);
#line 188 "quicklist-rendering.vala"
	cairo_set_source_rgba (cr, (double) 1.0f, (double) 1.0f, (double) 1.0f, (double) 1.0f);
#line 190 "quicklist-rendering.vala"
	layout = pango_cairo_create_layout (cr);
#line 191 "quicklist-rendering.vala"
	settings = _g_object_ref0 (gtk_settings_get_default ());
#line 192 "quicklist-rendering.vala"
	desc = pango_font_description_from_string (font);
#line 193 "quicklist-rendering.vala"
	pango_font_description_set_weight (desc, PANGO_WEIGHT_NORMAL);
#line 194 "quicklist-rendering.vala"
	pango_layout_set_font_description (layout, desc);
#line 195 "quicklist-rendering.vala"
	pango_layout_set_wrap (layout, PANGO_WRAP_WORD_CHAR);
#line 196 "quicklist-rendering.vala"
	pango_layout_set_ellipsize (layout, PANGO_ELLIPSIZE_END);
#line 197 "quicklist-rendering.vala"
	pango_layout_set_text (layout, text, -1);
#line 198 "quicklist-rendering.vala"
	pango_context = _g_object_ref0 (pango_layout_get_context (layout));
#line 199 "quicklist-rendering.vala"
	screen = _g_object_ref0 (gdk_screen_get_default ());
#line 200 "quicklist-rendering.vala"
	pango_cairo_context_set_font_options (pango_context, gdk_screen_get_font_options (screen));
#line 202 "quicklist-rendering.vala"
	pango_cairo_context_set_resolution (pango_context, (double) (((float) (g_object_get (settings, "gtk-xft-dpi", &_tmp0_, NULL), _tmp0_)) / ((float) PANGO_SCALE)));
#line 205 "quicklist-rendering.vala"
	pango_layout_context_changed (layout);
#line 209 "quicklist-rendering.vala"
	unity_quicklist_rendering_item_get_text_extents (font, text, &text_width, &text_height);
#line 210 "quicklist-rendering.vala"
	cairo_move_to (cr, ctk_em_to_pixel ((double) UNITY_QUICKLIST_RENDERING_MARGIN), (double) (((float) (h - text_height)) / 2.0f));
#line 213 "quicklist-rendering.vala"
	pango_cairo_show_layout (cr, layout);
#line 415 "quicklist-rendering.c"
	_g_object_unref0 (layout);
	_g_object_unref0 (settings);
	_pango_font_description_free0 (desc);
	_g_object_unref0 (pango_context);
	_g_object_unref0 (screen);
}


#line 216 "quicklist-rendering.vala"
void unity_quicklist_rendering_item_selected_mask (cairo_t* cr, gint w, gint h, const char* font, const char* text) {
#line 426 "quicklist-rendering.c"
	PangoLayout* layout;
	GtkSettings* settings;
	PangoFontDescription* desc;
	PangoContext* pango_context;
	GdkScreen* screen;
	gint _tmp0_;
	gint text_width = 0;
	gint text_height = 0;
#line 216 "quicklist-rendering.vala"
	g_return_if_fail (cr != NULL);
#line 216 "quicklist-rendering.vala"
	g_return_if_fail (font != NULL);
#line 216 "quicklist-rendering.vala"
	g_return_if_fail (text != NULL);
#line 224 "quicklist-rendering.vala"
	cairo_set_operator (cr, CAIRO_OPERATOR_CLEAR);
#line 225 "quicklist-rendering.vala"
	cairo_paint (cr);
#line 228 "quicklist-rendering.vala"
	cairo_set_operator (cr, CAIRO_OPERATOR_SOURCE);
#line 229 "quicklist-rendering.vala"
	cairo_scale (cr, (double) 1.0f, (double) 1.0f);
#line 230 "quicklist-rendering.vala"
	cairo_set_source_rgba (cr, (double) 1.0f, (double) 1.0f, (double) 1.0f, (double) 1.0f);
#line 233 "quicklist-rendering.vala"
	_unity_quicklist_rendering_item_round_rect (cr, (double) 1.0f, (double) 0.5f, (double) 0.5f, (double) UNITY_QUICKLIST_RENDERING_ITEM_CORNER_RADIUS_ABS, (double) (w - 1.0f), (double) (h - 1.0f));
#line 240 "quicklist-rendering.vala"
	cairo_fill (cr);
#line 243 "quicklist-rendering.vala"
	layout = pango_cairo_create_layout (cr);
#line 244 "quicklist-rendering.vala"
	settings = _g_object_ref0 (gtk_settings_get_default ());
#line 245 "quicklist-rendering.vala"
	desc = pango_font_description_from_string (font);
#line 246 "quicklist-rendering.vala"
	pango_font_description_set_weight (desc, PANGO_WEIGHT_NORMAL);
#line 247 "quicklist-rendering.vala"
	pango_layout_set_font_description (layout, desc);
#line 248 "quicklist-rendering.vala"
	pango_layout_set_wrap (layout, PANGO_WRAP_WORD_CHAR);
#line 249 "quicklist-rendering.vala"
	pango_layout_set_ellipsize (layout, PANGO_ELLIPSIZE_END);
#line 250 "quicklist-rendering.vala"
	pango_layout_set_text (layout, text, -1);
#line 252 "quicklist-rendering.vala"
	pango_context = _g_object_ref0 (pango_layout_get_context (layout));
#line 253 "quicklist-rendering.vala"
	screen = _g_object_ref0 (gdk_screen_get_default ());
#line 254 "quicklist-rendering.vala"
	pango_cairo_context_set_font_options (pango_context, gdk_screen_get_font_options (screen));
#line 256 "quicklist-rendering.vala"
	pango_cairo_context_set_resolution (pango_context, (double) (((float) (g_object_get (settings, "gtk-xft-dpi", &_tmp0_, NULL), _tmp0_)) / ((float) PANGO_SCALE)));
#line 259 "quicklist-rendering.vala"
	pango_layout_context_changed (layout);
#line 263 "quicklist-rendering.vala"
	unity_quicklist_rendering_item_get_text_extents (font, text, &text_width, &text_height);
#line 264 "quicklist-rendering.vala"
	cairo_move_to (cr, ctk_em_to_pixel ((double) UNITY_QUICKLIST_RENDERING_MARGIN), (double) (((float) (h - text_height)) / 2.0f));
#line 267 "quicklist-rendering.vala"
	cairo_set_source_rgba (cr, (double) 0.0f, (double) 0.0f, (double) 0.0f, (double) 0.0f);
#line 268 "quicklist-rendering.vala"
	pango_cairo_show_layout (cr, layout);
#line 489 "quicklist-rendering.c"
	_g_object_unref0 (layout);
	_g_object_unref0 (settings);
	_pango_font_description_free0 (desc);
	_g_object_unref0 (pango_context);
	_g_object_unref0 (screen);
}


#line 90 "quicklist-rendering.vala"
UnityQuicklistRenderingItem* unity_quicklist_rendering_item_construct (GType object_type) {
#line 500 "quicklist-rendering.c"
	UnityQuicklistRenderingItem * self;
#line 90 "quicklist-rendering.vala"
	self = (UnityQuicklistRenderingItem*) g_object_new (object_type, NULL);
#line 504 "quicklist-rendering.c"
	return self;
}


#line 90 "quicklist-rendering.vala"
UnityQuicklistRenderingItem* unity_quicklist_rendering_item_new (void) {
#line 90 "quicklist-rendering.vala"
	return unity_quicklist_rendering_item_construct (UNITY_QUICKLIST_RENDERING_TYPE_ITEM);
#line 513 "quicklist-rendering.c"
}


static void unity_quicklist_rendering_item_class_init (UnityQuicklistRenderingItemClass * klass) {
	unity_quicklist_rendering_item_parent_class = g_type_class_peek_parent (klass);
}


static void unity_quicklist_rendering_item_instance_init (UnityQuicklistRenderingItem * self) {
}


GType unity_quicklist_rendering_item_get_type (void) {
	static volatile gsize unity_quicklist_rendering_item_type_id__volatile = 0;
	if (g_once_init_enter (&unity_quicklist_rendering_item_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (UnityQuicklistRenderingItemClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) unity_quicklist_rendering_item_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (UnityQuicklistRenderingItem), 0, (GInstanceInitFunc) unity_quicklist_rendering_item_instance_init, NULL };
		GType unity_quicklist_rendering_item_type_id;
		unity_quicklist_rendering_item_type_id = g_type_register_static (G_TYPE_OBJECT, "UnityQuicklistRenderingItem", &g_define_type_info, 0);
		g_once_init_leave (&unity_quicklist_rendering_item_type_id__volatile, unity_quicklist_rendering_item_type_id);
	}
	return unity_quicklist_rendering_item_type_id__volatile;
}


#line 274 "quicklist-rendering.vala"
static double _unity_quicklist_rendering_menu_align (double val) {
#line 540 "quicklist-rendering.c"
	double result = 0.0;
	double fract;
#line 277 "quicklist-rendering.vala"
	fract = val - ((gint) val);
#line 279 "quicklist-rendering.vala"
	if (fract != 0.5f) {
#line 547 "quicklist-rendering.c"
		result = (double) (((gint) val) + 0.5f);
#line 280 "quicklist-rendering.vala"
		return result;
#line 551 "quicklist-rendering.c"
	} else {
		result = val;
#line 282 "quicklist-rendering.vala"
		return result;
#line 556 "quicklist-rendering.c"
	}
}


#line 285 "quicklist-rendering.vala"
static void _unity_quicklist_rendering_menu_round_rect_anchor (cairo_t* cr, double aspect, double x, double y, double corner_radius, double width, double height, double anchor_width, double anchor_height, double anchor_x, double anchor_y) {
#line 563 "quicklist-rendering.c"
	double radius;
	double a;
	double b;
	double c;
	double d;
	double e;
	double f;
	double g;
	double h;
	double* _tmp1_;
	gint _p0_size_;
	gint p0_length1;
	double* _tmp0_ = NULL;
	double* p0;
	double* _tmp3_;
	gint _p1_size_;
	gint p1_length1;
	double* _tmp2_ = NULL;
	double* p1;
	double* _tmp5_;
	gint _p2_size_;
	gint p2_length1;
	double* _tmp4_ = NULL;
	double* p2;
	double* _tmp7_;
	gint _p3_size_;
	gint p3_length1;
	double* _tmp6_ = NULL;
	double* p3;
	double* _tmp9_;
	gint _p4_size_;
	gint p4_length1;
	double* _tmp8_ = NULL;
	double* p4;
	double* _tmp11_;
	gint _p5_size_;
	gint p5_length1;
	double* _tmp10_ = NULL;
	double* p5;
	double* _tmp13_;
	gint _p6_size_;
	gint p6_length1;
	double* _tmp12_ = NULL;
	double* p6;
	double* _tmp15_;
	gint _p7_size_;
	gint p7_length1;
	double* _tmp14_ = NULL;
	double* p7;
	double* _tmp17_;
	gint _p8_size_;
	gint p8_length1;
	double* _tmp16_ = NULL;
	double* p8;
	double* _tmp19_;
	gint _p9_size_;
	gint p9_length1;
	double* _tmp18_ = NULL;
	double* p9;
	double* _tmp21_;
	gint _p10_size_;
	gint p10_length1;
	double* _tmp20_ = NULL;
	double* p10;
	double* _tmp23_;
	gint _q0_size_;
	gint q0_length1;
	double* _tmp22_ = NULL;
	double* q0;
	double* _tmp25_;
	gint _q1_size_;
	gint q1_length1;
	double* _tmp24_ = NULL;
	double* q1;
	double* _tmp27_;
	gint _q2_size_;
	gint q2_length1;
	double* _tmp26_ = NULL;
	double* q2;
	double* _tmp29_;
	gint _q3_size_;
	gint q3_length1;
	double* _tmp28_ = NULL;
	double* q3;
#line 285 "quicklist-rendering.vala"
	g_return_if_fail (cr != NULL);
#line 298 "quicklist-rendering.vala"
	radius = corner_radius / aspect;
#line 300 "quicklist-rendering.vala"
	a = _unity_quicklist_rendering_menu_align (x);
#line 301 "quicklist-rendering.vala"
	b = _unity_quicklist_rendering_menu_align (x + radius);
#line 302 "quicklist-rendering.vala"
	c = _unity_quicklist_rendering_menu_align (x + width);
#line 303 "quicklist-rendering.vala"
	d = _unity_quicklist_rendering_menu_align ((x + width) - radius);
#line 304 "quicklist-rendering.vala"
	e = _unity_quicklist_rendering_menu_align (y);
#line 305 "quicklist-rendering.vala"
	f = _unity_quicklist_rendering_menu_align (y + radius);
#line 306 "quicklist-rendering.vala"
	g = _unity_quicklist_rendering_menu_align (y + height);
#line 307 "quicklist-rendering.vala"
	h = _unity_quicklist_rendering_menu_align ((y + height) - radius);
#line 668 "quicklist-rendering.c"
	p0 = (_tmp1_ = (_tmp0_ = g_new0 (double, 2), _tmp0_[0] = b, _tmp0_[1] = e, _tmp0_), p0_length1 = 2, _p0_size_ = p0_length1, _tmp1_);
	p1 = (_tmp3_ = (_tmp2_ = g_new0 (double, 2), _tmp2_[0] = d, _tmp2_[1] = e, _tmp2_), p1_length1 = 2, _p1_size_ = p1_length1, _tmp3_);
	p2 = (_tmp5_ = (_tmp4_ = g_new0 (double, 2), _tmp4_[0] = c, _tmp4_[1] = f, _tmp4_), p2_length1 = 2, _p2_size_ = p2_length1, _tmp5_);
	p3 = (_tmp7_ = (_tmp6_ = g_new0 (double, 2), _tmp6_[0] = c, _tmp6_[1] = h, _tmp6_), p3_length1 = 2, _p3_size_ = p3_length1, _tmp7_);
	p4 = (_tmp9_ = (_tmp8_ = g_new0 (double, 2), _tmp8_[0] = d, _tmp8_[1] = g, _tmp8_), p4_length1 = 2, _p4_size_ = p4_length1, _tmp9_);
	p5 = (_tmp11_ = (_tmp10_ = g_new0 (double, 2), _tmp10_[0] = b, _tmp10_[1] = g, _tmp10_), p5_length1 = 2, _p5_size_ = p5_length1, _tmp11_);
	p6 = (_tmp13_ = (_tmp12_ = g_new0 (double, 2), _tmp12_[0] = a, _tmp12_[1] = h, _tmp12_), p6_length1 = 2, _p6_size_ = p6_length1, _tmp13_);
	p7 = (_tmp15_ = (_tmp14_ = g_new0 (double, 2), _tmp14_[0] = _unity_quicklist_rendering_menu_align (anchor_x + anchor_width), _tmp14_[1] = _unity_quicklist_rendering_menu_align (anchor_y + (anchor_height / 2.0f)), _tmp14_), p7_length1 = 2, _p7_size_ = p7_length1, _tmp15_);
	p8 = (_tmp17_ = (_tmp16_ = g_new0 (double, 2), _tmp16_[0] = _unity_quicklist_rendering_menu_align (anchor_x), _tmp16_[1] = _unity_quicklist_rendering_menu_align (anchor_y), _tmp16_), p8_length1 = 2, _p8_size_ = p8_length1, _tmp17_);
	p9 = (_tmp19_ = (_tmp18_ = g_new0 (double, 2), _tmp18_[0] = _unity_quicklist_rendering_menu_align (anchor_x + anchor_width), _tmp18_[1] = _unity_quicklist_rendering_menu_align (anchor_y - (anchor_height / 2.0f)), _tmp18_), p9_length1 = 2, _p9_size_ = p9_length1, _tmp19_);
	p10 = (_tmp21_ = (_tmp20_ = g_new0 (double, 2), _tmp20_[0] = a, _tmp20_[1] = f, _tmp20_), p10_length1 = 2, _p10_size_ = p10_length1, _tmp21_);
	q0 = (_tmp23_ = (_tmp22_ = g_new0 (double, 2), _tmp22_[0] = a, _tmp22_[1] = e, _tmp22_), q0_length1 = 2, _q0_size_ = q0_length1, _tmp23_);
	q1 = (_tmp25_ = (_tmp24_ = g_new0 (double, 2), _tmp24_[0] = c, _tmp24_[1] = e, _tmp24_), q1_length1 = 2, _q1_size_ = q1_length1, _tmp25_);
	q2 = (_tmp27_ = (_tmp26_ = g_new0 (double, 2), _tmp26_[0] = c, _tmp26_[1] = g, _tmp26_), q2_length1 = 2, _q2_size_ = q2_length1, _tmp27_);
	q3 = (_tmp29_ = (_tmp28_ = g_new0 (double, 2), _tmp28_[0] = a, _tmp28_[1] = g, _tmp28_), q3_length1 = 2, _q3_size_ = q3_length1, _tmp29_);
#line 327 "quicklist-rendering.vala"
	cairo_move_to (cr, p0[0], p0[1]);
#line 330 "quicklist-rendering.vala"
	cairo_line_to (cr, p1[0], p1[1]);
#line 333 "quicklist-rendering.vala"
	cairo_curve_to (cr, q1[0] - (radius * 0.45f), q1[1], q1[0], q1[1] + (radius * 0.45f), p2[0], p2[1]);
#line 341 "quicklist-rendering.vala"
	cairo_line_to (cr, p3[0], p3[1]);
#line 344 "quicklist-rendering.vala"
	cairo_curve_to (cr, q2[0], q2[1] - (radius * 0.45f), q2[0] - (radius * 0.45f), q2[1], p4[0], p4[1]);
#line 352 "quicklist-rendering.vala"
	cairo_line_to (cr, p5[0], p5[1]);
#line 355 "quicklist-rendering.vala"
	cairo_curve_to (cr, q3[0] + (radius * 0.45f), q3[1], q3[0], q3[1] - (radius * 0.45f), p6[0], p6[1]);
#line 363 "quicklist-rendering.vala"
	cairo_line_to (cr, p7[0], p7[1]);
#line 364 "quicklist-rendering.vala"
	cairo_line_to (cr, p8[0], p8[1]);
#line 365 "quicklist-rendering.vala"
	cairo_line_to (cr, p9[0], p9[1]);
#line 368 "quicklist-rendering.vala"
	cairo_line_to (cr, p10[0], p10[1]);
#line 369 "quicklist-rendering.vala"
	cairo_curve_to (cr, q0[0], q0[1] + (radius * 0.45f), q0[0] + (radius * 0.45f), q0[1], p0[0], p0[1]);
#line 708 "quicklist-rendering.c"
	p0 = (g_free (p0), NULL);
	p1 = (g_free (p1), NULL);
	p2 = (g_free (p2), NULL);
	p3 = (g_free (p3), NULL);
	p4 = (g_free (p4), NULL);
	p5 = (g_free (p5), NULL);
	p6 = (g_free (p6), NULL);
	p7 = (g_free (p7), NULL);
	p8 = (g_free (p8), NULL);
	p9 = (g_free (p9), NULL);
	p10 = (g_free (p10), NULL);
	q0 = (g_free (q0), NULL);
	q1 = (g_free (q1), NULL);
	q2 = (g_free (q2), NULL);
	q3 = (g_free (q3), NULL);
}


#line 377 "quicklist-rendering.vala"
static void _unity_quicklist_rendering_menu_draw_mask (cairo_t* cr, gint w, gint h, float anchor_y) {
#line 377 "quicklist-rendering.vala"
	g_return_if_fail (cr != NULL);
#line 383 "quicklist-rendering.vala"
	_unity_quicklist_rendering_menu_round_rect_anchor (cr, (double) 1.0f, UNITY_QUICKLIST_RENDERING_ANCHOR_WIDTH_ABS + ctk_em_to_pixel ((double) UNITY_QUICKLIST_RENDERING_SHADOW_SIZE), ctk_em_to_pixel ((double) UNITY_QUICKLIST_RENDERING_SHADOW_SIZE), (double) UNITY_QUICKLIST_RENDERING_CORNER_RADIUS_ABS, ((double) w) - (UNITY_QUICKLIST_RENDERING_ANCHOR_WIDTH_ABS + ctk_em_to_pixel ((double) (2 * UNITY_QUICKLIST_RENDERING_SHADOW_SIZE))), ((double) h) - ctk_em_to_pixel ((double) (2 * UNITY_QUICKLIST_RENDERING_SHADOW_SIZE)), (double) UNITY_QUICKLIST_RENDERING_ANCHOR_WIDTH_ABS, (double) UNITY_QUICKLIST_RENDERING_ANCHOR_HEIGHT_ABS, ctk_em_to_pixel ((double) UNITY_QUICKLIST_RENDERING_SHADOW_SIZE), (double) anchor_y);
#line 733 "quicklist-rendering.c"
}


#line 396 "quicklist-rendering.vala"
void unity_quicklist_rendering_menu_full_mask (cairo_t* cr, gint w, gint h, float anchor_y) {
#line 396 "quicklist-rendering.vala"
	g_return_if_fail (cr != NULL);
#line 403 "quicklist-rendering.vala"
	cairo_set_operator (cr, CAIRO_OPERATOR_CLEAR);
#line 404 "quicklist-rendering.vala"
	cairo_paint (cr);
#line 405 "quicklist-rendering.vala"
	cairo_set_operator (cr, CAIRO_OPERATOR_SOURCE);
#line 406 "quicklist-rendering.vala"
	cairo_set_source_rgba (cr, (double) 1.0f, (double) 1.0f, (double) 1.0f, (double) 1.0f);
#line 407 "quicklist-rendering.vala"
	cairo_paint (cr);
#line 751 "quicklist-rendering.c"
}


#line 410 "quicklist-rendering.vala"
void unity_quicklist_rendering_menu_fill_mask (cairo_t* cr, gint w, gint h, float anchor_y) {
#line 410 "quicklist-rendering.vala"
	g_return_if_fail (cr != NULL);
#line 417 "quicklist-rendering.vala"
	cairo_set_operator (cr, CAIRO_OPERATOR_CLEAR);
#line 418 "quicklist-rendering.vala"
	cairo_paint (cr);
#line 421 "quicklist-rendering.vala"
	cairo_set_operator (cr, CAIRO_OPERATOR_SOURCE);
#line 422 "quicklist-rendering.vala"
	cairo_scale (cr, (double) 1.0f, (double) 1.0f);
#line 423 "quicklist-rendering.vala"
	cairo_set_source_rgba (cr, (double) 1.0f, (double) 1.0f, (double) 1.0f, (double) 1.0f);
#line 426 "quicklist-rendering.vala"
	_unity_quicklist_rendering_menu_draw_mask (cr, w, h, anchor_y);
#line 427 "quicklist-rendering.vala"
	cairo_fill (cr);
#line 773 "quicklist-rendering.c"
}


#line 430 "quicklist-rendering.vala"
void unity_quicklist_rendering_menu_background (cairo_t* cr, gint w, gint h, float anchor_y) {
#line 779 "quicklist-rendering.c"
	cairo_surface_t* dots;
	cairo_t* cr_dots;
	cairo_pattern_t* dot_pattern;
	cairo_pattern_t* hl_pattern;
	cairo_pattern_t* _tmp0_;
	cairo_pattern_t* _tmp1_;
#line 430 "quicklist-rendering.vala"
	g_return_if_fail (cr != NULL);
#line 436 "quicklist-rendering.vala"
	dots = cairo_image_surface_create (CAIRO_FORMAT_ARGB32, 4, 4);
#line 437 "quicklist-rendering.vala"
	cr_dots = cairo_create (dots);
#line 792 "quicklist-rendering.c"
	dot_pattern = NULL;
	hl_pattern = NULL;
#line 442 "quicklist-rendering.vala"
	cairo_set_operator (cr, CAIRO_OPERATOR_CLEAR);
#line 443 "quicklist-rendering.vala"
	cairo_paint (cr);
#line 446 "quicklist-rendering.vala"
	cairo_set_operator (cr, CAIRO_OPERATOR_OVER);
#line 447 "quicklist-rendering.vala"
	cairo_scale (cr, (double) 1.0f, (double) 1.0f);
#line 448 "quicklist-rendering.vala"
	cairo_set_source_rgba (cr, (double) 0.0f, (double) 0.0f, (double) 0.0f, (double) 0.48f);
#line 451 "quicklist-rendering.vala"
	_unity_quicklist_rendering_menu_draw_mask (cr, w, h, anchor_y);
#line 452 "quicklist-rendering.vala"
	cairo_fill (cr);
#line 453 "quicklist-rendering.vala"
	ctk_surface_blur (cairo_get_target (cr), (guint) ((gint) ctk_em_to_pixel ((double) (UNITY_QUICKLIST_RENDERING_SHADOW_SIZE / 2))));
#line 456 "quicklist-rendering.vala"
	cairo_set_operator (cr, CAIRO_OPERATOR_CLEAR);
#line 457 "quicklist-rendering.vala"
	_unity_quicklist_rendering_menu_draw_mask (cr, w, h, anchor_y);
#line 458 "quicklist-rendering.vala"
	cairo_fill (cr);
#line 461 "quicklist-rendering.vala"
	cairo_set_operator (cr, CAIRO_OPERATOR_OVER);
#line 462 "quicklist-rendering.vala"
	cairo_scale (cr, (double) 1.0f, (double) 1.0f);
#line 463 "quicklist-rendering.vala"
	cairo_set_source_rgba (cr, (double) 0.0f, (double) 0.0f, (double) 0.0f, (double) 0.7f);
#line 464 "quicklist-rendering.vala"
	_unity_quicklist_rendering_menu_draw_mask (cr, w, h, anchor_y);
#line 465 "quicklist-rendering.vala"
	cairo_fill (cr);
#line 468 "quicklist-rendering.vala"
	cairo_set_operator (cr_dots, CAIRO_OPERATOR_CLEAR);
#line 469 "quicklist-rendering.vala"
	cairo_paint (cr_dots);
#line 470 "quicklist-rendering.vala"
	cairo_scale (cr_dots, (double) 1.0f, (double) 1.0f);
#line 471 "quicklist-rendering.vala"
	cairo_set_operator (cr_dots, CAIRO_OPERATOR_OVER);
#line 472 "quicklist-rendering.vala"
	cairo_set_source_rgba (cr_dots, (double) 1.0f, (double) 1.0f, (double) 1.0f, (double) 0.15f);
#line 473 "quicklist-rendering.vala"
	cairo_rectangle (cr_dots, (double) 0.0f, (double) 0.0f, (double) 1.0f, (double) 1.0f);
#line 474 "quicklist-rendering.vala"
	cairo_fill (cr_dots);
#line 475 "quicklist-rendering.vala"
	cairo_rectangle (cr_dots, (double) 2.0f, (double) 2.0f, (double) 1.0f, (double) 1.0f);
#line 476 "quicklist-rendering.vala"
	cairo_fill (cr_dots);
#line 477 "quicklist-rendering.vala"
	dot_pattern = (_tmp0_ = cairo_pattern_create_for_surface (dots), _cairo_pattern_destroy0 (dot_pattern), _tmp0_);
#line 478 "quicklist-rendering.vala"
	cairo_set_operator (cr, CAIRO_OPERATOR_OVER);
#line 479 "quicklist-rendering.vala"
	cairo_set_source (cr, dot_pattern);
#line 480 "quicklist-rendering.vala"
	cairo_pattern_set_extend (dot_pattern, CAIRO_EXTEND_REPEAT);
#line 481 "quicklist-rendering.vala"
	_unity_quicklist_rendering_menu_draw_mask (cr, w, h, anchor_y);
#line 482 "quicklist-rendering.vala"
	cairo_fill (cr);
#line 485 "quicklist-rendering.vala"
	cairo_set_operator (cr, CAIRO_OPERATOR_OVER);
#line 486 "quicklist-rendering.vala"
	hl_pattern = (_tmp1_ = cairo_pattern_create_radial (((double) w) / 2.0f, ctk_em_to_pixel ((double) UNITY_QUICKLIST_RENDERING_BORDER) - 15.0f, (double) 0.0f, ((double) w) / 2.0f, ctk_em_to_pixel ((double) UNITY_QUICKLIST_RENDERING_BORDER) - 15.0f, (((double) w) / 2.0f) + 20.0f), _cairo_pattern_destroy0 (hl_pattern), _tmp1_);
#line 492 "quicklist-rendering.vala"
	cairo_pattern_add_color_stop_rgba (hl_pattern, (double) 0.0f, (double) 1.0f, (double) 1.0f, (double) 1.0f, (double) 0.65f);
#line 493 "quicklist-rendering.vala"
	cairo_pattern_add_color_stop_rgba (hl_pattern, (double) 1.0f, (double) 1.0f, (double) 1.0f, (double) 1.0f, (double) 0.0f);
#line 494 "quicklist-rendering.vala"
	cairo_set_source (cr, hl_pattern);
#line 495 "quicklist-rendering.vala"
	_unity_quicklist_rendering_menu_draw_mask (cr, w, h, anchor_y);
#line 496 "quicklist-rendering.vala"
	cairo_fill (cr);
#line 499 "quicklist-rendering.vala"
	cairo_set_operator (cr, CAIRO_OPERATOR_SOURCE);
#line 500 "quicklist-rendering.vala"
	cairo_set_line_width (cr, (double) UNITY_QUICKLIST_RENDERING_LINE_WIDTH_ABS);
#line 501 "quicklist-rendering.vala"
	cairo_set_source_rgba (cr, (double) 1.0f, (double) 1.0f, (double) 1.0f, (double) 0.75f);
#line 502 "quicklist-rendering.vala"
	_unity_quicklist_rendering_menu_draw_mask (cr, w, h, anchor_y);
#line 503 "quicklist-rendering.vala"
	cairo_stroke (cr);
#line 881 "quicklist-rendering.c"
	_cairo_surface_destroy0 (dots);
	_cairo_destroy0 (cr_dots);
	_cairo_pattern_destroy0 (dot_pattern);
	_cairo_pattern_destroy0 (hl_pattern);
}


#line 272 "quicklist-rendering.vala"
UnityQuicklistRenderingMenu* unity_quicklist_rendering_menu_construct (GType object_type) {
#line 891 "quicklist-rendering.c"
	UnityQuicklistRenderingMenu * self;
#line 272 "quicklist-rendering.vala"
	self = (UnityQuicklistRenderingMenu*) g_object_new (object_type, NULL);
#line 895 "quicklist-rendering.c"
	return self;
}


#line 272 "quicklist-rendering.vala"
UnityQuicklistRenderingMenu* unity_quicklist_rendering_menu_new (void) {
#line 272 "quicklist-rendering.vala"
	return unity_quicklist_rendering_menu_construct (UNITY_QUICKLIST_RENDERING_TYPE_MENU);
#line 904 "quicklist-rendering.c"
}


static void unity_quicklist_rendering_menu_class_init (UnityQuicklistRenderingMenuClass * klass) {
	unity_quicklist_rendering_menu_parent_class = g_type_class_peek_parent (klass);
}


static void unity_quicklist_rendering_menu_instance_init (UnityQuicklistRenderingMenu * self) {
}


GType unity_quicklist_rendering_menu_get_type (void) {
	static volatile gsize unity_quicklist_rendering_menu_type_id__volatile = 0;
	if (g_once_init_enter (&unity_quicklist_rendering_menu_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (UnityQuicklistRenderingMenuClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) unity_quicklist_rendering_menu_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (UnityQuicklistRenderingMenu), 0, (GInstanceInitFunc) unity_quicklist_rendering_menu_instance_init, NULL };
		GType unity_quicklist_rendering_menu_type_id;
		unity_quicklist_rendering_menu_type_id = g_type_register_static (G_TYPE_OBJECT, "UnityQuicklistRenderingMenu", &g_define_type_info, 0);
		g_once_init_leave (&unity_quicklist_rendering_menu_type_id__volatile, unity_quicklist_rendering_menu_type_id);
	}
	return unity_quicklist_rendering_menu_type_id__volatile;
}




