/* quicklist-view.c generated by valac, the Vala compiler
 * generated from quicklist-view.vala, do not modify */

/* -*- Mode: vala; indent-tabs-mode: nil; c-basic-offset: 2; tab-width: 2 -*- */
/*
 * Copyright (C) 2009 Canonical Ltd
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Authored by Gordon Allott <gord.allott@canonical.com>,
 *             Mirco "MacSlow" Müller <mirco.mueller@canonical.com>
 *
 */

#include <glib.h>
#include <glib-object.h>
#include <clutk/clutk.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>
#include <cairo.h>
#include <pango/pangocairo.h>
#include <pango/pango.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>
#include <clutter/clutter.h>


#define UNITY_QUICKLAUNCHER_TYPE_QUICKLIST_MENU_ITEM (unity_quicklauncher_quicklist_menu_item_get_type ())
#define UNITY_QUICKLAUNCHER_QUICKLIST_MENU_ITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), UNITY_QUICKLAUNCHER_TYPE_QUICKLIST_MENU_ITEM, UnityQuicklauncherQuicklistMenuItem))
#define UNITY_QUICKLAUNCHER_QUICKLIST_MENU_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), UNITY_QUICKLAUNCHER_TYPE_QUICKLIST_MENU_ITEM, UnityQuicklauncherQuicklistMenuItemClass))
#define UNITY_QUICKLAUNCHER_IS_QUICKLIST_MENU_ITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), UNITY_QUICKLAUNCHER_TYPE_QUICKLIST_MENU_ITEM))
#define UNITY_QUICKLAUNCHER_IS_QUICKLIST_MENU_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), UNITY_QUICKLAUNCHER_TYPE_QUICKLIST_MENU_ITEM))
#define UNITY_QUICKLAUNCHER_QUICKLIST_MENU_ITEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), UNITY_QUICKLAUNCHER_TYPE_QUICKLIST_MENU_ITEM, UnityQuicklauncherQuicklistMenuItemClass))

typedef struct _UnityQuicklauncherQuicklistMenuItem UnityQuicklauncherQuicklistMenuItem;
typedef struct _UnityQuicklauncherQuicklistMenuItemClass UnityQuicklauncherQuicklistMenuItemClass;
typedef struct _UnityQuicklauncherQuicklistMenuItemPrivate UnityQuicklauncherQuicklistMenuItemPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _cairo_surface_destroy0(var) ((var == NULL) ? NULL : (var = (cairo_surface_destroy (var), NULL)))
#define _cairo_destroy0(var) ((var == NULL) ? NULL : (var = (cairo_destroy (var), NULL)))
#define _pango_font_description_free0(var) ((var == NULL) ? NULL : (var = (pango_font_description_free (var), NULL)))

#define UNITY_QUICKLAUNCHER_TYPE_QUICKLIST_MENU (unity_quicklauncher_quicklist_menu_get_type ())
#define UNITY_QUICKLAUNCHER_QUICKLIST_MENU(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), UNITY_QUICKLAUNCHER_TYPE_QUICKLIST_MENU, UnityQuicklauncherQuicklistMenu))
#define UNITY_QUICKLAUNCHER_QUICKLIST_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), UNITY_QUICKLAUNCHER_TYPE_QUICKLIST_MENU, UnityQuicklauncherQuicklistMenuClass))
#define UNITY_QUICKLAUNCHER_IS_QUICKLIST_MENU(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), UNITY_QUICKLAUNCHER_TYPE_QUICKLIST_MENU))
#define UNITY_QUICKLAUNCHER_IS_QUICKLIST_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), UNITY_QUICKLAUNCHER_TYPE_QUICKLIST_MENU))
#define UNITY_QUICKLAUNCHER_QUICKLIST_MENU_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), UNITY_QUICKLAUNCHER_TYPE_QUICKLIST_MENU, UnityQuicklauncherQuicklistMenuClass))

typedef struct _UnityQuicklauncherQuicklistMenu UnityQuicklauncherQuicklistMenu;
typedef struct _UnityQuicklauncherQuicklistMenuClass UnityQuicklauncherQuicklistMenuClass;
typedef struct _UnityQuicklauncherQuicklistMenuPrivate UnityQuicklauncherQuicklistMenuPrivate;
#define _cairo_pattern_destroy0(var) ((var == NULL) ? NULL : (var = (cairo_pattern_destroy (var), NULL)))

struct _UnityQuicklauncherQuicklistMenuItem {
	CtkMenuItem parent_instance;
	UnityQuicklauncherQuicklistMenuItemPrivate * priv;
};

struct _UnityQuicklauncherQuicklistMenuItemClass {
	CtkMenuItemClass parent_class;
};

struct _UnityQuicklauncherQuicklistMenuItemPrivate {
	CtkLayerActor* item_background;
	gint old_width;
	gint old_height;
	char* old_label;
};

struct _UnityQuicklauncherQuicklistMenu {
	CtkMenu parent_instance;
	UnityQuicklauncherQuicklistMenuPrivate * priv;
};

struct _UnityQuicklauncherQuicklistMenuClass {
	CtkMenuClass parent_class;
};

struct _UnityQuicklauncherQuicklistMenuPrivate {
	CtkLayerActor* ql_background;
	gint old_width;
	gint old_height;
};


static gpointer unity_quicklauncher_quicklist_menu_item_parent_class = NULL;
static gpointer unity_quicklauncher_quicklist_menu_parent_class = NULL;

#define UNITY_QUICKLAUNCHER_LINE_WIDTH 0.083f
#define UNITY_QUICKLAUNCHER_TEXT_HEIGHT 1.0f
#define UNITY_QUICKLAUNCHER_MAX_TEXT_WIDTH 15.0f
#define UNITY_QUICKLAUNCHER_GAP 0.25f
#define UNITY_QUICKLAUNCHER_MARGIN 0.5f
#define UNITY_QUICKLAUNCHER_BORDER 0.25f
#define UNITY_QUICKLAUNCHER_CORNER_RADIUS 0.3f
#define UNITY_QUICKLAUNCHER_ITEM_HEIGHT 2.0f
#define UNITY_QUICKLAUNCHER_ITEM_CORNER_RADIUS 0.3f
#define UNITY_QUICKLAUNCHER_ANCHOR_HEIGHT 1.5f
#define UNITY_QUICKLAUNCHER_ANCHOR_WIDTH 0.75f
GType unity_quicklauncher_quicklist_menu_item_get_type (void);
#define UNITY_QUICKLAUNCHER_QUICKLIST_MENU_ITEM_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), UNITY_QUICKLAUNCHER_TYPE_QUICKLIST_MENU_ITEM, UnityQuicklauncherQuicklistMenuItemPrivate))
enum  {
	UNITY_QUICKLAUNCHER_QUICKLIST_MENU_ITEM_DUMMY_PROPERTY
};
static void _unity_quicklauncher_quicklist_menu_item_round_rect (UnityQuicklauncherQuicklistMenuItem* self, cairo_t* cr, double aspect, double x, double y, double corner_radius, double width, double height);
static void _unity_quicklauncher_quicklist_menu_item_get_text_extents (UnityQuicklauncherQuicklistMenuItem* self, gint* width, gint* height);
static void _unity_quicklauncher_quicklist_menu_item_normal_mask (UnityQuicklauncherQuicklistMenuItem* self, cairo_t* cr, gint w, gint h, const char* label);
static void _unity_quicklauncher_quicklist_menu_item_selected_mask (UnityQuicklauncherQuicklistMenuItem* self, cairo_t* cr, gint w, gint h, const char* label);
static void unity_quicklauncher_quicklist_menu_item_real_paint (ClutterActor* base);
static void unity_quicklauncher_quicklist_menu_item_real_get_preferred_height (ClutterActor* base, float for_width, float* min_height_p, float* natural_height_p);
static void unity_quicklauncher_quicklist_menu_item_real_get_preferred_width (ClutterActor* base, float for_height, float* min_width_p, float* natural_width_p);
static void unity_quicklauncher_quicklist_menu_item_real_allocate (ClutterActor* base, const ClutterActorBox* box, ClutterAllocationFlags flags);
static gboolean _unity_quicklauncher_quicklist_menu_item_on_enter (UnityQuicklauncherQuicklistMenuItem* self, ClutterEvent* event);
static gboolean _unity_quicklauncher_quicklist_menu_item_on_leave (UnityQuicklauncherQuicklistMenuItem* self, ClutterEvent* event);
static void _unity_quicklauncher_quicklist_menu_item_on_label_changed (UnityQuicklauncherQuicklistMenuItem* self);
UnityQuicklauncherQuicklistMenuItem* unity_quicklauncher_quicklist_menu_item_new (const char* label);
UnityQuicklauncherQuicklistMenuItem* unity_quicklauncher_quicklist_menu_item_construct (GType object_type, const char* label);
static void __unity_quicklauncher_quicklist_menu_item_on_label_changed_g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static gboolean __unity_quicklauncher_quicklist_menu_item_on_enter_clutter_actor_enter_event (ClutterActor* _sender, ClutterEvent* event, gpointer self);
static gboolean __unity_quicklauncher_quicklist_menu_item_on_leave_clutter_actor_leave_event (ClutterActor* _sender, ClutterEvent* event, gpointer self);
static GObject * unity_quicklauncher_quicklist_menu_item_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void unity_quicklauncher_quicklist_menu_item_finalize (GObject* obj);
GType unity_quicklauncher_quicklist_menu_get_type (void);
#define UNITY_QUICKLAUNCHER_QUICKLIST_MENU_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), UNITY_QUICKLAUNCHER_TYPE_QUICKLIST_MENU, UnityQuicklauncherQuicklistMenuPrivate))
enum  {
	UNITY_QUICKLAUNCHER_QUICKLIST_MENU_DUMMY_PROPERTY
};
static void _unity_quicklauncher_quicklist_menu_round_rect_anchor (UnityQuicklauncherQuicklistMenu* self, cairo_t* cr, double aspect, double x, double y, double corner_radius, double width, double height, double anchor_width, double anchor_height, double anchor_x, double anchor_y);
static void _unity_quicklauncher_quicklist_menu_outline_mask (UnityQuicklauncherQuicklistMenu* self, cairo_t* cr, gint w, gint h, float anchor_y);
static void _unity_quicklauncher_quicklist_menu_fill_mask (UnityQuicklauncherQuicklistMenu* self, cairo_t* cr, gint w, gint h, float anchor_y);
static void _unity_quicklauncher_quicklist_menu_negative_mask (UnityQuicklauncherQuicklistMenu* self, cairo_t* cr, gint w, gint h, float anchor_y);
static void _unity_quicklauncher_quicklist_menu_dotted_bg (UnityQuicklauncherQuicklistMenu* self, cairo_t* cr, gint w, gint h, float anchor_y);
static void _unity_quicklauncher_quicklist_menu_highlight_bg (UnityQuicklauncherQuicklistMenu* self, cairo_t* cr, gint w, gint h, float anchor_y);
static void unity_quicklauncher_quicklist_menu_real_allocate (ClutterActor* base, const ClutterActorBox* box, ClutterAllocationFlags flags);
UnityQuicklauncherQuicklistMenu* unity_quicklauncher_quicklist_menu_new (void);
UnityQuicklauncherQuicklistMenu* unity_quicklauncher_quicklist_menu_construct (GType object_type);
static GObject * unity_quicklauncher_quicklist_menu_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void unity_quicklauncher_quicklist_menu_finalize (GObject* obj);
static int _vala_strcmp0 (const char * str1, const char * str2);



#line 44 "quicklist-view.vala"
static void _unity_quicklauncher_quicklist_menu_item_round_rect (UnityQuicklauncherQuicklistMenuItem* self, cairo_t* cr, double aspect, double x, double y, double corner_radius, double width, double height) {
#line 160 "quicklist-view.c"
	double radius;
#line 44 "quicklist-view.vala"
	g_return_if_fail (self != NULL);
#line 44 "quicklist-view.vala"
	g_return_if_fail (cr != NULL);
#line 53 "quicklist-view.vala"
	radius = corner_radius / aspect;
#line 56 "quicklist-view.vala"
	cairo_move_to (cr, x + radius, y);
#line 59 "quicklist-view.vala"
	cairo_line_to (cr, (x + width) - radius, y);
#line 62 "quicklist-view.vala"
	cairo_arc (cr, (x + width) - radius, y + radius, radius, ((-90.0f) * G_PI) / 180.0f, (0.0f * G_PI) / 180.0f);
#line 69 "quicklist-view.vala"
	cairo_line_to (cr, x + width, (y + height) - radius);
#line 72 "quicklist-view.vala"
	cairo_arc (cr, (x + width) - radius, (y + height) - radius, radius, (0.0f * G_PI) / 180.0f, (90.0f * G_PI) / 180.0f);
#line 79 "quicklist-view.vala"
	cairo_line_to (cr, x + radius, y + height);
#line 82 "quicklist-view.vala"
	cairo_arc (cr, x + radius, (y + height) - radius, radius, (90.0f * G_PI) / 180.0f, (180.0f * G_PI) / 180.0f);
#line 89 "quicklist-view.vala"
	cairo_arc (cr, x + radius, y + radius, radius, (180.0f * G_PI) / 180.0f, (270.0f * G_PI) / 180.0f);
#line 184 "quicklist-view.c"
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


#line 96 "quicklist-view.vala"
static void _unity_quicklauncher_quicklist_menu_item_get_text_extents (UnityQuicklauncherQuicklistMenuItem* self, gint* width, gint* height) {
#line 195 "quicklist-view.c"
	cairo_surface_t* dummy_surf;
	cairo_t* dummy_cr;
	PangoLayout* layout;
	GtkSettings* settings;
	char* _tmp0_ = NULL;
	char* face;
	PangoFontDescription* desc;
	PangoContext* pango_context;
	GdkScreen* screen;
	gint _tmp1_;
	PangoRectangle log_rect = {0};
#line 96 "quicklist-view.vala"
	g_return_if_fail (self != NULL);
#line 100 "quicklist-view.vala"
	dummy_surf = cairo_image_surface_create (CAIRO_FORMAT_A1, 1, 1);
#line 101 "quicklist-view.vala"
	dummy_cr = cairo_create (dummy_surf);
#line 102 "quicklist-view.vala"
	layout = pango_cairo_create_layout (dummy_cr);
#line 103 "quicklist-view.vala"
	settings = _g_object_ref0 (gtk_settings_get_default ());
#line 104 "quicklist-view.vala"
	face = (g_object_get (settings, "gtk-font-name", &_tmp0_, NULL), _tmp0_);
#line 105 "quicklist-view.vala"
	desc = pango_font_description_from_string (face);
#line 107 "quicklist-view.vala"
	pango_font_description_set_weight (desc, PANGO_WEIGHT_NORMAL);
#line 108 "quicklist-view.vala"
	pango_layout_set_font_description (layout, desc);
#line 109 "quicklist-view.vala"
	pango_layout_set_wrap (layout, PANGO_WRAP_WORD_CHAR);
#line 110 "quicklist-view.vala"
	pango_layout_set_ellipsize (layout, PANGO_ELLIPSIZE_END);
#line 111 "quicklist-view.vala"
	pango_layout_set_text (layout, ctk_menu_item_get_label ((CtkMenuItem*) self), -1);
#line 112 "quicklist-view.vala"
	pango_context = _g_object_ref0 (pango_layout_get_context (layout));
#line 113 "quicklist-view.vala"
	screen = _g_object_ref0 (gdk_screen_get_default ());
#line 114 "quicklist-view.vala"
	pango_cairo_context_set_font_options (pango_context, gdk_screen_get_font_options (screen));
#line 116 "quicklist-view.vala"
	pango_cairo_context_set_resolution (pango_context, (double) (((float) (g_object_get (settings, "gtk-xft-dpi", &_tmp1_, NULL), _tmp1_)) / ((float) PANGO_SCALE)));
#line 119 "quicklist-view.vala"
	pango_layout_context_changed (layout);
#line 121 "quicklist-view.vala"
	pango_layout_get_extents (layout, NULL, &log_rect);
#line 122 "quicklist-view.vala"
	*width = log_rect.width / PANGO_SCALE;
#line 123 "quicklist-view.vala"
	*height = log_rect.height / PANGO_SCALE;
#line 247 "quicklist-view.c"
	_cairo_surface_destroy0 (dummy_surf);
	_cairo_destroy0 (dummy_cr);
	_g_object_unref0 (layout);
	_g_object_unref0 (settings);
	_g_free0 (face);
	_pango_font_description_free0 (desc);
	_g_object_unref0 (pango_context);
	_g_object_unref0 (screen);
}


#line 126 "quicklist-view.vala"
static void _unity_quicklauncher_quicklist_menu_item_normal_mask (UnityQuicklauncherQuicklistMenuItem* self, cairo_t* cr, gint w, gint h, const char* label) {
#line 261 "quicklist-view.c"
	PangoLayout* layout;
	GtkSettings* settings;
	char* _tmp0_ = NULL;
	char* font_face;
	PangoFontDescription* desc;
	PangoContext* pango_context;
	GdkScreen* screen;
	gint _tmp1_;
	gint text_width = 0;
	gint text_height = 0;
#line 126 "quicklist-view.vala"
	g_return_if_fail (self != NULL);
#line 126 "quicklist-view.vala"
	g_return_if_fail (cr != NULL);
#line 126 "quicklist-view.vala"
	g_return_if_fail (label != NULL);
#line 132 "quicklist-view.vala"
	cairo_set_operator (cr, CAIRO_OPERATOR_CLEAR);
#line 133 "quicklist-view.vala"
	cairo_paint (cr);
#line 136 "quicklist-view.vala"
	cairo_set_operator (cr, CAIRO_OPERATOR_SOURCE);
#line 137 "quicklist-view.vala"
	cairo_scale (cr, (double) 1.0f, (double) 1.0f);
#line 138 "quicklist-view.vala"
	cairo_set_source_rgba (cr, (double) 1.0f, (double) 1.0f, (double) 1.0f, (double) 1.0f);
#line 140 "quicklist-view.vala"
	layout = pango_cairo_create_layout (cr);
#line 141 "quicklist-view.vala"
	settings = _g_object_ref0 (gtk_settings_get_default ());
#line 142 "quicklist-view.vala"
	font_face = (g_object_get (settings, "gtk-font-name", &_tmp0_, NULL), _tmp0_);
#line 143 "quicklist-view.vala"
	desc = pango_font_description_from_string (font_face);
#line 144 "quicklist-view.vala"
	pango_font_description_set_weight (desc, PANGO_WEIGHT_NORMAL);
#line 145 "quicklist-view.vala"
	pango_layout_set_font_description (layout, desc);
#line 146 "quicklist-view.vala"
	pango_layout_set_wrap (layout, PANGO_WRAP_WORD_CHAR);
#line 147 "quicklist-view.vala"
	pango_layout_set_ellipsize (layout, PANGO_ELLIPSIZE_END);
#line 148 "quicklist-view.vala"
	pango_layout_set_text (layout, label, -1);
#line 149 "quicklist-view.vala"
	pango_context = _g_object_ref0 (pango_layout_get_context (layout));
#line 150 "quicklist-view.vala"
	screen = _g_object_ref0 (gdk_screen_get_default ());
#line 151 "quicklist-view.vala"
	pango_cairo_context_set_font_options (pango_context, gdk_screen_get_font_options (screen));
#line 153 "quicklist-view.vala"
	pango_cairo_context_set_resolution (pango_context, (double) (((float) (g_object_get (settings, "gtk-xft-dpi", &_tmp1_, NULL), _tmp1_)) / ((float) PANGO_SCALE)));
#line 156 "quicklist-view.vala"
	pango_layout_context_changed (layout);
#line 160 "quicklist-view.vala"
	_unity_quicklauncher_quicklist_menu_item_get_text_extents (self, &text_width, &text_height);
#line 161 "quicklist-view.vala"
	cairo_move_to (cr, ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_MARGIN), (double) (((float) (h - text_height)) / 2.0f));
#line 164 "quicklist-view.vala"
	pango_cairo_show_layout (cr, layout);
#line 322 "quicklist-view.c"
	_g_object_unref0 (layout);
	_g_object_unref0 (settings);
	_g_free0 (font_face);
	_pango_font_description_free0 (desc);
	_g_object_unref0 (pango_context);
	_g_object_unref0 (screen);
}


#line 167 "quicklist-view.vala"
static void _unity_quicklauncher_quicklist_menu_item_selected_mask (UnityQuicklauncherQuicklistMenuItem* self, cairo_t* cr, gint w, gint h, const char* label) {
#line 334 "quicklist-view.c"
	PangoLayout* layout;
	GtkSettings* settings;
	char* _tmp0_ = NULL;
	char* font_face;
	PangoFontDescription* desc;
	PangoContext* pango_context;
	GdkScreen* screen;
	gint _tmp1_;
	gint text_width = 0;
	gint text_height = 0;
#line 167 "quicklist-view.vala"
	g_return_if_fail (self != NULL);
#line 167 "quicklist-view.vala"
	g_return_if_fail (cr != NULL);
#line 167 "quicklist-view.vala"
	g_return_if_fail (label != NULL);
#line 173 "quicklist-view.vala"
	cairo_set_operator (cr, CAIRO_OPERATOR_CLEAR);
#line 174 "quicklist-view.vala"
	cairo_paint (cr);
#line 177 "quicklist-view.vala"
	cairo_set_operator (cr, CAIRO_OPERATOR_SOURCE);
#line 178 "quicklist-view.vala"
	cairo_scale (cr, (double) 1.0f, (double) 1.0f);
#line 179 "quicklist-view.vala"
	cairo_set_source_rgba (cr, (double) 1.0f, (double) 1.0f, (double) 1.0f, (double) 1.0f);
#line 182 "quicklist-view.vala"
	_unity_quicklauncher_quicklist_menu_item_round_rect (self, cr, (double) 1.0f, (double) 0.5f, (double) 0.5f, ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_ITEM_CORNER_RADIUS), (double) (w - 1.0f), (double) (h - 1.0f));
#line 189 "quicklist-view.vala"
	cairo_fill (cr);
#line 192 "quicklist-view.vala"
	layout = pango_cairo_create_layout (cr);
#line 193 "quicklist-view.vala"
	settings = _g_object_ref0 (gtk_settings_get_default ());
#line 194 "quicklist-view.vala"
	font_face = (g_object_get (settings, "gtk-font-name", &_tmp0_, NULL), _tmp0_);
#line 195 "quicklist-view.vala"
	desc = pango_font_description_from_string (font_face);
#line 196 "quicklist-view.vala"
	pango_font_description_set_weight (desc, PANGO_WEIGHT_NORMAL);
#line 197 "quicklist-view.vala"
	pango_layout_set_font_description (layout, desc);
#line 198 "quicklist-view.vala"
	pango_layout_set_wrap (layout, PANGO_WRAP_WORD_CHAR);
#line 199 "quicklist-view.vala"
	pango_layout_set_ellipsize (layout, PANGO_ELLIPSIZE_END);
#line 200 "quicklist-view.vala"
	pango_layout_set_text (layout, label, -1);
#line 201 "quicklist-view.vala"
	pango_context = _g_object_ref0 (pango_layout_get_context (layout));
#line 202 "quicklist-view.vala"
	screen = _g_object_ref0 (gdk_screen_get_default ());
#line 203 "quicklist-view.vala"
	pango_cairo_context_set_font_options (pango_context, gdk_screen_get_font_options (screen));
#line 205 "quicklist-view.vala"
	pango_cairo_context_set_resolution (pango_context, (double) (((float) (g_object_get (settings, "gtk-xft-dpi", &_tmp1_, NULL), _tmp1_)) / ((float) PANGO_SCALE)));
#line 208 "quicklist-view.vala"
	pango_layout_context_changed (layout);
#line 212 "quicklist-view.vala"
	_unity_quicklauncher_quicklist_menu_item_get_text_extents (self, &text_width, &text_height);
#line 213 "quicklist-view.vala"
	cairo_move_to (cr, ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_MARGIN), (double) (((float) (h - text_height)) / 2.0f));
#line 216 "quicklist-view.vala"
	cairo_set_source_rgba (cr, (double) 0.0f, (double) 0.0f, (double) 0.0f, (double) 0.0f);
#line 217 "quicklist-view.vala"
	pango_cairo_show_layout (cr, layout);
#line 401 "quicklist-view.c"
	_g_object_unref0 (layout);
	_g_object_unref0 (settings);
	_g_free0 (font_face);
	_pango_font_description_free0 (desc);
	_g_object_unref0 (pango_context);
	_g_object_unref0 (screen);
}


#line 220 "quicklist-view.vala"
static void unity_quicklauncher_quicklist_menu_item_real_paint (ClutterActor* base) {
#line 413 "quicklist-view.c"
	UnityQuicklauncherQuicklistMenuItem * self;
	self = (UnityQuicklauncherQuicklistMenuItem*) base;
#line 223 "quicklist-view.vala"
	clutter_actor_paint ((ClutterActor*) self->priv->item_background);
#line 418 "quicklist-view.c"
}


#line 226 "quicklist-view.vala"
static void unity_quicklauncher_quicklist_menu_item_real_get_preferred_height (ClutterActor* base, float for_width, float* min_height_p, float* natural_height_p) {
#line 424 "quicklist-view.c"
	UnityQuicklauncherQuicklistMenuItem * self;
	self = (UnityQuicklauncherQuicklistMenuItem*) base;
#line 231 "quicklist-view.vala"
	*min_height_p = (float) ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_ITEM_HEIGHT);
#line 232 "quicklist-view.vala"
	*natural_height_p = *min_height_p;
#line 431 "quicklist-view.c"
}


#line 235 "quicklist-view.vala"
static void unity_quicklauncher_quicklist_menu_item_real_get_preferred_width (ClutterActor* base, float for_height, float* min_width_p, float* natural_width_p) {
#line 437 "quicklist-view.c"
	UnityQuicklauncherQuicklistMenuItem * self;
	gint width = 0;
	gint height = 0;
	self = (UnityQuicklauncherQuicklistMenuItem*) base;
#line 242 "quicklist-view.vala"
	_unity_quicklauncher_quicklist_menu_item_get_text_extents (self, &width, &height);
#line 243 "quicklist-view.vala"
	*min_width_p = ((float) width) + ((float) ctk_em_to_pixel ((double) (2 * UNITY_QUICKLAUNCHER_MARGIN)));
#line 244 "quicklist-view.vala"
	*natural_width_p = *min_width_p;
#line 448 "quicklist-view.c"
}


#line 247 "quicklist-view.vala"
static void unity_quicklauncher_quicklist_menu_item_real_allocate (ClutterActor* base, const ClutterActorBox* box, ClutterAllocationFlags flags) {
#line 454 "quicklist-view.c"
	UnityQuicklauncherQuicklistMenuItem * self;
	gint w = 0;
	gint h = 0;
	ClutterColor _tmp0_ = {0};
	ClutterColor white_color;
	gboolean _tmp1_ = FALSE;
	CtkLayerActor* _tmp2_;
	CtkLayer* normal_layer;
	CtkLayer* selected_layer;
	cairo_surface_t* normal_surf;
	cairo_surface_t* selected_surf;
	cairo_t* normal_cr;
	cairo_t* selected_cr;
	self = (UnityQuicklauncherQuicklistMenuItem*) base;
#line 253 "quicklist-view.vala"
	white_color = (memset (&_tmp0_, 0, sizeof (ClutterColor)), _tmp0_.red = (guint8) 255, _tmp0_.green = (guint8) 255, _tmp0_.blue = (guint8) 255, _tmp0_.alpha = (guint8) 255, _tmp0_);
#line 260 "quicklist-view.vala"
	CLUTTER_ACTOR_CLASS (unity_quicklauncher_quicklist_menu_item_parent_class)->allocate ((ClutterActor*) CTK_MENU_ITEM (self), box, flags);
#line 262 "quicklist-view.vala"
	w = (gint) ((*box).x2 - (*box).x1);
#line 263 "quicklist-view.vala"
	h = (gint) ((*box).y2 - (*box).y1);
#line 267 "quicklist-view.vala"
	if (self->priv->old_width == w) {
#line 267 "quicklist-view.vala"
		_tmp1_ = self->priv->old_height == h;
#line 481 "quicklist-view.c"
	} else {
#line 267 "quicklist-view.vala"
		_tmp1_ = FALSE;
#line 485 "quicklist-view.c"
	}
#line 267 "quicklist-view.vala"
	if (_tmp1_) {
#line 268 "quicklist-view.vala"
		return;
#line 491 "quicklist-view.c"
	}
#line 271 "quicklist-view.vala"
	self->priv->old_width = w;
#line 272 "quicklist-view.vala"
	self->priv->old_height = h;
#line 275 "quicklist-view.vala"
	if (CTK_IS_LAYER_ACTOR (self->priv->item_background)) {
#line 276 "quicklist-view.vala"
		clutter_actor_unparent ((ClutterActor*) self->priv->item_background);
#line 501 "quicklist-view.c"
	}
#line 277 "quicklist-view.vala"
	self->priv->item_background = (_tmp2_ = g_object_ref_sink ((CtkLayerActor*) ctk_layer_actor_new ((guint) w, (guint) h)), _g_object_unref0 (self->priv->item_background), _tmp2_);
#line 279 "quicklist-view.vala"
	normal_layer = ctk_layer_new ((guint) w, (guint) h, CTK_LAYER_REPEAT_NONE, CTK_LAYER_REPEAT_NONE);
#line 283 "quicklist-view.vala"
	selected_layer = ctk_layer_new ((guint) w, (guint) h, CTK_LAYER_REPEAT_NONE, CTK_LAYER_REPEAT_NONE);
#line 288 "quicklist-view.vala"
	normal_surf = cairo_image_surface_create (CAIRO_FORMAT_ARGB32, w, h);
#line 291 "quicklist-view.vala"
	selected_surf = cairo_image_surface_create (CAIRO_FORMAT_ARGB32, w, h);
#line 295 "quicklist-view.vala"
	normal_cr = cairo_create (normal_surf);
#line 296 "quicklist-view.vala"
	selected_cr = cairo_create (selected_surf);
#line 298 "quicklist-view.vala"
	_unity_quicklauncher_quicklist_menu_item_normal_mask (self, normal_cr, w, h, ctk_menu_item_get_label ((CtkMenuItem*) self));
#line 299 "quicklist-view.vala"
	_unity_quicklauncher_quicklist_menu_item_selected_mask (self, selected_cr, w, h, ctk_menu_item_get_label ((CtkMenuItem*) self));
#line 304 "quicklist-view.vala"
	ctk_layer_set_mask_from_surface (normal_layer, normal_surf);
#line 305 "quicklist-view.vala"
	ctk_layer_set_color (normal_layer, &white_color);
#line 307 "quicklist-view.vala"
	ctk_layer_set_mask_from_surface (selected_layer, selected_surf);
#line 308 "quicklist-view.vala"
	ctk_layer_set_color (selected_layer, &white_color);
#line 310 "quicklist-view.vala"
	ctk_layer_actor_add_layer (self->priv->item_background, normal_layer);
#line 311 "quicklist-view.vala"
	ctk_layer_actor_add_layer (self->priv->item_background, selected_layer);
#line 313 "quicklist-view.vala"
	ctk_layer_set_enabled (ctk_layer_actor_get_layer (self->priv->item_background, (guint) 0), TRUE);
#line 314 "quicklist-view.vala"
	ctk_layer_set_enabled (ctk_layer_actor_get_layer (self->priv->item_background, (guint) 1), FALSE);
#line 315 "quicklist-view.vala"
	clutter_actor_queue_redraw ((ClutterActor*) self->priv->item_background);
#line 317 "quicklist-view.vala"
	clutter_actor_set_parent ((ClutterActor*) self->priv->item_background, (ClutterActor*) self);
#line 318 "quicklist-view.vala"
	clutter_actor_map ((ClutterActor*) self->priv->item_background);
#line 319 "quicklist-view.vala"
	clutter_actor_show ((ClutterActor*) self->priv->item_background);
#line 545 "quicklist-view.c"
	_g_object_unref0 (normal_layer);
	_g_object_unref0 (selected_layer);
	_cairo_surface_destroy0 (normal_surf);
	_cairo_surface_destroy0 (selected_surf);
	_cairo_destroy0 (normal_cr);
	_cairo_destroy0 (selected_cr);
}


#line 322 "quicklist-view.vala"
static gboolean _unity_quicklauncher_quicklist_menu_item_on_enter (UnityQuicklauncherQuicklistMenuItem* self, ClutterEvent* event) {
#line 557 "quicklist-view.c"
	gboolean result;
#line 322 "quicklist-view.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 324 "quicklist-view.vala"
	ctk_layer_set_enabled (ctk_layer_actor_get_layer (self->priv->item_background, (guint) 0), FALSE);
#line 325 "quicklist-view.vala"
	ctk_layer_set_enabled (ctk_layer_actor_get_layer (self->priv->item_background, (guint) 1), TRUE);
#line 326 "quicklist-view.vala"
	clutter_actor_queue_redraw ((ClutterActor*) self->priv->item_background);
#line 567 "quicklist-view.c"
	result = FALSE;
#line 327 "quicklist-view.vala"
	return result;
#line 571 "quicklist-view.c"
}


#line 330 "quicklist-view.vala"
static gboolean _unity_quicklauncher_quicklist_menu_item_on_leave (UnityQuicklauncherQuicklistMenuItem* self, ClutterEvent* event) {
#line 577 "quicklist-view.c"
	gboolean result;
#line 330 "quicklist-view.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 332 "quicklist-view.vala"
	ctk_layer_set_enabled (ctk_layer_actor_get_layer (self->priv->item_background, (guint) 0), TRUE);
#line 333 "quicklist-view.vala"
	ctk_layer_set_enabled (ctk_layer_actor_get_layer (self->priv->item_background, (guint) 1), FALSE);
#line 334 "quicklist-view.vala"
	clutter_actor_queue_redraw ((ClutterActor*) self->priv->item_background);
#line 587 "quicklist-view.c"
	result = FALSE;
#line 335 "quicklist-view.vala"
	return result;
#line 591 "quicklist-view.c"
}


#line 338 "quicklist-view.vala"
static void _unity_quicklauncher_quicklist_menu_item_on_label_changed (UnityQuicklauncherQuicklistMenuItem* self) {
#line 597 "quicklist-view.c"
	char* _tmp0_;
#line 338 "quicklist-view.vala"
	g_return_if_fail (self != NULL);
#line 341 "quicklist-view.vala"
	if (_vala_strcmp0 (self->priv->old_label, ctk_menu_item_get_label ((CtkMenuItem*) self)) == 0) {
#line 342 "quicklist-view.vala"
		return;
#line 605 "quicklist-view.c"
	}
#line 344 "quicklist-view.vala"
	self->priv->old_label = (_tmp0_ = g_strdup (ctk_menu_item_get_label ((CtkMenuItem*) self)), _g_free0 (self->priv->old_label), _tmp0_);
#line 609 "quicklist-view.c"
}


#line 347 "quicklist-view.vala"
UnityQuicklauncherQuicklistMenuItem* unity_quicklauncher_quicklist_menu_item_construct (GType object_type, const char* label) {
#line 615 "quicklist-view.c"
	UnityQuicklauncherQuicklistMenuItem * self;
#line 347 "quicklist-view.vala"
	g_return_val_if_fail (label != NULL, NULL);
#line 349 "quicklist-view.vala"
	self = (UnityQuicklauncherQuicklistMenuItem*) g_object_new (object_type, "label", label, NULL);
#line 621 "quicklist-view.c"
	return self;
}


#line 347 "quicklist-view.vala"
UnityQuicklauncherQuicklistMenuItem* unity_quicklauncher_quicklist_menu_item_new (const char* label) {
#line 347 "quicklist-view.vala"
	return unity_quicklauncher_quicklist_menu_item_construct (UNITY_QUICKLAUNCHER_TYPE_QUICKLIST_MENU_ITEM, label);
#line 630 "quicklist-view.c"
}


#line 338 "quicklist-view.vala"
static void __unity_quicklauncher_quicklist_menu_item_on_label_changed_g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
#line 636 "quicklist-view.c"
	_unity_quicklauncher_quicklist_menu_item_on_label_changed (self);
}


#line 322 "quicklist-view.vala"
static gboolean __unity_quicklauncher_quicklist_menu_item_on_enter_clutter_actor_enter_event (ClutterActor* _sender, ClutterEvent* event, gpointer self) {
#line 643 "quicklist-view.c"
	return _unity_quicklauncher_quicklist_menu_item_on_enter (self, event);
}


#line 330 "quicklist-view.vala"
static gboolean __unity_quicklauncher_quicklist_menu_item_on_leave_clutter_actor_leave_event (ClutterActor* _sender, ClutterEvent* event, gpointer self) {
#line 650 "quicklist-view.c"
	return _unity_quicklauncher_quicklist_menu_item_on_leave (self, event);
}


static GObject * unity_quicklauncher_quicklist_menu_item_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	UnityQuicklauncherQuicklistMenuItem * self;
	parent_class = G_OBJECT_CLASS (unity_quicklauncher_quicklist_menu_item_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = UNITY_QUICKLAUNCHER_QUICKLIST_MENU_ITEM (obj);
	{
		CtkPadding _tmp0_ = {0};
		CtkPadding padding;
		char* _tmp1_;
#line 354 "quicklist-view.vala"
		padding = (memset (&_tmp0_, 0, sizeof (CtkPadding)), _tmp0_.left = (float) ((gint) ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_MARGIN)), _tmp0_.right = (float) ((gint) ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_MARGIN)), _tmp0_.top = (float) ((gint) ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_MARGIN)), _tmp0_.bottom = (float) ((gint) ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_MARGIN)), _tmp0_);
#line 360 "quicklist-view.vala"
		ctk_actor_set_padding ((CtkActor*) self, &padding);
#line 362 "quicklist-view.vala"
		g_signal_connect_object ((GObject*) self, "notify::label", (GCallback) __unity_quicklauncher_quicklist_menu_item_on_label_changed_g_object_notify, self, 0);
#line 363 "quicklist-view.vala"
		g_signal_connect_object ((ClutterActor*) self, "enter-event", (GCallback) __unity_quicklauncher_quicklist_menu_item_on_enter_clutter_actor_enter_event, self, 0);
#line 364 "quicklist-view.vala"
		g_signal_connect_object ((ClutterActor*) self, "leave-event", (GCallback) __unity_quicklauncher_quicklist_menu_item_on_leave_clutter_actor_leave_event, self, 0);
#line 366 "quicklist-view.vala"
		self->priv->old_width = 0;
#line 367 "quicklist-view.vala"
		self->priv->old_height = 0;
#line 368 "quicklist-view.vala"
		self->priv->old_label = (_tmp1_ = g_strdup (""), _g_free0 (self->priv->old_label), _tmp1_);
#line 682 "quicklist-view.c"
	}
	return obj;
}


static void unity_quicklauncher_quicklist_menu_item_class_init (UnityQuicklauncherQuicklistMenuItemClass * klass) {
	unity_quicklauncher_quicklist_menu_item_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (UnityQuicklauncherQuicklistMenuItemPrivate));
	CLUTTER_ACTOR_CLASS (klass)->paint = unity_quicklauncher_quicklist_menu_item_real_paint;
	CLUTTER_ACTOR_CLASS (klass)->get_preferred_height = unity_quicklauncher_quicklist_menu_item_real_get_preferred_height;
	CLUTTER_ACTOR_CLASS (klass)->get_preferred_width = unity_quicklauncher_quicklist_menu_item_real_get_preferred_width;
	CLUTTER_ACTOR_CLASS (klass)->allocate = unity_quicklauncher_quicklist_menu_item_real_allocate;
	G_OBJECT_CLASS (klass)->constructor = unity_quicklauncher_quicklist_menu_item_constructor;
	G_OBJECT_CLASS (klass)->finalize = unity_quicklauncher_quicklist_menu_item_finalize;
}


static void unity_quicklauncher_quicklist_menu_item_instance_init (UnityQuicklauncherQuicklistMenuItem * self) {
	self->priv = UNITY_QUICKLAUNCHER_QUICKLIST_MENU_ITEM_GET_PRIVATE (self);
}


static void unity_quicklauncher_quicklist_menu_item_finalize (GObject* obj) {
	UnityQuicklauncherQuicklistMenuItem * self;
	self = UNITY_QUICKLAUNCHER_QUICKLIST_MENU_ITEM (obj);
	_g_object_unref0 (self->priv->item_background);
	_g_free0 (self->priv->old_label);
	G_OBJECT_CLASS (unity_quicklauncher_quicklist_menu_item_parent_class)->finalize (obj);
}


GType unity_quicklauncher_quicklist_menu_item_get_type (void) {
	static GType unity_quicklauncher_quicklist_menu_item_type_id = 0;
	if (unity_quicklauncher_quicklist_menu_item_type_id == 0) {
		static const GTypeInfo g_define_type_info = { sizeof (UnityQuicklauncherQuicklistMenuItemClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) unity_quicklauncher_quicklist_menu_item_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (UnityQuicklauncherQuicklistMenuItem), 0, (GInstanceInitFunc) unity_quicklauncher_quicklist_menu_item_instance_init, NULL };
		unity_quicklauncher_quicklist_menu_item_type_id = g_type_register_static (CTK_TYPE_MENU_ITEM, "UnityQuicklauncherQuicklistMenuItem", &g_define_type_info, 0);
	}
	return unity_quicklauncher_quicklist_menu_item_type_id;
}


#line 379 "quicklist-view.vala"
static void _unity_quicklauncher_quicklist_menu_round_rect_anchor (UnityQuicklauncherQuicklistMenu* self, cairo_t* cr, double aspect, double x, double y, double corner_radius, double width, double height, double anchor_width, double anchor_height, double anchor_x, double anchor_y) {
#line 726 "quicklist-view.c"
	double radius;
#line 379 "quicklist-view.vala"
	g_return_if_fail (self != NULL);
#line 379 "quicklist-view.vala"
	g_return_if_fail (cr != NULL);
#line 392 "quicklist-view.vala"
	radius = corner_radius / aspect;
#line 395 "quicklist-view.vala"
	cairo_move_to (cr, x + radius, y);
#line 398 "quicklist-view.vala"
	cairo_line_to (cr, (x + width) - radius, y);
#line 401 "quicklist-view.vala"
	cairo_arc (cr, (x + width) - radius, y + radius, radius, ((-90.0f) * G_PI) / 180.0f, (0.0f * G_PI) / 180.0f);
#line 408 "quicklist-view.vala"
	cairo_line_to (cr, x + width, (y + height) - radius);
#line 411 "quicklist-view.vala"
	cairo_arc (cr, (x + width) - radius, (y + height) - radius, radius, (0.0f * G_PI) / 180.0f, (90.0f * G_PI) / 180.0f);
#line 418 "quicklist-view.vala"
	cairo_line_to (cr, x + radius, y + height);
#line 421 "quicklist-view.vala"
	cairo_arc (cr, x + radius, (y + height) - radius, radius, (90.0f * G_PI) / 180.0f, (180.0f * G_PI) / 180.0f);
#line 428 "quicklist-view.vala"
	cairo_line_to (cr, anchor_x + anchor_width, anchor_y + (anchor_height / 2.0f));
#line 431 "quicklist-view.vala"
	cairo_line_to (cr, anchor_x, anchor_y);
#line 434 "quicklist-view.vala"
	cairo_line_to (cr, anchor_x + anchor_width, anchor_y - (anchor_height / 2.0f));
#line 437 "quicklist-view.vala"
	cairo_arc (cr, x + radius, y + radius, radius, (180.0f * G_PI) / 180.0f, (270.0f * G_PI) / 180.0f);
#line 756 "quicklist-view.c"
}


#line 465 "quicklist-view.vala"
static void _unity_quicklauncher_quicklist_menu_outline_mask (UnityQuicklauncherQuicklistMenu* self, cairo_t* cr, gint w, gint h, float anchor_y) {
#line 762 "quicklist-view.c"
	float _tmp0_ = 0.0F;
#line 465 "quicklist-view.vala"
	g_return_if_fail (self != NULL);
#line 465 "quicklist-view.vala"
	g_return_if_fail (cr != NULL);
#line 472 "quicklist-view.vala"
	cairo_set_operator (cr, CAIRO_OPERATOR_CLEAR);
#line 473 "quicklist-view.vala"
	cairo_paint (cr);
#line 476 "quicklist-view.vala"
	cairo_set_operator (cr, CAIRO_OPERATOR_SOURCE);
#line 477 "quicklist-view.vala"
	cairo_scale (cr, (double) 1.0f, (double) 1.0f);
#line 478 "quicklist-view.vala"
	cairo_set_line_width (cr, ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_LINE_WIDTH));
#line 479 "quicklist-view.vala"
	cairo_set_source_rgba (cr, (double) 1.0f, (double) 1.0f, (double) 1.0f, (double) 1.0f);
#line 492 "quicklist-view.vala"
	if (anchor_y != 0.0f) {
#line 492 "quicklist-view.vala"
		_tmp0_ = anchor_y;
#line 784 "quicklist-view.c"
	} else {
#line 492 "quicklist-view.vala"
		_tmp0_ = ((float) h) / 2.0f;
#line 788 "quicklist-view.c"
	}
#line 482 "quicklist-view.vala"
	_unity_quicklauncher_quicklist_menu_round_rect_anchor (self, cr, (double) 1.0f, ctk_em_to_pixel ((double) (UNITY_QUICKLAUNCHER_BORDER + UNITY_QUICKLAUNCHER_ANCHOR_WIDTH)), (double) 0.5f, ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_CORNER_RADIUS), (((double) w) - ctk_em_to_pixel ((double) (UNITY_QUICKLAUNCHER_BORDER + UNITY_QUICKLAUNCHER_ANCHOR_WIDTH))) - 0.5f, ((double) h) - 1.0f, ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_ANCHOR_WIDTH), ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_ANCHOR_HEIGHT), ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_BORDER), (double) _tmp0_);
#line 493 "quicklist-view.vala"
	cairo_stroke (cr);
#line 794 "quicklist-view.c"
}


#line 496 "quicklist-view.vala"
static void _unity_quicklauncher_quicklist_menu_fill_mask (UnityQuicklauncherQuicklistMenu* self, cairo_t* cr, gint w, gint h, float anchor_y) {
#line 800 "quicklist-view.c"
	float _tmp0_ = 0.0F;
#line 496 "quicklist-view.vala"
	g_return_if_fail (self != NULL);
#line 496 "quicklist-view.vala"
	g_return_if_fail (cr != NULL);
#line 503 "quicklist-view.vala"
	cairo_set_operator (cr, CAIRO_OPERATOR_CLEAR);
#line 504 "quicklist-view.vala"
	cairo_paint (cr);
#line 507 "quicklist-view.vala"
	cairo_set_operator (cr, CAIRO_OPERATOR_SOURCE);
#line 508 "quicklist-view.vala"
	cairo_scale (cr, (double) 1.0f, (double) 1.0f);
#line 509 "quicklist-view.vala"
	cairo_set_source_rgba (cr, (double) 1.0f, (double) 1.0f, (double) 1.0f, (double) 1.0f);
#line 522 "quicklist-view.vala"
	if (anchor_y != 0.0f) {
#line 522 "quicklist-view.vala"
		_tmp0_ = anchor_y;
#line 820 "quicklist-view.c"
	} else {
#line 522 "quicklist-view.vala"
		_tmp0_ = ((float) h) / 2.0f;
#line 824 "quicklist-view.c"
	}
#line 512 "quicklist-view.vala"
	_unity_quicklauncher_quicklist_menu_round_rect_anchor (self, cr, (double) 1.0f, ctk_em_to_pixel ((double) (UNITY_QUICKLAUNCHER_BORDER + UNITY_QUICKLAUNCHER_ANCHOR_WIDTH)), (double) 0.5f, ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_CORNER_RADIUS), (((double) w) - ctk_em_to_pixel ((double) (UNITY_QUICKLAUNCHER_BORDER + UNITY_QUICKLAUNCHER_ANCHOR_WIDTH))) - 0.5f, ((double) h) - 1.0f, ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_ANCHOR_WIDTH), ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_ANCHOR_HEIGHT), ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_BORDER), (double) _tmp0_);
#line 524 "quicklist-view.vala"
	cairo_fill (cr);
#line 830 "quicklist-view.c"
}


#line 527 "quicklist-view.vala"
static void _unity_quicklauncher_quicklist_menu_negative_mask (UnityQuicklauncherQuicklistMenu* self, cairo_t* cr, gint w, gint h, float anchor_y) {
#line 836 "quicklist-view.c"
	float _tmp0_ = 0.0F;
#line 527 "quicklist-view.vala"
	g_return_if_fail (self != NULL);
#line 527 "quicklist-view.vala"
	g_return_if_fail (cr != NULL);
#line 534 "quicklist-view.vala"
	cairo_set_operator (cr, CAIRO_OPERATOR_SOURCE);
#line 535 "quicklist-view.vala"
	cairo_set_source_rgba (cr, (double) 1.0f, (double) 1.0f, (double) 1.0f, (double) 1.0f);
#line 536 "quicklist-view.vala"
	cairo_paint (cr);
#line 539 "quicklist-view.vala"
	cairo_set_operator (cr, CAIRO_OPERATOR_CLEAR);
#line 540 "quicklist-view.vala"
	cairo_scale (cr, (double) 1.0f, (double) 1.0f);
#line 554 "quicklist-view.vala"
	if (anchor_y != 0.0f) {
#line 554 "quicklist-view.vala"
		_tmp0_ = anchor_y;
#line 856 "quicklist-view.c"
	} else {
#line 554 "quicklist-view.vala"
		_tmp0_ = ((float) h) / 2.0f;
#line 860 "quicklist-view.c"
	}
#line 543 "quicklist-view.vala"
	_unity_quicklauncher_quicklist_menu_round_rect_anchor (self, cr, (double) 1.0f, ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_BORDER) + ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_ANCHOR_WIDTH), ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_BORDER), ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_CORNER_RADIUS), (double) w, (double) h, ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_ANCHOR_WIDTH), ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_ANCHOR_HEIGHT), ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_BORDER), (double) _tmp0_);
#line 556 "quicklist-view.vala"
	cairo_fill (cr);
#line 866 "quicklist-view.c"
}


#line 559 "quicklist-view.vala"
static void _unity_quicklauncher_quicklist_menu_dotted_bg (UnityQuicklauncherQuicklistMenu* self, cairo_t* cr, gint w, gint h, float anchor_y) {
#line 872 "quicklist-view.c"
	cairo_surface_t* dots;
	cairo_t* cr_dots;
	cairo_pattern_t* pattern;
	float _tmp0_ = 0.0F;
#line 559 "quicklist-view.vala"
	g_return_if_fail (self != NULL);
#line 559 "quicklist-view.vala"
	g_return_if_fail (cr != NULL);
#line 565 "quicklist-view.vala"
	dots = cairo_image_surface_create (CAIRO_FORMAT_ARGB32, 4, 4);
#line 566 "quicklist-view.vala"
	cr_dots = cairo_create (dots);
#line 569 "quicklist-view.vala"
	cairo_set_operator (cr_dots, CAIRO_OPERATOR_CLEAR);
#line 570 "quicklist-view.vala"
	cairo_paint (cr_dots);
#line 571 "quicklist-view.vala"
	cairo_scale (cr_dots, (double) 1.0f, (double) 1.0f);
#line 572 "quicklist-view.vala"
	cairo_set_operator (cr_dots, CAIRO_OPERATOR_SOURCE);
#line 573 "quicklist-view.vala"
	cairo_set_source_rgba (cr_dots, (double) 1.0f, (double) 1.0f, (double) 1.0f, (double) 1.0f);
#line 574 "quicklist-view.vala"
	cairo_rectangle (cr_dots, (double) 0.0f, (double) 0.0f, (double) 1.0f, (double) 1.0f);
#line 575 "quicklist-view.vala"
	cairo_fill (cr_dots);
#line 576 "quicklist-view.vala"
	cairo_rectangle (cr_dots, (double) 2.0f, (double) 2.0f, (double) 1.0f, (double) 1.0f);
#line 577 "quicklist-view.vala"
	cairo_fill (cr_dots);
#line 580 "quicklist-view.vala"
	cairo_set_operator (cr, CAIRO_OPERATOR_CLEAR);
#line 581 "quicklist-view.vala"
	cairo_paint (cr);
#line 584 "quicklist-view.vala"
	pattern = cairo_pattern_create_for_surface (dots);
#line 587 "quicklist-view.vala"
	cairo_set_operator (cr, CAIRO_OPERATOR_SOURCE);
#line 588 "quicklist-view.vala"
	cairo_scale (cr, (double) 1.0f, (double) 1.0f);
#line 589 "quicklist-view.vala"
	cairo_set_source (cr, pattern);
#line 590 "quicklist-view.vala"
	cairo_pattern_set_extend (pattern, CAIRO_EXTEND_REPEAT);
#line 604 "quicklist-view.vala"
	if (anchor_y != 0.0f) {
#line 604 "quicklist-view.vala"
		_tmp0_ = anchor_y;
#line 921 "quicklist-view.c"
	} else {
#line 604 "quicklist-view.vala"
		_tmp0_ = ((float) h) / 2.0f;
#line 925 "quicklist-view.c"
	}
#line 593 "quicklist-view.vala"
	_unity_quicklauncher_quicklist_menu_round_rect_anchor (self, cr, (double) 1.0f, ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_BORDER) + ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_ANCHOR_WIDTH), ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_BORDER), ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_CORNER_RADIUS), (double) w, (double) h, ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_ANCHOR_WIDTH), ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_ANCHOR_HEIGHT), ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_BORDER), (double) _tmp0_);
#line 605 "quicklist-view.vala"
	cairo_fill (cr);
#line 931 "quicklist-view.c"
	_cairo_surface_destroy0 (dots);
	_cairo_destroy0 (cr_dots);
	_cairo_pattern_destroy0 (pattern);
}


#line 608 "quicklist-view.vala"
static void _unity_quicklauncher_quicklist_menu_highlight_bg (UnityQuicklauncherQuicklistMenu* self, cairo_t* cr, gint w, gint h, float anchor_y) {
#line 940 "quicklist-view.c"
	cairo_pattern_t* pattern;
	cairo_pattern_t* _tmp0_;
	float _tmp1_ = 0.0F;
#line 608 "quicklist-view.vala"
	g_return_if_fail (self != NULL);
#line 608 "quicklist-view.vala"
	g_return_if_fail (cr != NULL);
#line 948 "quicklist-view.c"
	pattern = NULL;
#line 617 "quicklist-view.vala"
	cairo_set_operator (cr, CAIRO_OPERATOR_CLEAR);
#line 618 "quicklist-view.vala"
	cairo_paint (cr);
#line 621 "quicklist-view.vala"
	cairo_set_operator (cr, CAIRO_OPERATOR_SOURCE);
#line 622 "quicklist-view.vala"
	cairo_scale (cr, (double) 1.0f, (double) 1.0f);
#line 623 "quicklist-view.vala"
	cairo_set_source_rgba (cr, (double) 1.0f, (double) 1.0f, (double) 1.0f, (double) 1.0f);
#line 626 "quicklist-view.vala"
	pattern = (_tmp0_ = cairo_pattern_create_radial (((double) w) / 2.0f, ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_BORDER), (double) 0.0f, ((double) w) / 2.0f, ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_BORDER), ((double) w) / 2.0f), _cairo_pattern_destroy0 (pattern), _tmp0_);
#line 632 "quicklist-view.vala"
	cairo_pattern_add_color_stop_rgba (pattern, (double) 0.0f, (double) 1.0f, (double) 1.0f, (double) 1.0f, (double) 0.5f);
#line 633 "quicklist-view.vala"
	cairo_pattern_add_color_stop_rgba (pattern, (double) 1.0f, (double) 1.0f, (double) 1.0f, (double) 1.0f, (double) 0.0f);
#line 634 "quicklist-view.vala"
	cairo_set_source (cr, pattern);
#line 648 "quicklist-view.vala"
	if (anchor_y != 0.0f) {
#line 648 "quicklist-view.vala"
		_tmp1_ = anchor_y;
#line 972 "quicklist-view.c"
	} else {
#line 648 "quicklist-view.vala"
		_tmp1_ = ((float) h) / 2.0f;
#line 976 "quicklist-view.c"
	}
#line 637 "quicklist-view.vala"
	_unity_quicklauncher_quicklist_menu_round_rect_anchor (self, cr, (double) 1.0f, ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_BORDER) + ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_ANCHOR_WIDTH), ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_BORDER), ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_CORNER_RADIUS), (double) w, (double) h, ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_ANCHOR_WIDTH), ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_ANCHOR_HEIGHT), ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_BORDER), (double) _tmp1_);
#line 649 "quicklist-view.vala"
	cairo_fill (cr);
#line 982 "quicklist-view.c"
	_cairo_pattern_destroy0 (pattern);
}


#line 652 "quicklist-view.vala"
static void unity_quicklauncher_quicklist_menu_real_allocate (ClutterActor* base, const ClutterActorBox* box, ClutterAllocationFlags flags) {
#line 989 "quicklist-view.c"
	UnityQuicklauncherQuicklistMenu * self;
	gint w = 0;
	gint h = 0;
	float x = 0.0F;
	float y = 0.0F;
	float ax = 0.0F;
	float ay = 0.0F;
	float aw = 0.0F;
	float ah = 0.0F;
	float new_y = 0.0F;
	gboolean _tmp0_ = FALSE;
	CtkActor* actor;
	ClutterColor _tmp1_ = {0};
	ClutterColor outline_color;
	ClutterColor _tmp2_ = {0};
	ClutterColor fill_color;
	CtkLayerActor* _tmp3_;
	CtkLayer* outline_layer;
	CtkLayer* fill_layer;
	CtkLayer* highlight_layer;
	CtkLayer* dotted_layer;
	cairo_surface_t* outline_surf;
	cairo_surface_t* fill_surf;
	cairo_surface_t* negative_surf;
	cairo_surface_t* highlight_surf;
	cairo_surface_t* dotted_surf;
	cairo_t* outline_cr;
	cairo_t* fill_cr;
	cairo_t* negative_cr;
	cairo_t* highlight_cr;
	cairo_t* dotted_cr;
	self = (UnityQuicklauncherQuicklistMenu*) base;
#line 666 "quicklist-view.vala"
	CLUTTER_ACTOR_CLASS (unity_quicklauncher_quicklist_menu_parent_class)->allocate ((ClutterActor*) CTK_MENU (self), box, flags);
#line 667 "quicklist-view.vala"
	w = (gint) ((*box).x2 - (*box).x1);
#line 668 "quicklist-view.vala"
	h = (gint) ((*box).y2 - (*box).y1);
#line 672 "quicklist-view.vala"
	if (self->priv->old_width == w) {
#line 672 "quicklist-view.vala"
		_tmp0_ = self->priv->old_height == h;
#line 1032 "quicklist-view.c"
	} else {
#line 672 "quicklist-view.vala"
		_tmp0_ = FALSE;
#line 1036 "quicklist-view.c"
	}
#line 672 "quicklist-view.vala"
	if (_tmp0_) {
#line 673 "quicklist-view.vala"
		return;
#line 1042 "quicklist-view.c"
	}
#line 675 "quicklist-view.vala"
	actor = _g_object_ref0 (ctk_menu_get_attached_actor ((CtkMenu*) self));
#line 676 "quicklist-view.vala"
	clutter_actor_get_position ((ClutterActor*) actor, &ax, &ay);
#line 677 "quicklist-view.vala"
	clutter_actor_get_size ((ClutterActor*) actor, &aw, &ah);
#line 679 "quicklist-view.vala"
	clutter_actor_get_position ((ClutterActor*) self, &x, &y);
#line 682 "quicklist-view.vala"
	if (ctk_menu_get_num_items ((CtkMenu*) self) != 1) {
#line 683 "quicklist-view.vala"
		new_y = ah / 2.0f;
#line 1056 "quicklist-view.c"
	} else {
#line 685 "quicklist-view.vala"
		new_y = 0.0f;
#line 1060 "quicklist-view.c"
	}
#line 688 "quicklist-view.vala"
	self->priv->old_width = w;
#line 689 "quicklist-view.vala"
	self->priv->old_height = h;
#line 691 "quicklist-view.vala"
	outline_color = (memset (&_tmp1_, 0, sizeof (ClutterColor)), _tmp1_.red = (guint8) 255, _tmp1_.green = (guint8) 255, _tmp1_.blue = (guint8) 255, _tmp1_.alpha = (guint8) 255, _tmp1_);
#line 697 "quicklist-view.vala"
	fill_color = (memset (&_tmp2_, 0, sizeof (ClutterColor)), _tmp2_.red = (guint8) 0, _tmp2_.green = (guint8) 0, _tmp2_.blue = (guint8) 0, _tmp2_.alpha = (guint8) (255.0f * 0.3f), _tmp2_);
#line 711 "quicklist-view.vala"
	if (CTK_IS_LAYER_ACTOR (self->priv->ql_background)) {
#line 712 "quicklist-view.vala"
		clutter_actor_destroy ((ClutterActor*) self->priv->ql_background);
#line 1074 "quicklist-view.c"
	}
#line 713 "quicklist-view.vala"
	self->priv->ql_background = (_tmp3_ = g_object_ref_sink ((CtkLayerActor*) ctk_layer_actor_new ((guint) w, (guint) h)), _g_object_unref0 (self->priv->ql_background), _tmp3_);
#line 722 "quicklist-view.vala"
	outline_layer = ctk_layer_new ((guint) w, (guint) h, CTK_LAYER_REPEAT_NONE, CTK_LAYER_REPEAT_NONE);
#line 726 "quicklist-view.vala"
	fill_layer = ctk_layer_new ((guint) w, (guint) h, CTK_LAYER_REPEAT_NONE, CTK_LAYER_REPEAT_NONE);
#line 730 "quicklist-view.vala"
	highlight_layer = ctk_layer_new ((guint) w, (guint) h, CTK_LAYER_REPEAT_NONE, CTK_LAYER_REPEAT_NONE);
#line 734 "quicklist-view.vala"
	dotted_layer = ctk_layer_new ((guint) w, (guint) h, CTK_LAYER_REPEAT_NONE, CTK_LAYER_REPEAT_NONE);
#line 747 "quicklist-view.vala"
	outline_surf = cairo_image_surface_create (CAIRO_FORMAT_ARGB32, w, h);
#line 750 "quicklist-view.vala"
	fill_surf = cairo_image_surface_create (CAIRO_FORMAT_ARGB32, w, h);
#line 753 "quicklist-view.vala"
	negative_surf = cairo_image_surface_create (CAIRO_FORMAT_ARGB32, w, h);
#line 756 "quicklist-view.vala"
	highlight_surf = cairo_image_surface_create (CAIRO_FORMAT_ARGB32, w, h);
#line 759 "quicklist-view.vala"
	dotted_surf = cairo_image_surface_create (CAIRO_FORMAT_ARGB32, w, h);
#line 764 "quicklist-view.vala"
	outline_cr = cairo_create (outline_surf);
#line 765 "quicklist-view.vala"
	fill_cr = cairo_create (fill_surf);
#line 766 "quicklist-view.vala"
	negative_cr = cairo_create (negative_surf);
#line 767 "quicklist-view.vala"
	highlight_cr = cairo_create (highlight_surf);
#line 768 "quicklist-view.vala"
	dotted_cr = cairo_create (dotted_surf);
#line 771 "quicklist-view.vala"
	_unity_quicklauncher_quicklist_menu_outline_mask (self, outline_cr, w, h, new_y);
#line 772 "quicklist-view.vala"
	_unity_quicklauncher_quicklist_menu_fill_mask (self, fill_cr, w, h, new_y);
#line 773 "quicklist-view.vala"
	_unity_quicklauncher_quicklist_menu_negative_mask (self, negative_cr, w, h, new_y);
#line 774 "quicklist-view.vala"
	_unity_quicklauncher_quicklist_menu_dotted_bg (self, dotted_cr, w, h, new_y);
#line 775 "quicklist-view.vala"
	_unity_quicklauncher_quicklist_menu_highlight_bg (self, highlight_cr, w, h, new_y);
#line 789 "quicklist-view.vala"
	ctk_layer_set_mask_from_surface (fill_layer, fill_surf);
#line 790 "quicklist-view.vala"
	ctk_layer_set_color (fill_layer, &fill_color);
#line 792 "quicklist-view.vala"
	ctk_layer_set_mask_from_surface (dotted_layer, fill_surf);
#line 793 "quicklist-view.vala"
	ctk_layer_set_image_from_surface (dotted_layer, dotted_surf);
#line 794 "quicklist-view.vala"
	ctk_layer_set_opacity (dotted_layer, (guint) ((guint8) (255.0f * 0.15f)));
#line 796 "quicklist-view.vala"
	ctk_layer_set_mask_from_surface (highlight_layer, fill_surf);
#line 797 "quicklist-view.vala"
	ctk_layer_set_image_from_surface (highlight_layer, highlight_surf);
#line 798 "quicklist-view.vala"
	ctk_layer_set_opacity (highlight_layer, (guint) 128);
#line 800 "quicklist-view.vala"
	ctk_layer_set_mask_from_surface (outline_layer, outline_surf);
#line 801 "quicklist-view.vala"
	ctk_layer_set_color (outline_layer, &outline_color);
#line 807 "quicklist-view.vala"
	ctk_layer_actor_add_layer (self->priv->ql_background, fill_layer);
#line 808 "quicklist-view.vala"
	ctk_layer_actor_add_layer (self->priv->ql_background, dotted_layer);
#line 809 "quicklist-view.vala"
	ctk_layer_actor_add_layer (self->priv->ql_background, highlight_layer);
#line 810 "quicklist-view.vala"
	ctk_layer_actor_add_layer (self->priv->ql_background, outline_layer);
#line 813 "quicklist-view.vala"
	ctk_layer_actor_flatten (self->priv->ql_background);
#line 815 "quicklist-view.vala"
	ctk_menu_set_background ((CtkMenu*) self, (ClutterActor*) self->priv->ql_background);
#line 1148 "quicklist-view.c"
	_g_object_unref0 (actor);
	_g_object_unref0 (outline_layer);
	_g_object_unref0 (fill_layer);
	_g_object_unref0 (highlight_layer);
	_g_object_unref0 (dotted_layer);
	_cairo_surface_destroy0 (outline_surf);
	_cairo_surface_destroy0 (fill_surf);
	_cairo_surface_destroy0 (negative_surf);
	_cairo_surface_destroy0 (highlight_surf);
	_cairo_surface_destroy0 (dotted_surf);
	_cairo_destroy0 (outline_cr);
	_cairo_destroy0 (fill_cr);
	_cairo_destroy0 (negative_cr);
	_cairo_destroy0 (highlight_cr);
	_cairo_destroy0 (dotted_cr);
}


#line 373 "quicklist-view.vala"
UnityQuicklauncherQuicklistMenu* unity_quicklauncher_quicklist_menu_construct (GType object_type) {
#line 1169 "quicklist-view.c"
	UnityQuicklauncherQuicklistMenu * self;
	self = g_object_newv (object_type, 0, NULL);
	return self;
}


#line 373 "quicklist-view.vala"
UnityQuicklauncherQuicklistMenu* unity_quicklauncher_quicklist_menu_new (void) {
#line 373 "quicklist-view.vala"
	return unity_quicklauncher_quicklist_menu_construct (UNITY_QUICKLAUNCHER_TYPE_QUICKLIST_MENU);
#line 1180 "quicklist-view.c"
}


static GObject * unity_quicklauncher_quicklist_menu_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	UnityQuicklauncherQuicklistMenu * self;
	parent_class = G_OBJECT_CLASS (unity_quicklauncher_quicklist_menu_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = UNITY_QUICKLAUNCHER_QUICKLIST_MENU (obj);
	{
		CtkPadding _tmp2_ = {0};
		CtkPadding padding;
#line 820 "quicklist-view.vala"
		padding = (memset (&_tmp2_, 0, sizeof (CtkPadding)), _tmp2_.left = (float) ((gint) ctk_em_to_pixel ((double) (UNITY_QUICKLAUNCHER_ANCHOR_WIDTH + (1.75f * UNITY_QUICKLAUNCHER_BORDER)))), _tmp2_.right = (float) ((gint) ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_BORDER)), _tmp2_.top = (float) ((gint) ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_BORDER)), _tmp2_.bottom = (float) 0, _tmp2_);
#line 829 "quicklist-view.vala"
		ctk_actor_set_padding ((CtkActor*) self, &padding);
#line 830 "quicklist-view.vala"
		ctk_menu_set_spacing ((CtkMenu*) self, (gint) ctk_em_to_pixel ((double) UNITY_QUICKLAUNCHER_GAP));
#line 832 "quicklist-view.vala"
		self->priv->old_width = 0;
#line 833 "quicklist-view.vala"
		self->priv->old_height = 0;
#line 1204 "quicklist-view.c"
	}
	return obj;
}


static void unity_quicklauncher_quicklist_menu_class_init (UnityQuicklauncherQuicklistMenuClass * klass) {
	unity_quicklauncher_quicklist_menu_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (UnityQuicklauncherQuicklistMenuPrivate));
	CLUTTER_ACTOR_CLASS (klass)->allocate = unity_quicklauncher_quicklist_menu_real_allocate;
	G_OBJECT_CLASS (klass)->constructor = unity_quicklauncher_quicklist_menu_constructor;
	G_OBJECT_CLASS (klass)->finalize = unity_quicklauncher_quicklist_menu_finalize;
}


static void unity_quicklauncher_quicklist_menu_instance_init (UnityQuicklauncherQuicklistMenu * self) {
	self->priv = UNITY_QUICKLAUNCHER_QUICKLIST_MENU_GET_PRIVATE (self);
}


static void unity_quicklauncher_quicklist_menu_finalize (GObject* obj) {
	UnityQuicklauncherQuicklistMenu * self;
	self = UNITY_QUICKLAUNCHER_QUICKLIST_MENU (obj);
	_g_object_unref0 (self->priv->ql_background);
	G_OBJECT_CLASS (unity_quicklauncher_quicklist_menu_parent_class)->finalize (obj);
}


GType unity_quicklauncher_quicklist_menu_get_type (void) {
	static GType unity_quicklauncher_quicklist_menu_type_id = 0;
	if (unity_quicklauncher_quicklist_menu_type_id == 0) {
		static const GTypeInfo g_define_type_info = { sizeof (UnityQuicklauncherQuicklistMenuClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) unity_quicklauncher_quicklist_menu_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (UnityQuicklauncherQuicklistMenu), 0, (GInstanceInitFunc) unity_quicklauncher_quicklist_menu_instance_init, NULL };
		unity_quicklauncher_quicklist_menu_type_id = g_type_register_static (CTK_TYPE_MENU, "UnityQuicklauncherQuicklistMenu", &g_define_type_info, 0);
	}
	return unity_quicklauncher_quicklist_menu_type_id;
}


static int _vala_strcmp0 (const char * str1, const char * str2) {
	if (str1 == NULL) {
		return -(str1 != str2);
	}
	if (str2 == NULL) {
		return str1 != str2;
	}
	return strcmp (str1, str2);
}




