#!/bin/bash

set -e

# If gnome-session is going to start compiz,
# we don't want to be the ones doing it.
if grep -q compiz /usr/share/gnome-session/sessions/ubuntu.session ; then
  echo "GNOME Session is starting Compiz"
  exit 1
fi

if [ -z "$UPSTART_SESSION" ]; then
  exit 0
fi

status=$(initctl status unity7) || true

if (echo "$status" | grep -q "start/running"); then
  echo "Unity is managed by Upstart"
  exit 1
fi

exit 0
