#!/bin/bash

this_unit=$(sed -n "s,.*:name=systemd:.*/\([^/]\+.service\)[/\b]\?.*,\1,p" /proc/self/cgroup)

# If gnome-session is going to start compiz,
# we don't want to be the ones doing it.
if grep -q compiz /usr/share/gnome-session/sessions/ubuntu.session ; then
  echo "GNOME Session is starting Compiz"

  if [ -n "$this_unit" ] && [[ $string != "unity"* ]]; then
    systemctl --user stop $this_unit
  fi
  exit 1
fi

if [ -z "$UPSTART_SESSION" ]; then
  exit 0
fi

upstart_status=$(initctl status unity7) || true

if (echo "$upstart_status" | grep -q "start/running"); then
  echo "Unity is managed by Upstart"

  if [ -n "$this_unit" ] && [[ $string != "unity"* ]]; then
    systemctl --user stop $this_unit
  fi

  exit 1
fi

exit 0
