#!/usr/bin/python3
# -*- coding: utf-8 -*-
# Copyright (C) 2016 Canonical
#
# Authors:
#  Marco Trevisan <marco.trevisan@canonical.com>
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; version 3.
#
# This program is distributed in the hope that it will be useful, but WITHOUTa
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

from gi.repository import Gio

UNITY_LAUNCHER_SETTINGS = "com.canonical.Unity.Launcher";
UNITY_LAUNCER_FAVORITES = "favorites";

launcher_settings = Gio.Settings.new(UNITY_LAUNCHER_SETTINGS)
favorites = launcher_settings.get_strv(UNITY_LAUNCER_FAVORITES)
replaced = False

for i in range(len(favorites)):
  if 'ubuntu-software-center.desktop' in favorites[i]:
    favorites[i] = favorites[i].replace('ubuntu-software-center', 'org.gnome.Software')
    replaced = True

if replaced:
  launcher_settings.set_strv(UNITY_LAUNCER_FAVORITES, favorites)
  Gio.Settings.sync()
