#!/usr/bin/python3
# -*- coding: utf-8 -*-
# Copyright (C) 2014-2017 Canonical
#
# Authors:
#  Marco Trevisan <marco.trevisan@canonical.com>
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; version 3.
#
# This program is distributed in the hope that it will be useful, but WITHOUTa
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

from gi.repository import Gio
import os,sys

GNOME_UI_SETTINGS = "org.gnome.desktop.interface";
UBUNTU_UI_SETTINGS = "com.ubuntu.user-interface.desktop";

KEYS_TO_MIGRATE = [ "scaling-factor", "text-scaling-factor", "cursor-size" ]

gnome_ui_schema = Gio.SettingsSchemaSource.get_default().lookup(GNOME_UI_SETTINGS, recursive=False)
if not gnome_ui_schema:
    print("No gnome desktop interface schemas found, no migration needed")
    sys.exit(0)

ubuntu_ui_schema = Gio.SettingsSchemaSource.get_default().lookup(UBUNTU_UI_SETTINGS, recursive=False)
if not ubuntu_ui_schema:
    print("No ubuntu desktop interface schemas found, no migration needed")
    sys.exit(0)

gnome_settings = Gio.Settings(settings_schema=gnome_ui_schema)
ubuntu_settings = Gio.Settings(settings_schema=ubuntu_ui_schema)

for key in KEYS_TO_MIGRATE:
  gnome_value = gnome_settings.get_value(key)
  ubuntu_value = ubuntu_settings.get_value(key)

  if ubuntu_value != gnome_value:
    ubuntu_settings.set_value(key, gnome_value)

Gio.Settings.sync()
